import { entriesFromBundle, type BiomeBundle } from "./shared.js";

const brasilBundle = {
  biome: "brasil",
  prefix: "bra",
  editorialSource: "curadoria-cruzaverso-brasil-v1",
  sources: [
    {
      sourceId: "ibge-territorio",
      title: "IBGE Educa — Divisão territorial",
      url: "https://educa.ibge.gov.br/jovens/conheca-o-brasil/territorio/19637-divisao-territorial.html",
      license: "Uso informativo institucional; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "ibge-mapa",
      title: "IBGE — Mapa político do Brasil",
      url: "https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-de-referencia/15816-politico.html?lang=pt-BR",
      license: "Uso informativo institucional; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "ibge-cidades",
      title: "IBGE — Cidades e Estados",
      url: "https://www.ibge.gov.br/cidades-e-estados.html",
      license: "Uso informativo institucional; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "icmbio-parques",
      title: "ICMBio — Lista dos parques nacionais",
      url: "https://www.gov.br/icmbio/pt-br/assuntos/unidades-de-conservacao/parna/lista-dos-parques-nacionais/",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "iphan-mundial",
      title: "IPHAN — Lista do Patrimônio Mundial no Brasil",
      url: "https://www.gov.br/iphan/pt-br/patrimonio-cultural/internacional/reconhecimento-internacional-1/lista-do-patrimonio-mundial-convencao-para-a-protecao-do-patrimonio-mundial-cultural-e-natural-1972",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "iphan-imaterial",
      title: "IPHAN — Patrimônio Imaterial",
      url: "https://www.gov.br/iphan/pt-br/patrimonio-cultural/patrimonio-imaterial",
      license: "CC BY-ND 3.0 BR; consulta factual e pistas autorais",
      role: "factual",
    },
    {
      sourceId: "iphan-inventarios",
      title: "IPHAN — Projetos de identificação de bens culturais imateriais",
      url: "https://www.gov.br/iphan/pt-br/patrimonio-cultural/patrimonio-imaterial/identificacao-de-bens-culturais/projetos-realizados-de-identificacao-de-bens-culturais-imateriais",
      license: "CC BY-ND 3.0 BR; consulta factual e pistas autorais",
      role: "factual",
    },
    {
      sourceId: "iphan-pernambuco",
      title: "IPHAN Pernambuco — Patrimônio imaterial",
      url: "https://www.gov.br/iphan/pt-br/superintendencias/pernambuco/patrimonio-imaterial",
      license: "CC BY-ND 3.0 BR; consulta factual e pistas autorais",
      role: "factual",
    },
    {
      sourceId: "iphan-rio",
      title: "IPHAN Rio de Janeiro — Patrimônio imaterial",
      url: "https://www.gov.br/iphan/pt-br/superintendencias/rio-de-janeiro/patrimonio-imaterial",
      license: "CC BY-ND 3.0 BR; consulta factual e pistas autorais",
      role: "factual",
    },
    {
      sourceId: "iphan-para",
      title: "IPHAN Pará — Patrimônio imaterial",
      url: "https://www.gov.br/iphan/pt-br/superintendencias/para/patrimonio-imaterial",
      license: "CC BY-ND 3.0 BR; consulta factual e pistas autorais",
      role: "factual",
    },
    {
      sourceId: "iphan-mato-grosso",
      title: "IPHAN Mato Grosso — Patrimônio imaterial",
      url: "https://www.gov.br/iphan/pt-br/superintendencias/mato-grosso/patrimonio-imaterial",
      license: "CC BY-ND 3.0 BR; consulta factual e pistas autorais",
      role: "factual",
    },
    {
      sourceId: "iphan-parana",
      title: "IPHAN Paraná — Patrimônio imaterial",
      url: "https://www.gov.br/iphan/pt-br/superintendencias/parana/patrimonio-imaterial",
      license: "CC BY-ND 3.0 BR; consulta factual e pistas autorais",
      role: "factual",
    },
    {
      sourceId: "iphan-piaui",
      title: "IPHAN Piauí — Patrimônio imaterial",
      url: "https://www.gov.br/iphan/pt-br/superintendencias/piaui/patrimonio-imaterial",
      license: "CC BY-ND 3.0 BR; consulta factual e pistas autorais",
      role: "factual",
    },
    {
      sourceId: "iphan-marabaixo",
      title: "IPHAN — Marabaixo ganha plano de salvaguarda",
      url: "https://www.gov.br/iphan/pt-br/assuntos/noticias/marabaixo-ganha-plano-de-salvaguarda",
      license: "CC BY-ND 3.0 BR; consulta factual e pistas autorais",
      role: "factual",
    },
    {
      sourceId: "iphan-repente",
      title: "IPHAN — Repente registrado como Patrimônio Cultural do Brasil",
      url: "https://www.gov.br/iphan/pt-br/assuntos/noticias/referencia-para-a-identidade-nordestina-repente-e-registrado-como-patrimonio-cultural-do-brasil-1",
      license: "CC BY-ND 3.0 BR; consulta factual e pistas autorais",
      role: "factual",
    },
    {
      sourceId: "iphan-capoeira",
      title: "IPHAN — Salvaguarda da capoeira",
      url: "https://www.gov.br/iphan/pt-br/assuntos/noticias/iphan-disponibiliza-plano-de-salvaguarda-da-capoeira-em-rondonia",
      license: "CC BY-ND 3.0 BR; consulta factual e pistas autorais",
      role: "factual",
    },
    {
      sourceId: "iphan-karaja",
      title: "IPHAN — Modo de fazer bonecas Karajá",
      url: "https://www.gov.br/iphan/pt-br/assuntos/noticias/modo-de-fazer-bonecas-karaja-ganha-plano-de-salvaguarda",
      license: "CC BY-ND 3.0 BR; consulta factual e pistas autorais",
      role: "factual",
    },
    {
      sourceId: "iphan-queijo",
      title: "IPHAN — Modos de fazer o queijo Minas artesanal",
      url: "https://www.gov.br/iphan/pt-br/assuntos/noticias/modos-de-fazer-o-queijo-minas-artesanal-ganha-plano-de-salvaguarda",
      license: "CC BY-ND 3.0 BR; consulta factual e pistas autorais",
      role: "factual",
    },
    {
      sourceId: "saude-alimentos",
      title: "Ministério da Saúde — Alimentos regionais brasileiros",
      url: "https://bvsms.saude.gov.br/bvs/publicacoes/alimentos_regionais_brasileiros_2ed.pdf",
      license: "Uso informativo institucional; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "santarem-culinaria",
      title: "Prefeitura de Santarém — Culinária",
      url: "https://turismo.santarem.pa.gov.br/culinaria",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "fundaj-amazonica",
      title: "Fundação Joaquim Nabuco — Alimentação amazônica",
      url: "https://pesquisaescolar.fundaj.gov.br/pt-br/artigo/alimentacao-amazonica-ver-tambem-cozinha-amazonica/",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "embrapa-caupi",
      title: "Embrapa Meio-Norte — Receitas com feijão-caupi",
      url: "https://www.embrapa.br/en/web/meio-norte/receitas-caupi",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "ipac-acaraje",
      title: "IPAC Bahia — Ofício das baianas de acarajé",
      url: "https://www.ba.gov.br/ipac/oficio-das-baianas-do-acaraje",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "parana-barreado",
      title: "Paraná Turismo — Barreado",
      url: "https://www.paranaturismo.pr.gov.br/Turista/Pagina/Barreado",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "es-culinaria",
      title: "Governo do Espírito Santo — Culinária capixaba",
      url: "https://www.es.gov.br/cultura/culinaria-capixaba",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "funarte-choro",
      title: "Funarte — Dia Nacional do Choro",
      url: "https://www.gov.br/funarte/pt-br/assuntos/noticias/todas-noticias/funarte-comemora-o-dia-nacional-do-choro-e-aniversario-de-pixinguinha",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "funarte-forro",
      title: "Funarte — Dia Nacional do Forró",
      url: "https://www.gov.br/funarte/pt-br/assuntos/noticias/todas-noticias/funarte-celebra-13-de-dezembro-dia-nacional-do-forro-e-aniversario-de-luiz-gonzaga/",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "dicionario-mpb",
      title: "Instituto Cultural Cravo Albin — Dicionário da Música Popular Brasileira",
      url: "https://dicionariompb.com.br/",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "mma-pct",
      title: "Ministério do Meio Ambiente — Povos e Comunidades Tradicionais",
      url: "https://www.gov.br/mma/pt-br/composicao/snpct/pdpct",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "palmares",
      title: "Fundação Cultural Palmares — Informações Quilombolas",
      url: "https://www.gov.br/palmares/pt-br/departamentos/protecao-preservacao-e-articulacao/informacoes-quilombolas/",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "funai-institucional",
      title: "Funai — Informações institucionais e diversidade dos povos indígenas",
      url: "https://www.gov.br/funai/pt-br/acesso-a-informacao/institucional/Institucional",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "ibge-quebradeiras",
      title: "Agência IBGE Notícias — Quebradeiras de coco babaçu",
      url: "https://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/23624-quebradeiras-de-coco-babacu-preservam-tradicao-no-interior-do-maranhao",
      license: "Uso informativo institucional; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "goiania-peteca",
      title: "Secretaria Municipal de Educação de Goiânia — Peteca",
      url: "https://sme.goiania.go.gov.br/conexaoescola/ensino_fundamental/educacao-fisica-esportes-de-rede-ou-parede-peteca/",
      license: "Uso informativo institucional; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "planalto-bandeira",
      title: "Presidência da República — Bandeira Nacional",
      url: "https://www.gov.br/planalto/pt-br/conheca-a-presidencia/biblioteca-da-pr/simbolos-nacionais/bandeira/bandeira-nacional",
      license: "Uso informativo institucional; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "camara-pau-brasil",
      title: "Câmara dos Deputados — Pau-brasil",
      url: "https://www2.camara.leg.br/a-camara/estruturaadm/gestao-na-camara-dos-deputados/responsabilidade-social-e-ambiental/ecocamara/recursos/bosque-dos-constituintes/flora-local/as-4-arvores-historicas/pau-brasil",
      license: "Uso informativo institucional; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "saude-sus",
      title: "Ministério da Saúde — Sistema Único de Saúde",
      url: "https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/sus",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "iphan-institucional",
      title: "IPHAN — Informações institucionais",
      url: "https://www.gov.br/iphan/pt-br/acesso-a-informacao/institucional",
      license: "CC BY-ND 3.0 BR; consulta factual e pistas autorais",
      role: "factual",
    },
    {
      sourceId: "iphan-material",
      title: "IPHAN — Patrimônio Material",
      url: "https://www.gov.br/iphan/pt-br/patrimonio-cultural/patrimonio-material/",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "rio-frescobol",
      title: "Prefeitura do Rio — Frescobol como patrimônio imaterial carioca",
      url: "https://www.rio.rj.gov.br/web/guest/exibeconteudo?id=5196550",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "ibge-esportes",
      title: "IBGE — Características de modalidades e instalações esportivas",
      url: "https://www.ibge.gov.br/biblioteca/visualizacao/instrumentos_de_coleta/doc3271.pdf",
      license: "Uso informativo institucional; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "planalto-simbolos",
      title: "Presidência da República — Lei dos símbolos nacionais",
      url: "https://www.planalto.gov.br/ccivil_03/leis/l5700compilado.htm",
      license: "Legislação brasileira; consulta factual",
      role: "factual",
    },
    {
      sourceId: "bcb-real",
      title: "Banco Central do Brasil — Real",
      url: "https://www.bcb.gov.br/cedulasemoedas/real",
      license: "Uso informativo institucional; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "embrapa-nhecolandia",
      title: "Embrapa Pantanal — Solos da sub-região da Nhecolândia",
      url: "https://www.infoteca.cnptia.embrapa.br/infoteca/handle/doc/787697",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "boa-vista-damurida",
      title: "Prefeitura de Boa Vista — Damurida na cultura roraimense",
      url: "https://boavista.rr.gov.br/noticias/2022/7/bv-132-anos-damurida-o-sabor-que-faz-parte-da-nossa-cultura",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "cultura-am-toada",
      title: "Secretaria de Cultura do Amazonas — Toada de boi-bumbá",
      url: "https://cultura.am.gov.br/projeto-traz-a-manaus-exposicao-coletiva-de-artistas-parintinenses-e-show-do-grupo-toada-de-roda/?lang=pt",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "mesp-futevolei",
      title: "Ministério do Esporte — Futevôlei nos Jogos Universitários de Praia",
      url: "https://www.gov.br/esporte/pt-br/noticias-e-conteudos/esporte/ministro-paulo-henrique-abre-o-jubs-praia-2026-em-guarapari-e-celebra-esporte-universitario",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "mesp-futsal",
      title: "Ministério do Esporte — Campeonato Brasileiro de Futsal Escolar",
      url: "https://www.gov.br/esporte/pt-br/noticias-e-conteudos/esporte/brasilia-vai-sediar-o-campeonato-brasileiro-de-futsal-escolar-sub-17",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
  ],
  records: [
    // Território, unidades federativas, capitais e gentílicos — 85
    ["Brasil", "Do Oiapoque ao Chuí, cabe num tabuleiro", "País sul-americano de língua oficial portuguesa, com 26 estados e um Distrito Federal.", "association", 1, 5, ["território", "nacional"], ["ibge-territorio"]],
    ["Norte", "Sete UFs, de Rio Branco a Palmas", "Grande Região formada por AC, AP, AM, PA, RO, RR e TO.", "trivia", 2, 5, ["região", "território"], ["ibge-territorio"]],
    ["Nordeste", "Nove UFs voltadas em grande parte ao Atlântico", "Grande Região formada por AL, BA, CE, MA, PB, PE, PI, RN e SE.", "trivia", 2, 5, ["região", "território"], ["ibge-territorio"]],
    ["Centro-Oeste", "Três estados e o quadradinho federal?", "Grande Região formada por DF, GO, MT e MS.", "wordplay", 2, 5, ["região", "território"], ["ibge-territorio"]],
    ["Sudeste", "Quatro UFs, três delas banhadas pelo Atlântico", "Grande Região formada por ES, MG, RJ e SP.", "trivia", 2, 5, ["região", "território"], ["ibge-territorio"]],
    ["Sul", "Trio regional de Curitiba, Florianópolis e Porto Alegre", "Grande Região formada por PR, SC e RS.", "trivia", 1, 5, ["região", "território"], ["ibge-territorio"]],

    ["Acre", "Rio Branco governa perto da fronteira peruana", "Unidade federativa cuja capital é Rio Branco.", "trivia", 2, 4, ["estado", "norte"], ["ibge-cidades"]],
    ["Alagoas", "Maceió governa entre Pernambuco e Sergipe", "Unidade federativa cuja capital é Maceió.", "trivia", 2, 4, ["estado", "nordeste"], ["ibge-cidades"]],
    ["Amapá", "Macapá governa na linha do Equador", "Unidade federativa cuja capital é Macapá.", "trivia", 2, 4, ["estado", "norte"], ["ibge-cidades"]],
    ["Amazonas", "Manaus governa a maior UF em área", "Unidade federativa cuja capital é Manaus.", "trivia", 1, 5, ["estado", "norte"], ["ibge-cidades"]],
    ["Bahia", "Salvador governa a terra do Recôncavo", "Unidade federativa cuja capital é Salvador.", "trivia", 1, 5, ["estado", "nordeste"], ["ibge-cidades"]],
    ["Ceará", "Fortaleza governa a terra de Iracema", "Unidade federativa cuja capital é Fortaleza.", "association", 1, 5, ["estado", "nordeste"], ["ibge-cidades"]],
    ["Distrito Federal", "Quadradinho que abriga Brasília?", "Unidade federativa onde fica a capital do país.", "wordplay", 1, 5, ["unidade-federativa", "centro-oeste"], ["ibge-cidades"]],
    ["Espírito Santo", "Vitória governa entre Bahia, Minas e oceano", "Unidade federativa cuja capital é Vitória.", "trivia", 2, 4, ["estado", "sudeste"], ["ibge-cidades"]],
    ["Goiás", "Goiânia governa no coração do mapa", "Unidade federativa cuja capital é Goiânia.", "association", 1, 5, ["estado", "centro-oeste"], ["ibge-cidades"]],
    ["Maranhão", "São Luís governa a terra dos Lençóis", "Unidade federativa cuja capital é São Luís.", "association", 2, 5, ["estado", "nordeste"], ["ibge-cidades"]],
    ["Mato Grosso", "Cuiabá governa a UF de Chapada e planície alagável", "Unidade federativa cuja capital é Cuiabá.", "association", 2, 5, ["estado", "centro-oeste"], ["ibge-cidades"]],
    ["Mato Grosso do Sul", "Campo Grande governa entre Goiás, Paraguai e Paraná", "Unidade federativa cuja capital é Campo Grande.", "trivia", 2, 4, ["estado", "centro-oeste"], ["ibge-cidades"]],
    ["Minas Gerais", "Belo Horizonte governa a UF sem litoral", "Unidade federativa cuja capital é Belo Horizonte.", "trivia", 1, 5, ["estado", "sudeste"], ["ibge-cidades"]],
    ["Pará", "Belém governa a UF cortada pela linha do Equador", "UF cuja capital é Belém.", "trivia", 2, 5, ["estado", "norte"], ["ibge-cidades"]],
    ["Paraíba", "João Pessoa governa a UF do extremo oriental continental", "Unidade federativa cuja capital é João Pessoa.", "trivia", 2, 4, ["estado", "nordeste"], ["ibge-cidades"]],
    ["Paraná", "Curitiba governa entre São Paulo e Santa Catarina", "Unidade federativa cuja capital é Curitiba.", "trivia", 1, 5, ["estado", "sul"], ["ibge-cidades"]],
    ["Pernambuco", "Recife governa a UF de Fernando de Noronha", "Unidade federativa cuja capital é Recife.", "trivia", 1, 5, ["estado", "nordeste"], ["ibge-cidades"]],
    ["Piauí", "Teresina governa a UF do Delta do Parnaíba", "Unidade federativa cuja capital é Teresina.", "trivia", 2, 4, ["estado", "nordeste"], ["ibge-cidades"]],
    ["Rio de Janeiro", "Entre Minas, Espírito Santo e o Atlântico, capital homônima", "Unidade federativa sudestina cuja capital é a Cidade Maravilhosa.", "trivia", 1, 5, ["estado", "sudeste"], ["ibge-cidades"]],
    ["Rio Grande do Norte", "Natal governa na esquina atlântica do país", "Unidade federativa cuja capital é Natal.", "association", 2, 4, ["estado", "nordeste"], ["ibge-cidades"]],
    ["Rio Grande do Sul", "Porto Alegre governa a UF mais meridional", "Unidade federativa cuja capital é Porto Alegre.", "trivia", 1, 5, ["estado", "sul"], ["ibge-cidades"]],
    ["Rondônia", "Porto Velho governa junto à Bolívia", "Unidade federativa cuja capital é Porto Velho.", "trivia", 2, 4, ["estado", "norte"], ["ibge-cidades"]],
    ["Roraima", "Boa Vista governa a UF mais setentrional", "Unidade federativa cuja capital é Boa Vista.", "trivia", 2, 4, ["estado", "norte"], ["ibge-cidades"]],
    ["Santa Catarina", "Florianópolis governa entre Paraná e Rio Grande do Sul", "Unidade federativa cuja capital é Florianópolis.", "trivia", 1, 5, ["estado", "sul"], ["ibge-cidades"]],
    ["São Paulo", "Entre Paraná, Minas, Rio e Atlântico, capital homônima", "Unidade federativa sudestina cuja capital é a maior cidade do país.", "trivia", 1, 5, ["estado", "sudeste"], ["ibge-cidades"]],
    ["Sergipe", "Aracaju governa o menor estado em área", "Unidade federativa cuja capital é Aracaju.", "trivia", 2, 4, ["estado", "nordeste"], ["ibge-cidades"]],
    ["Tocantins", "Palmas governa a mais jovem UF estadual", "Unidade federativa cuja capital é Palmas.", "trivia", 2, 4, ["estado", "norte"], ["ibge-cidades"]],

    ["Rio Branco", "Capital acreana com nome de barão?", "Capital do Acre.", "wordplay", 2, 4, ["capital", "norte"], ["ibge-cidades"]],
    ["Maceió", "Capital alagoana entre lagoas e Atlântico", "Capital de Alagoas.", "association", 1, 5, ["capital", "nordeste"], ["ibge-cidades"]],
    ["Macapá", "Capital atravessada pela linha do Equador", "Capital do Amapá.", "trivia", 2, 4, ["capital", "norte"], ["ibge-cidades"]],
    ["Manaus", "Capital amazonense às margens do Rio Negro", "Capital do Amazonas.", "association", 1, 5, ["capital", "norte"], ["ibge-cidades"]],
    ["Salvador", "Primeira capital colonial, hoje baiana", "Capital da Bahia.", "trivia", 1, 5, ["capital", "nordeste"], ["ibge-cidades"]],
    ["Fortaleza", "Capital cearense voltada ao Atlântico", "Capital do Ceará.", "association", 1, 5, ["capital", "nordeste"], ["ibge-cidades"]],
    ["Brasília", "Capital desenhada no Planalto Central", "Capital do Brasil e sede do Distrito Federal.", "association", 1, 5, ["capital", "centro-oeste"], ["ibge-cidades"]],
    ["Vitória", "Capital capixaba assentada em ilhas e continente", "Capital do Espírito Santo.", "trivia", 2, 4, ["capital", "sudeste"], ["ibge-cidades"]],
    ["Goiânia", "Capital goiana planejada no século XX", "Capital de Goiás.", "trivia", 2, 5, ["capital", "centro-oeste"], ["ibge-cidades"]],
    ["São Luís", "Capital maranhense na ilha de Upaon-Açu", "Capital do Maranhão.", "trivia", 2, 4, ["capital", "nordeste"], ["ibge-cidades"]],
    ["Cuiabá", "Capital mato-grossense quase no centro continental", "Capital de Mato Grosso.", "association", 2, 4, ["capital", "centro-oeste"], ["ibge-cidades"]],
    ["Campo Grande", "Capital sul-mato-grossense", "Capital de Mato Grosso do Sul.", "elliptical", 1, 5, ["capital", "centro-oeste"], ["ibge-cidades"]],
    ["Belo Horizonte", "Capital mineira abraçada pela Serra do Curral", "Capital de Minas Gerais.", "association", 1, 5, ["capital", "sudeste"], ["ibge-cidades"]],
    ["Belém", "Capital paraense às portas do estuário amazônico", "Capital do Pará.", "association", 1, 5, ["capital", "norte"], ["ibge-cidades"]],
    ["João Pessoa", "Capital paraibana no litoral oriental", "Capital da Paraíba.", "association", 2, 4, ["capital", "nordeste"], ["ibge-cidades"]],
    ["Curitiba", "Capital paranaense no primeiro planalto", "Capital do Paraná.", "association", 1, 5, ["capital", "sul"], ["ibge-cidades"]],
    ["Recife", "Capital pernambucana cortada por rios e pontes", "Capital de Pernambuco.", "association", 1, 5, ["capital", "nordeste"], ["ibge-cidades"]],
    ["Teresina", "Capital piauiense à beira do Parnaíba", "Capital do Piauí.", "association", 2, 4, ["capital", "nordeste"], ["ibge-cidades"]],
    ["Natal", "Capital potiguar batizada pelo calendário?", "Capital do Rio Grande do Norte.", "wordplay", 1, 5, ["capital", "nordeste"], ["ibge-cidades"]],
    ["Porto Alegre", "Capital gaúcha às margens do Guaíba", "Capital do Rio Grande do Sul.", "association", 1, 5, ["capital", "sul"], ["ibge-cidades"]],
    ["Porto Velho", "Capital rondoniense às margens do Madeira", "Capital de Rondônia.", "association", 2, 4, ["capital", "norte"], ["ibge-cidades"]],
    ["Boa Vista", "Única capital brasileira inteiramente ao norte do Equador", "Capital de Roraima.", "trivia", 2, 4, ["capital", "norte"], ["ibge-cidades"]],
    ["Florianópolis", "Capital catarinense entre ilha e continente", "Capital de Santa Catarina.", "association", 1, 5, ["capital", "sul"], ["ibge-cidades"]],
    ["Aracaju", "Capital sergipana às margens do Sergipe", "Capital de Sergipe.", "association", 2, 4, ["capital", "nordeste"], ["ibge-cidades"]],
    ["Palmas", "Capital tocantinense inaugurada no fim do século XX", "Capital do Tocantins.", "trivia", 2, 4, ["capital", "norte"], ["ibge-cidades"]],

    ["acreano", "Do Acre, por nascimento", "Gentílico de quem nasce no Acre.", "elliptical", 2, 4, ["gentílico", "norte"], ["ibge-cidades"]],
    ["alagoano", "De Alagoas, por nascimento", "Gentílico de quem nasce em Alagoas.", "elliptical", 2, 4, ["gentílico", "nordeste"], ["ibge-cidades"]],
    ["amapaense", "Do Amapá, por nascimento", "Gentílico de quem nasce no Amapá.", "elliptical", 3, 3, ["gentílico", "norte"], ["ibge-cidades"]],
    ["amazonense", "Do Amazonas, por nascimento", "Gentílico de quem nasce no Amazonas.", "elliptical", 2, 4, ["gentílico", "norte"], ["ibge-cidades"]],
    ["baiano", "Da Bahia, por nascimento", "Gentílico de quem nasce na Bahia.", "elliptical", 1, 5, ["gentílico", "nordeste"], ["ibge-cidades"]],
    ["cearense", "Do Ceará, por nascimento", "Gentílico de quem nasce no Ceará.", "elliptical", 1, 5, ["gentílico", "nordeste"], ["ibge-cidades"]],
    ["brasiliense", "Do Distrito Federal, por nascimento", "Gentílico de quem nasce no Distrito Federal.", "elliptical", 2, 5, ["gentílico", "centro-oeste"], ["ibge-cidades"]],
    ["capixaba", "Do Espírito Santo, por nascimento", "Gentílico de quem nasce no Espírito Santo.", "elliptical", 2, 5, ["gentílico", "sudeste"], ["ibge-cidades"]],
    ["goiano", "De Goiás, por nascimento", "Gentílico de quem nasce em Goiás.", "elliptical", 1, 5, ["gentílico", "centro-oeste"], ["ibge-cidades"]],
    ["maranhense", "Do Maranhão, por nascimento", "Gentílico de quem nasce no Maranhão.", "elliptical", 2, 4, ["gentílico", "nordeste"], ["ibge-cidades"]],
    ["mato-grossense", "De Mato Grosso, por nascimento", "Gentílico de quem nasce em Mato Grosso.", "elliptical", 2, 4, ["gentílico", "centro-oeste"], ["ibge-cidades"]],
    ["sul-mato-grossense", "De Mato Grosso do Sul, por nascimento", "Gentílico de quem nasce em Mato Grosso do Sul.", "elliptical", 3, 3, ["gentílico", "centro-oeste"], ["ibge-cidades"]],
    ["mineiro", "De Minas Gerais, por nascimento", "Gentílico de quem nasce em Minas Gerais.", "elliptical", 1, 5, ["gentílico", "sudeste"], ["ibge-cidades"]],
    ["paraense", "Do Pará, por nascimento", "Gentílico de quem nasce no Pará.", "elliptical", 2, 4, ["gentílico", "norte"], ["ibge-cidades"]],
    ["paraibano", "Da Paraíba, por nascimento", "Gentílico de quem nasce na Paraíba.", "elliptical", 2, 4, ["gentílico", "nordeste"], ["ibge-cidades"]],
    ["paranaense", "Do Paraná, por nascimento", "Gentílico de quem nasce no Paraná.", "elliptical", 2, 4, ["gentílico", "sul"], ["ibge-cidades"]],
    ["pernambucano", "De Pernambuco, por nascimento", "Gentílico de quem nasce em Pernambuco.", "elliptical", 2, 4, ["gentílico", "nordeste"], ["ibge-cidades"]],
    ["piauiense", "Do Piauí, por nascimento", "Gentílico de quem nasce no Piauí.", "elliptical", 2, 4, ["gentílico", "nordeste"], ["ibge-cidades"]],
    ["fluminense", "Do estado cuja capital é a Cidade Maravilhosa", "Gentílico de quem nasce no estado do Rio de Janeiro.", "elliptical", 2, 5, ["gentílico", "sudeste"], ["ibge-cidades"]],
    ["potiguar", "Do Rio Grande do Norte, em palavra de raiz tupi", "Gentílico de quem nasce no Rio Grande do Norte.", "trivia", 2, 4, ["gentílico", "nordeste"], ["ibge-cidades"]],
    ["gaúcho", "Do Rio Grande do Sul, no uso brasileiro", "Gentílico de quem nasce no Rio Grande do Sul.", "elliptical", 1, 5, ["gentílico", "sul"], ["ibge-cidades"]],
    ["rondoniense", "De Rondônia, por nascimento", "Gentílico de quem nasce em Rondônia.", "elliptical", 3, 3, ["gentílico", "norte"], ["ibge-cidades"]],
    ["roraimense", "De Roraima, por nascimento", "Gentílico de quem nasce em Roraima.", "elliptical", 3, 3, ["gentílico", "norte"], ["ibge-cidades"]],
    ["catarinense", "De Santa Catarina, por nascimento", "Gentílico de quem nasce em Santa Catarina.", "elliptical", 2, 4, ["gentílico", "sul"], ["ibge-cidades"]],
    ["paulista", "Do estado mais populoso", "Gentílico de quem nasce no estado de São Paulo.", "elliptical", 1, 5, ["gentílico", "sudeste"], ["ibge-cidades"]],
    ["sergipano", "De Sergipe, por nascimento", "Gentílico de quem nasce em Sergipe.", "elliptical", 2, 4, ["gentílico", "nordeste"], ["ibge-cidades"]],
    ["tocantinense", "Do Tocantins, por nascimento", "Gentílico de quem nasce no Tocantins.", "elliptical", 3, 3, ["gentílico", "norte"], ["ibge-cidades"]],

    // Paisagens e lugares de referência — 25 (cinco por Grande Região)
    ["Marajó", "Ilha paraense entre águas fluviais e atlânticas", "Ilha e arquipélago na foz do Amazonas, no Pará.", "association", 2, 4, ["paisagem", "norte"], ["ibge-mapa", "iphan-para"]],
    ["Anavilhanas", "Labirinto de ilhas no Rio Negro", "Arquipélago fluvial e parque nacional no Amazonas.", "association", 3, 3, ["paisagem", "norte"], ["icmbio-parques"]],
    ["Jalapão", "Dunas douradas e fervedouros tocantinenses", "Região turística e protegida no leste do Tocantins.", "association", 2, 4, ["paisagem", "norte"], ["ibge-mapa"]],
    ["Xingu", "Nome que une rio e território indígena", "Rio amazônico e região indígena no norte de Mato Grosso.", "association", 2, 5, ["rio", "norte", "povos-indígenas"], ["ibge-mapa", "funai-institucional"]],
    ["Solimões", "Nome do grande rio antes do encontro com o Negro", "Trecho brasileiro do Amazonas a oeste de Manaus.", "trivia", 2, 4, ["rio", "norte"], ["ibge-mapa"]],

    ["Fernando de Noronha", "Arquipélago pernambucano de águas protegidas", "Arquipélago oceânico administrado por Pernambuco.", "association", 1, 5, ["paisagem", "nordeste"], ["iphan-mundial"]],
    ["Lençóis Maranhenses", "Dunas e lagoas que parecem tecido ao vento?", "Parque nacional de campos de dunas no Maranhão.", "wordplay", 2, 5, ["paisagem", "nordeste"], ["icmbio-parques", "iphan-mundial"]],
    ["Chapada Diamantina", "Serras, vales e cachoeiras no centro baiano", "Região de planaltos no interior da Bahia.", "association", 2, 5, ["paisagem", "nordeste"], ["icmbio-parques"]],
    ["Serra da Capivara", "Paredões piauienses guardam pinturas rupestres", "Parque nacional e patrimônio mundial no Piauí.", "trivia", 2, 5, ["paisagem", "nordeste", "patrimônio"], ["iphan-mundial", "icmbio-parques"]],
    ["Recôncavo", "Baía de Todos-os-Santos por dentro", "Região histórica que circunda a Baía de Todos-os-Santos.", "association", 3, 4, ["território-cultural", "nordeste"], ["iphan-inventarios"]],

    ["Veadeiros", "Chapada goiana de cânions e cachoeiras", "Nome abreviado da chapada e do parque nacional em Goiás.", "elliptical", 2, 4, ["paisagem", "centro-oeste"], ["icmbio-parques", "iphan-mundial"]],
    ["Nhecolândia", "Sub-região sul-mato-grossense pontilhada de baías e salinas", "Sub-região da planície alagável em Mato Grosso do Sul.", "trivia", 4, 2, ["paisagem", "centro-oeste"], ["embrapa-nhecolandia"]],
    ["Bonito", "Município sul-mato-grossense de rios transparentes", "Destino de ecoturismo no sudoeste de Mato Grosso do Sul.", "association", 1, 5, ["paisagem", "centro-oeste"], ["ibge-cidades"]],
    ["Bodoquena", "Serra calcária próxima de Bonito", "Serra e parque nacional em Mato Grosso do Sul.", "association", 3, 3, ["paisagem", "centro-oeste"], ["icmbio-parques"]],
    ["Araguaia", "Rio que encontra o Tocantins e banha a Ilha do Bananal", "Rio que percorre o Centro-Oeste e desemboca no Tocantins.", "trivia", 2, 4, ["rio", "centro-oeste"], ["ibge-mapa"]],

    ["Canastra", "Serra mineira associada à nascente do São Francisco", "Serra e parque nacional no oeste de Minas Gerais.", "association", 2, 5, ["paisagem", "sudeste"], ["icmbio-parques"]],
    ["Caparaó", "Serra do Pico da Bandeira", "Serra e parque nacional entre Minas Gerais e Espírito Santo.", "association", 2, 4, ["paisagem", "sudeste"], ["icmbio-parques"]],
    ["Pampulha", "Conjunto moderno à beira de uma lagoa belo-horizontina", "Conjunto arquitetônico e paisagístico de Belo Horizonte.", "association", 2, 5, ["patrimônio", "sudeste"], ["iphan-mundial"]],
    ["Ouro Preto", "Casario barroco sobe e desce ladeiras mineiras", "Cidade histórica mineira reconhecida como patrimônio mundial.", "association", 1, 5, ["patrimônio", "sudeste"], ["iphan-mundial"]],
    ["Paraty", "Centro histórico entre serra e mar fluminenses", "Cidade histórica no litoral sul do Rio de Janeiro.", "association", 1, 5, ["patrimônio", "sudeste"], ["iphan-mundial"]],

    ["Iguaçu", "Cataratas na fronteira entre Paraná e Argentina", "Rio e parque nacional no oeste do Paraná.", "association", 1, 5, ["paisagem", "sul"], ["icmbio-parques", "iphan-mundial"]],
    ["Aparados da Serra", "Cânions marcam a divisa de Santa Catarina e Rio Grande do Sul", "Parque nacional de cânions na Região Sul.", "association", 3, 4, ["paisagem", "sul"], ["icmbio-parques"]],
    ["Serra do Mar", "Escarpa acompanha o litoral meridional e sudeste", "Sistema de serras próximo da costa brasileira.", "association", 2, 5, ["paisagem", "sul"], ["ibge-mapa"]],
    ["Ilha do Mel", "Faixa paranaense sem carros, diante da baía", "Ilha turística na entrada da Baía de Paranaguá.", "association", 2, 4, ["paisagem", "sul"], ["ibge-mapa"]],
    ["Lagoa dos Patos", "Grande laguna separada do Atlântico por restinga", "Laguna costeira no Rio Grande do Sul.", "trivia", 2, 4, ["paisagem", "sul"], ["ibge-mapa"]],

    // Culinárias regionais — 35 (sete por Grande Região)
    ["tacacá", "Cuia fumegante com tucupi, goma e jambu", "Caldo amazônico servido em cuia, com tucupi e jambu.", "association", 1, 5, ["culinária", "norte"], ["santarem-culinaria", "iphan-para"]],
    ["maniçoba", "Folhas de mandioca cozinham por muitos dias", "Prato paraense preparado com maniva cozida.", "trivia", 2, 4, ["culinária", "norte"], ["santarem-culinaria"]],
    ["pato no tucupi", "Ave mergulhada em caldo amarelo amazônico", "Prato paraense que combina ave, tucupi e jambu.", "association", 2, 5, ["culinária", "norte"], ["santarem-culinaria"]],
    ["beiju", "Disco de massa de mandioca sobre a chapa", "Preparação indígena feita de massa ou fécula de mandioca.", "association", 1, 5, ["culinária", "norte", "influência-indígena"], ["saude-alimentos"]],
    ["farinha d'água", "Mandioca fermentada vira acompanhamento amazônico", "Farinha de mandioca fermentada e torrada, comum na Amazônia.", "trivia", 3, 3, ["culinária", "norte"], ["fundaj-amazonica"]],
    ["damurida", "Caldo apimentado de tradição indígena roraimense", "Preparação de peixe e pimentas difundida em Roraima.", "association", 3, 3, ["culinária", "norte", "influência-indígena"], ["boa-vista-damurida"]],
    ["piracuí", "Farinha de peixe que tempera a mesa amazônica", "Farinha produzida com peixe seco e triturado.", "association", 3, 3, ["culinária", "norte"], ["fundaj-amazonica", "santarem-culinaria"]],

    ["acarajé", "Bolinho de feijão-fradinho, dendê e ofício de baiana", "Bolinho frito em azeite de dendê, ligado às baianas.", "association", 1, 5, ["culinária", "nordeste", "influência-afro-brasileira"], ["ipac-acaraje", "iphan-imaterial"]],
    ["abará", "Massa de feijão-fradinho cozinha embrulhada em folha", "Bolinho cozido de feijão-fradinho, dendê e temperos.", "association", 2, 4, ["culinária", "nordeste", "influência-afro-brasileira"], ["ipac-acaraje"]],
    ["vatapá", "Creme baiano de dendê que acompanha o tabuleiro", "Preparação cremosa com dendê, servida na culinária baiana.", "association", 1, 5, ["culinária", "nordeste", "influência-afro-brasileira"], ["ipac-acaraje"]],
    ["caruru", "Quiabo e dendê dividem a panela baiana", "Prato baiano à base de quiabo e azeite de dendê.", "association", 2, 5, ["culinária", "nordeste", "influência-afro-brasileira"], ["ipac-acaraje"]],
    ["cuscuz", "Flocos de milho ganham forma no vapor", "Preparação de milho flocado cozida no vapor.", "association", 1, 5, ["culinária", "nordeste"], ["saude-alimentos"]],
    ["baião de dois", "Arroz e feijão dançam juntos na panela?", "Prato nordestino que combina arroz e feijão.", "wordplay", 1, 5, ["culinária", "nordeste"], ["embrapa-caupi"]],
    ["cajuína", "Bebida piauiense clara, doce e sem álcool", "Bebida filtrada e cozida feita do suco de caju.", "association", 2, 4, ["culinária", "nordeste", "patrimônio"], ["iphan-piaui"]],

    ["arroz com pequi", "Grão perfumado pelo fruto amarelo do Centro-Oeste", "Prato que cozinha arroz com polpa de pequi.", "association", 1, 5, ["culinária", "centro-oeste"], ["saude-alimentos"]],
    ["empadão goiano", "Torta robusta recheada no coração de Goiás", "Torta salgada tradicional da culinária goiana.", "association", 2, 4, ["culinária", "centro-oeste"], ["saude-alimentos"]],
    ["sopa paraguaia", "Tem nome de caldo, mas chega à mesa em pedaços?", "Bolo salgado de milho, queijo e cebola, comum em Mato Grosso do Sul.", "wordplay", 2, 4, ["culinária", "centro-oeste", "fronteira"], ["saude-alimentos"]],
    ["chipa", "Rosquinha de polvilho e queijo atravessa a fronteira", "Biscoito assado de polvilho e queijo, comum em Mato Grosso do Sul.", "association", 2, 4, ["culinária", "centro-oeste", "fronteira"], ["saude-alimentos"]],
    ["mojica", "Peixe ensopado engrossa com mandioca em Mato Grosso", "Ensopado mato-grossense de peixe e mandioca.", "association", 3, 3, ["culinária", "centro-oeste"], ["saude-alimentos"]],
    ["furrundu", "Doce cuiabano junta mamão verde e rapadura", "Doce de mamão verde e rapadura da culinária mato-grossense.", "association", 3, 3, ["culinária", "centro-oeste"], ["saude-alimentos"]],
    ["galinhada", "Arroz e ave dividem uma só panela", "Prato de arroz cozido com pedaços de galinha.", "association", 1, 5, ["culinária", "centro-oeste"], ["saude-alimentos"]],

    ["feijoada", "Panela escura reúne feijão e carnes", "Prato de feijão-preto cozido com carnes.", "association", 1, 5, ["culinária", "sudeste"], ["saude-alimentos"]],
    ["pão de queijo", "Quitute mineiro, redondo e de polvilho", "Pãozinho de polvilho e queijo associado a Minas Gerais.", "association", 1, 5, ["culinária", "sudeste"], ["saude-alimentos"]],
    ["queijo minas", "Fresco ou curado, leva o estado no nome?", "Queijo tradicional produzido em Minas Gerais.", "wordplay", 1, 5, ["culinária", "sudeste", "patrimônio"], ["iphan-queijo"]],
    ["tutu", "Feijão engrossado com farinha na cozinha mineira", "Pasta de feijão cozido engrossada com farinha.", "association", 1, 5, ["culinária", "sudeste"], ["saude-alimentos"]],
    ["angu", "Mingau firme de fubá acompanha o prato", "Preparação cozida de fubá e água.", "association", 1, 5, ["culinária", "sudeste"], ["saude-alimentos"]],
    ["virado à paulista", "Feijão e farinha dão nome ao prato de São Paulo", "Prato paulista com feijão engrossado por farinha e acompanhamentos.", "association", 2, 4, ["culinária", "sudeste"], ["saude-alimentos"]],
    ["moqueca capixaba", "Panela de barro, peixe e urucum — sem dendê", "Ensopado de peixe típico do Espírito Santo.", "trivia", 1, 5, ["culinária", "sudeste"], ["es-culinaria"]],

    ["churrasco", "Carne encontra brasa na tradição gaúcha", "Carne assada sobre brasas ou fogo.", "association", 1, 5, ["culinária", "sul"], ["saude-alimentos"]],
    ["chimarrão", "Cuia, bomba e erva passam de mão em mão", "Infusão de erva-mate bebida em cuia com bomba.", "association", 1, 5, ["culinária", "sul"], ["saude-alimentos"]],
    ["barreado", "Panela vedada cozinha lentamente no litoral paranaense", "Prato paranaense de carne cozida por muitas horas.", "association", 2, 4, ["culinária", "sul"], ["parana-barreado"]],
    ["arroz carreteiro", "Grão de estrada leva charque na bagagem?", "Prato de arroz com charque ligado à tradição dos carreteiros.", "wordplay", 2, 5, ["culinária", "sul"], ["saude-alimentos"]],
    ["cuca", "Farofa doce cobre o bolo do Sul", "Bolo de influência germânica coberto por farofa doce.", "association", 2, 4, ["culinária", "sul", "imigração"], ["saude-alimentos"]],
    ["entrevero", "Carnes e legumes se misturam no disco", "Prato sulista que mistura carnes e vegetais na chapa.", "association", 3, 3, ["culinária", "sul"], ["saude-alimentos"]],
    ["sagu", "Pérolas de mandioca encontram vinho tinto", "Sobremesa sulista de bolinhas de fécula, muitas vezes cozidas em vinho.", "association", 2, 4, ["culinária", "sul"], ["saude-alimentos"]],

    // Música e dança — 35
    ["samba", "Síncope brasileira que cabe na roda e na avenida", "Gênero musical e dança de raízes afro-brasileiras.", "association", 1, 5, ["música", "dança", "influência-afro-brasileira"], ["iphan-rio", "dicionario-mpb"]],
    ["choro", "Virtuosismo instrumental que não precisa de lágrimas?", "Gênero instrumental brasileiro surgido no século XIX.", "wordplay", 1, 5, ["música", "sudeste"], ["funarte-choro"]],
    ["bossa nova", "Batida contida, apartamento e mar carioca", "Movimento musical brasileiro associado ao fim dos anos 1950.", "association", 1, 5, ["música", "sudeste"], ["dicionario-mpb"]],
    ["baião", "A sanfona nordestina acentua dois tempos", "Gênero musical e dança difundido por Luiz Gonzaga.", "association", 1, 5, ["música", "nordeste"], ["funarte-forro", "dicionario-mpb"]],
    ["forró", "Sanfona, zabumba e triângulo chamam ao salão", "Gênero e festa dançante ligados ao Nordeste.", "association", 1, 5, ["música", "dança", "nordeste"], ["funarte-forro"]],
    ["xote", "Passos a dois no salão nordestino", "Ritmo e dança presentes no repertório do forró.", "association", 2, 5, ["música", "dança", "nordeste"], ["funarte-forro"]],
    ["frevo", "Som acelerado põe sombrinhas no ar", "Música e dança carnavalesca de Pernambuco.", "association", 1, 5, ["música", "dança", "nordeste", "patrimônio"], ["iphan-pernambuco"]],
    ["maracatu", "Cortejo percussivo coroa sua realeza", "Manifestação pernambucana de música, dança e cortejo.", "association", 1, 5, ["música", "dança", "nordeste", "influência-afro-brasileira"], ["iphan-pernambuco"]],
    ["coco de roda", "Palmas, canto responsorial e passos em círculo", "Dança e música popular nordestina realizada em roda.", "association", 2, 4, ["música", "dança", "nordeste"], ["iphan-inventarios"]],
    ["ciranda", "Roda pernambucana cresce de mãos dadas", "Dança coletiva em roda, de forte presença em Pernambuco.", "association", 1, 5, ["música", "dança", "nordeste"], ["iphan-pernambuco"]],
    ["toada", "Voz melódica conduz a arena de Parintins", "Canção que acompanha apresentações do boi-bumbá amazônico.", "association", 2, 4, ["música", "norte"], ["cultura-am-toada"]],
    ["lundu", "Dança afro-brasileira que também virou canção", "Dança e gênero musical de matriz africana difundidos no Brasil.", "trivia", 3, 3, ["música", "dança", "influência-afro-brasileira"], ["dicionario-mpb"]],
    ["maxixe", "Salão urbano gingou antes do samba", "Dança de par e gênero musical urbano brasileiro.", "trivia", 2, 4, ["música", "dança"], ["dicionario-mpb"]],
    ["modinha", "Canção sentimental atravessou salões e serestas", "Gênero de canção lírica popular no Brasil desde o período colonial.", "association", 3, 3, ["música", "canção"], ["dicionario-mpb"]],
    ["afoxé", "Cortejo baiano leva o ijexá às ruas", "Agremiação carnavalesca afro-brasileira, especialmente baiana.", "association", 2, 4, ["música", "carnaval", "influência-afro-brasileira"], ["iphan-inventarios"]],
    ["ijexá", "Toque dos terreiros também pulsa nos afoxés", "Ritmo de matriz africana presente em cultos e cortejos baianos.", "association", 3, 3, ["música", "influência-afro-brasileira"], ["dicionario-mpb"]],
    ["jongo", "Tambores e pontos cantados formam a roda", "Manifestação afro-brasileira de canto, dança e percussão.", "association", 2, 4, ["música", "dança", "sudeste", "influência-afro-brasileira"], ["iphan-rio"]],
    ["samba de bumbo", "Grande tambor marca a roda paulista", "Modalidade tradicional paulista marcada por grande tambor.", "association", 3, 3, ["música", "dança", "sudeste"], ["iphan-inventarios"]],
    ["catira", "Palmas e sapateado riscam o chão do interior", "Dança em fileiras, com palmas e batidas dos pés.", "association", 2, 4, ["dança", "centro-oeste", "sudeste"], ["iphan-inventarios"]],
    ["samba-rock", "Balanço paulista mistura gingado e guitarra", "Gênero dançante brasileiro que combina samba, soul e rock.", "association", 2, 4, ["música", "dança", "sudeste"], ["dicionario-mpb"]],
    ["siriri", "Dança mato-grossense de pares e roda", "Dança popular tradicional de Mato Grosso.", "association", 3, 3, ["música", "dança", "centro-oeste"], ["iphan-mato-grosso"]],
    ["chamamé", "Acordeão de fronteira embala pares no Sul e Centro-Oeste", "Gênero musical e dança difundido na fronteira sul-americana.", "association", 3, 3, ["música", "dança", "centro-oeste", "fronteira"], ["dicionario-mpb"]],
    ["rasqueado", "Cordas sincopadas animam bailes mato-grossenses", "Gênero musical associado a Mato Grosso.", "association", 3, 3, ["música", "centro-oeste"], ["dicionario-mpb"]],
    ["vanerão", "Baile gaúcho acelera a vaneira", "Ritmo e dança de salão presentes na música gaúcha.", "trivia", 3, 3, ["música", "dança", "sul"], ["dicionario-mpb"]],
    ["milonga", "Canção e dança dos pampas atravessam fronteiras", "Gênero musical de circulação no Rio Grande do Sul, Uruguai e Argentina.", "association", 2, 4, ["música", "dança", "sul", "fronteira"], ["dicionario-mpb"]],
    ["fandango caiçara", "Baile costeiro une rabeca, tamancos e mutirão", "Expressão de música e dança das comunidades caiçaras do Sul e Sudeste.", "association", 3, 3, ["música", "dança", "sul", "patrimônio"], ["iphan-parana"]],
    ["marabaixo", "Caixas e ladrões animam o ciclo do Divino no Amapá", "Manifestação amapaense de dança, música e religiosidade.", "trivia", 3, 3, ["música", "dança", "norte", "influência-afro-brasileira"], ["iphan-marabaixo"]],
    ["guitarrada", "Cordas elétricas puxam o baile paraense", "Gênero instrumental popular surgido no Pará.", "association", 2, 4, ["música", "norte"], ["dicionario-mpb"]],
    ["lambada", "Dança paraense de pares ganhou o mundo", "Gênero musical e dança popularizados a partir do Norte.", "association", 1, 5, ["música", "dança", "norte"], ["dicionario-mpb"]],
    ["embolada", "Dupla improvisa versos sobre batida de pandeiro", "Canto poético improvisado, comum no Nordeste.", "association", 2, 4, ["música", "oralidade", "nordeste"], ["dicionario-mpb"]],
    ["repente", "Dois cantadores duelam em versos improvisados", "Arte poética oral improvisada por cantadores.", "association", 1, 5, ["música", "oralidade", "nordeste", "patrimônio"], ["iphan-repente"]],
    ["samba de roda", "Canto, palmas e dança circulam no Recôncavo", "Expressão musical e coreográfica tradicional do Recôncavo Baiano.", "association", 2, 5, ["música", "dança", "nordeste", "patrimônio"], ["iphan-imaterial"]],
    ["samba-enredo", "A avenida canta a história escolhida pela escola", "Modalidade criada para o desfile de escola carnavalesca.", "association", 1, 5, ["música", "carnaval", "sudeste"], ["iphan-rio"]],
    ["partido-alto", "Versos improvisados respondem ao refrão na roda", "Modalidade de samba com improviso e canto responsorial.", "association", 2, 4, ["música", "sudeste"], ["iphan-rio"]],
    ["tambor de crioula", "Coreiras giram ao som de três tambores maranhenses", "Dança afro-brasileira do Maranhão acompanhada por tambores.", "association", 2, 4, ["música", "dança", "nordeste", "influência-afro-brasileira"], ["iphan-imaterial"]],

    // Festas, cortejos e artes populares — 30
    ["carnaval", "Avenida, rua e salão esperam a quarta-feira", "Festa popular que antecede a Quaresma.", "association", 1, 5, ["festa", "nacional"], ["iphan-inventarios"]],
    ["festa junina", "Bandeirinhas, fogueira e dança no meio do ano", "Conjunto de celebrações populares realizadas em junho.", "association", 1, 5, ["festa", "nacional"], ["iphan-inventarios"]],
    ["São João", "Fogueira acesa na noite de 23 para 24 de junho", "Celebração popular dedicada ao santo festejado em 24 de junho.", "trivia", 1, 5, ["festa", "nordeste"], ["iphan-inventarios"]],
    ["Círio de Nazaré", "Multidão e corda acompanham a procissão em Belém", "Grande celebração católica paraense dedicada a Nossa Senhora de Nazaré.", "association", 1, 5, ["festa", "norte", "patrimônio"], ["iphan-para"]],
    ["lavagem do Bonfim", "Água de cheiro sobe a Colina Sagrada", "Festa baiana em que se lavam as escadarias de uma igreja de Salvador.", "association", 2, 5, ["festa", "nordeste", "religiosidade"], ["iphan-inventarios"]],
    ["boi-bumbá", "Garantido e Caprichoso disputam em Parintins", "Manifestação do boi festivo associada ao Amazonas.", "trivia", 1, 5, ["festa", "norte"], ["iphan-inventarios"]],
    ["bumba meu boi", "Sotaques e matracas animam o Maranhão", "Complexo cultural maranhense centrado na brincadeira do boi.", "association", 1, 5, ["festa", "nordeste", "patrimônio"], ["iphan-imaterial"]],
    ["boi de mamão", "Bonecos e cantoria conduzem o auto catarinense", "Brincadeira popular do litoral de Santa Catarina com figuras de boi.", "association", 3, 3, ["festa", "sul"], ["iphan-inventarios"]],
    ["caboclinho", "Cocar, preacas e dança cruzam o carnaval pernambucano", "Brincadeira carnavalesca pernambucana com música e coreografia próprias.", "association", 3, 3, ["festa", "nordeste", "influência-indígena"], ["iphan-pernambuco"]],
    ["reisado", "Cortejo visita casas no ciclo natalino", "Folia popular ligada à visita dos Reis Magos.", "association", 2, 4, ["festa", "nordeste"], ["iphan-inventarios"]],
    ["pastoril", "Cordões azul e encarnado cantam diante do presépio", "Auto popular natalino organizado em cordões de participantes.", "trivia", 3, 3, ["festa", "nordeste"], ["iphan-inventarios"]],
    ["folia de reis", "Bandeira e cantoria percorrem casas até janeiro", "Cortejo popular que celebra a visita dos Reis Magos.", "association", 2, 4, ["festa", "sudeste"], ["iphan-inventarios"]],
    ["festa do divino", "Coroa e pomba vermelha percorrem comunidades", "Celebração católica popular dedicada ao Espírito Santo.", "association", 2, 4, ["festa", "nacional"], ["iphan-rio"]],
    ["cavalhada", "Cavaleiros encenam combates em roupa de festa", "Folguedo equestre que dramatiza batalhas medievais.", "association", 2, 4, ["festa", "centro-oeste"], ["iphan-inventarios"]],
    ["romaria", "Fé põe peregrinos na estrada", "Peregrinação coletiva a um lugar de devoção.", "association", 1, 5, ["festa", "religiosidade"], ["iphan-inventarios"]],
    ["quadrilha", "Casamento caipira organiza pares no arraial", "Dança coletiva em pares típica das festas de junho.", "association", 1, 5, ["dança", "festa"], ["iphan-inventarios"]],
    ["escola de samba", "Agremiação prepara enredo, bateria e desfile", "Agremiação carnavalesca que desfila com alas e enredo.", "association", 1, 5, ["carnaval", "sudeste"], ["iphan-rio"]],
    ["bloco", "Cortejo toma a rua atrás de música e estandarte", "Grupo carnavalesco que desfila pelas ruas.", "association", 1, 5, ["carnaval", "nacional"], ["iphan-inventarios"]],
    ["trio elétrico", "Palco sobre rodas arrasta multidões em Salvador?", "Caminhão equipado com som e palco para apresentações carnavalescas.", "wordplay", 1, 5, ["carnaval", "nordeste"], ["iphan-inventarios"]],
    ["passista", "Samba no pé abre espaço na avenida", "Dançarino ou dançarina de destaque em desfile carnavalesco.", "association", 1, 5, ["carnaval", "dança"], ["iphan-rio"]],
    ["mestre-sala", "Ele corteja o pavilhão sem lhe dar as costas", "Integrante que dança em par com a porta-bandeira.", "trivia", 2, 5, ["carnaval", "dança"], ["iphan-rio"]],
    ["porta-bandeira", "Ela apresenta o pavilhão em giros cerimoniais", "Integrante que conduz a bandeira da escola carnavalesca.", "association", 2, 5, ["carnaval", "dança"], ["iphan-rio"]],
    ["cordel", "Versos pendurados chegaram à capa do folheto?", "Literatura popular publicada em folhetos, frequentemente rimada.", "wordplay", 1, 5, ["literatura", "nordeste", "patrimônio"], ["iphan-imaterial"]],
    ["xilogravura", "Matriz de madeira imprime traços sobre papel", "Técnica de gravura feita com matriz entalhada em madeira.", "association", 2, 4, ["arte", "cultura-material"], ["iphan-inventarios"]],
    ["mamulengo", "Boneco de luva improvisa no teatro popular", "Teatro popular de bonecos tradicional do Nordeste.", "association", 2, 4, ["teatro", "nordeste", "patrimônio"], ["iphan-imaterial"]],
    ["carranca", "Rosto de madeira encara a proa sanfranciscana", "Escultura figurativa colocada na proa de embarcações do São Francisco.", "association", 2, 4, ["arte", "cultura-material"], ["iphan-material"]],
    ["ex-voto", "Objeto agradece uma graça alcançada", "Oferenda deixada em cumprimento de promessa ou agradecimento.", "association", 3, 4, ["arte", "religiosidade", "cultura-material"], ["iphan-material"]],
    ["ritxoko", "Boneca de cerâmica transmite saberes Karajá", "Boneca de cerâmica produzida por mulheres do povo Karajá.", "association", 4, 2, ["arte", "centro-oeste", "povos-indígenas"], ["iphan-karaja"]],
    ["kusiwa", "Grafismos Wajãpi organizam seres e mundos", "Sistema de pintura corporal e arte gráfica do povo Wajãpi.", "association", 4, 2, ["arte", "norte", "povos-indígenas"], ["iphan-imaterial"]],
    ["paneleira", "Em Goiabeiras, ela modela barro sem torno", "Artesã que produz as tradicionais panelas de barro de Goiabeiras.", "association", 3, 3, ["ofício", "sudeste", "cultura-material"], ["iphan-imaterial", "es-culinaria"]],

    // Comunidades e ofícios tradicionais — 11
    ["indígena", "Pertence a um dos muitos povos originários do país", "Pessoa pertencente a um povo originário do território brasileiro.", "association", 1, 5, ["povos-indígenas", "diversidade"], ["funai-institucional"]],
    ["quilombola", "Comunidade e identidade ligadas a quilombos", "Pessoa pertencente a uma comunidade remanescente de quilombo.", "association", 2, 5, ["comunidade-tradicional", "influência-afro-brasileira"], ["palmares"]],
    ["ribeirinho", "A vida comunitária acompanha o curso das águas", "Morador de comunidade tradicional situada junto a rios.", "association", 2, 5, ["comunidade-tradicional", "norte"], ["mma-pct"]],
    ["caiçara", "Mar, roça e pesca compõem a cultura costeira", "Integrante de comunidade tradicional do litoral Sul e Sudeste.", "association", 2, 4, ["comunidade-tradicional", "litoral"], ["mma-pct"]],
    ["pantaneiro", "Cheias e vazantes marcam seu modo de vida", "Pessoa ligada às comunidades e atividades tradicionais da planície alagável de MT e MS.", "association", 2, 4, ["comunidade-tradicional", "centro-oeste"], ["mma-pct"]],
    ["caipira", "Violeiro, roça e interior — identidade, não caricatura", "Identidade cultural ligada a comunidades rurais do interior do Sudeste e Centro-Oeste.", "association", 2, 5, ["identidade-cultural", "interior"], ["iphan-inventarios"]],
    ["vaqueiro", "Conduz o gado e preserva saberes do sertão", "Trabalhador tradicional que cuida e conduz rebanhos bovinos.", "association", 1, 5, ["ofício", "nordeste"], ["mma-pct"]],
    ["jangadeiro", "Vela e remo levam o pescador pelo litoral", "Trabalhador que navega ou pesca em jangada.", "association", 2, 4, ["ofício", "nordeste", "litoral"], ["mma-pct"]],
    ["seringueiro", "A estrada na mata leva ao látex", "Trabalhador que extrai látex de seringueiras.", "association", 2, 4, ["ofício", "norte"], ["mma-pct"]],
    ["marisqueira", "Ela coleta sustento onde a maré recua", "Mulher que coleta mariscos em áreas costeiras e estuarinas.", "association", 2, 4, ["ofício", "litoral"], ["mma-pct"]],
    ["quebradeira de coco", "Mulheres transformam babaçu em renda e resistência", "Trabalhadora tradicional que coleta e quebra coco-babaçu.", "association", 3, 3, ["ofício", "comunidade-tradicional", "nordeste", "norte"], ["ibge-quebradeiras", "mma-pct"]],

    // Instrumentos e cultura material — 13
    ["berimbau", "Uma corda, uma cabaça e o toque da roda", "Instrumento de arco musical central na capoeira.", "association", 1, 5, ["instrumento", "influência-afro-brasileira"], ["iphan-capoeira"]],
    ["cuíca", "Fricção por dentro faz o tambor roncar", "Tambor de fricção muito usado no samba.", "association", 2, 5, ["instrumento", "música"], ["dicionario-mpb"]],
    ["pandeiro", "Platinelas cercam a pele redonda", "Instrumento de percussão com pele e platinelas.", "association", 1, 5, ["instrumento", "música"], ["dicionario-mpb"]],
    ["atabaque", "Tambor alto sustenta roda e terreiro", "Tambor de mão presente em tradições afro-brasileiras.", "association", 2, 5, ["instrumento", "influência-afro-brasileira"], ["iphan-capoeira"]],
    ["agogô", "Duas campanas de metal conversam com baqueta", "Instrumento de percussão formado por campanas metálicas.", "association", 2, 4, ["instrumento", "influência-afro-brasileira"], ["dicionario-mpb"]],
    ["caxixi", "Cesto pequeno chacoalha ao lado do arco musical", "Chocalho de palha trançada com sementes ou contas.", "association", 3, 3, ["instrumento", "cultura-material"], ["iphan-capoeira"]],
    ["alfaia", "Tambor grave puxa o baque do maracatu", "Grande tambor de madeira usado no maracatu-nação.", "association", 3, 3, ["instrumento", "nordeste"], ["iphan-pernambuco"]],
    ["zabumba", "Grave de duas peles sustenta o forró", "Tambor de duas peles tocado com baquetas.", "association", 1, 5, ["instrumento", "nordeste"], ["funarte-forro"]],
    ["sanfona", "Fole abre caminho ao baião", "Nome popular do acordeão em boa parte do Brasil.", "association", 1, 5, ["instrumento", "nordeste"], ["funarte-forro"]],
    ["rabeca", "Arco fricciona cordas em bailes e folguedos", "Instrumento popular de cordas tocado com arco.", "association", 2, 4, ["instrumento", "música"], ["iphan-parana"]],
    ["viola de cocho", "Cordas vibram num corpo escavado em madeira", "Instrumento mato-grossense feito em peça de madeira escavada.", "association", 2, 4, ["instrumento", "centro-oeste", "patrimônio"], ["iphan-mato-grosso"]],
    ["cuia", "Recipiente vegetal recebe caldo ou erva", "Vasilha feita do fruto seco da cuieira ou porongo.", "association", 1, 5, ["cultura-material", "culinária"], ["iphan-para"]],
    ["panela de barro", "Argila capixaba cozinha a moqueca", "Utensílio cerâmico tradicional produzido em Goiabeiras.", "association", 1, 5, ["cultura-material", "sudeste", "patrimônio"], ["iphan-imaterial", "es-culinaria"]],

    // Jogos e práticas corporais — 6
    ["capoeira", "Jogo, luta e dança giram ao som do arco", "Prática afro-brasileira que reúne luta, jogo, música e dança.", "association", 1, 5, ["jogo", "influência-afro-brasileira", "patrimônio"], ["iphan-capoeira"]],
    ["peteca", "A mão rebate o objeto de penas sobre a rede", "Jogo em que se golpeia com a mão um objeto com penas.", "association", 1, 5, ["jogo", "influência-indígena"], ["goiania-peteca"]],
    ["frescobol", "Duas raquetes cooperam na areia carioca", "Jogo de praia com raquetes, sem adversários separados por rede.", "association", 1, 5, ["esporte", "sudeste", "litoral"], ["rio-frescobol"]],
    ["futevôlei", "Pés e cabeça passam a bola sobre a rede de areia?", "Esporte de areia que combina fundamentos do futebol e do vôlei.", "wordplay", 2, 5, ["esporte", "litoral"], ["mesp-futevolei"]],
    ["biribol", "Vôlei brasileiro mergulha na piscina?", "Jogo semelhante ao voleibol, disputado em piscina rasa.", "wordplay", 3, 3, ["esporte", "sudeste"], ["ibge-esportes"]],
    ["futsal", "Cinco de cada lado e bola nos pés da quadra", "Modalidade de futebol jogada em quadra por equipes de cinco.", "association", 1, 5, ["esporte", "nacional"], ["mesp-futsal"]],

    // Instituições e símbolos — 10
    ["SUS", "Da vacina à cirurgia, universal no princípio", "Sistema público nacional de saúde do Brasil.", "association", 1, 5, ["instituição", "saúde"], ["saude-sus"]],
    ["IBGE", "Censos, mapas e estatísticas oficiais saem daqui", "Instituto Brasileiro de Geografia e Estatística.", "association", 1, 5, ["instituição", "geografia"], ["ibge-territorio"]],
    ["IPHAN", "Tomba edifícios e registra modos de fazer", "Instituto do Patrimônio Histórico e Artístico Nacional.", "association", 2, 5, ["instituição", "patrimônio"], ["iphan-institucional"]],
    ["Funai", "Órgão indigenista oficial da União", "Fundação Nacional dos Povos Indígenas.", "elliptical", 2, 5, ["instituição", "povos-indígenas"], ["funai-institucional"]],
    ["bandeira", "Verde, losango amarelo e céu estrelado", "Símbolo nacional retangular com as cores verde, amarela, azul e branca.", "association", 1, 5, ["símbolo", "nacional"], ["planalto-bandeira", "planalto-simbolos"]],
    ["hino", "“Ouviram do Ipiranga” dá a entrada", "Símbolo nacional composto por música e poema oficiais.", "association", 1, 5, ["símbolo", "nacional"], ["planalto-simbolos"]],
    ["Ordem e Progresso", "Positivismo atravessa a faixa branca", "Lema inscrito na faixa central da bandeira brasileira.", "association", 1, 5, ["símbolo", "nacional"], ["planalto-bandeira"]],
    ["Cruzeiro do Sul", "Cinco estrelas formam cruz no céu da bandeira", "Constelação representada entre as estrelas da bandeira brasileira.", "association", 1, 5, ["símbolo", "nacional"], ["planalto-bandeira"]],
    ["pau-brasil", "Árvore que emprestou nome ao país", "Árvore nativa que deu origem ao nome do Brasil.", "association", 1, 5, ["símbolo", "flora", "nacional"], ["camara-pau-brasil"]],
    ["real", "R$ antes do preço", "Moeda oficial do Brasil desde 1994.", "association", 1, 5, ["instituição", "moeda"], ["bcb-real"]],
  ],
} satisfies BiomeBundle;

export const brasilEntries = entriesFromBundle(brasilBundle);
