import { entriesFromBundle, type BiomeBundle } from "./shared.js";

const cienciaBundle = {
  biome: "ciencia",
  prefix: "cie",
  editorialSource: "curadoria-autoral-ciencia-v3",
  sources: [
    {
      sourceId: "openstax-bio",
      title: "OpenStax — Biology 2e",
      url: "https://openstax.org/books/biology-2e/pages/1-introduction",
      license: "CC BY-NC-SA 4.0; usado apenas como referência factual",
      role: "factual",
    },
    {
      sourceId: "nhgri-genetics",
      title: "NHGRI Talking Glossary of Genetic Terms",
      url: "https://www.genome.gov/genetics-glossary",
      license: "obra informativa de órgão do governo dos EUA",
      role: "factual",
    },
    {
      sourceId: "iupac-gold",
      title: "IUPAC Compendium of Chemical Terminology (Gold Book)",
      url: "https://goldbook.iupac.org/",
      license: "CC BY-SA 4.0 para termos individuais; usado como referência factual",
      role: "factual",
    },
    {
      sourceId: "openstax-physics",
      title: "OpenStax — College Physics 2e",
      url: "https://openstax.org/books/college-physics-2e/pages/1-introduction-to-science-and-the-realm-of-physics-physical-quantities-and-units",
      license: "CC BY-NC-SA 4.0; usado apenas como referência factual",
      role: "factual",
    },
    {
      sourceId: "nasa-universe",
      title: "NASA Science — Universe Glossary",
      url: "https://science.nasa.gov/universe/glossary/",
      license: "obra informativa da NASA; conteúdo autoral do projeto",
      role: "factual",
    },
    {
      sourceId: "openstax-earth",
      title: "OpenStax Astronomy 2e — Earth's Crust",
      url: "https://openstax.org/books/astronomy-2e/pages/8-2-earths-crust",
      license: "CC BY-NC-SA 4.0; usado apenas como referência factual",
      role: "factual",
    },
    {
      sourceId: "usgs-water",
      title: "USGS Water Science Glossary",
      url: "https://www.usgs.gov/water-science-school/science/water-science-glossary",
      license: "obra de órgão do governo dos EUA; conteúdo autoral do projeto",
      role: "factual",
    },
    {
      sourceId: "usgs-earthquake",
      title: "USGS Earthquake Hazards Program Glossary",
      url: "https://www.usgs.gov/glossary/earthquake-hazards-program",
      license: "obra de órgão do governo dos EUA; conteúdo autoral do projeto",
      role: "factual",
    },
    {
      sourceId: "usgs-volcano",
      title: "USGS Volcano Hazards Program Glossary",
      url: "https://www.usgs.gov/glossary/volcano-hazards-program-glossary",
      license: "obra de órgão do governo dos EUA; conteúdo autoral do projeto",
      role: "factual",
    },
    {
      sourceId: "noaa-weather",
      title: "NOAA National Weather Service Glossary",
      url: "https://forecast.weather.gov/glossary.php",
      license: "obra de órgão do governo dos EUA; conteúdo autoral do projeto",
      role: "factual",
    },
    {
      sourceId: "openstax-math",
      title: "OpenStax — Algebra and Trigonometry 2e",
      url: "https://openstax.org/books/algebra-and-trigonometry-2e/pages/1-introduction-to-prerequisites",
      license: "CC BY-NC-SA 4.0; usado apenas como referência factual",
      role: "factual",
    },
    {
      sourceId: "openstax-stats",
      title: "OpenStax — Introductory Statistics 2e",
      url: "https://openstax.org/books/introductory-statistics-2e/pages/1-introduction",
      license: "CC BY-NC-SA 4.0; usado apenas como referência factual",
      role: "factual",
    },
    {
      sourceId: "nist-glossary",
      title: "NIST Computer Security Resource Center Glossary",
      url: "https://csrc.nist.gov/glossary",
      license: "publicação do governo dos EUA; conteúdo autoral do projeto",
      role: "factual",
    },
    {
      sourceId: "nist-si",
      title: "NIST — International System of Units (SI)",
      url: "https://www.nist.gov/programs-projects/international-system-units-si",
      license: "publicação do governo dos EUA; conteúdo autoral do projeto",
      role: "factual",
    },
  ],
  records: [
    // Biologia celular, genética e corpo humano — 40
    ["alelo", "É uma das versões disponíveis no cardápio de um gene", "Forma alternativa de um mesmo gene.", "association", 3, 3, ["genetica"], ["nhgri-genetics"]],
    ["anticorpo", "Defesa sob medida para reconhecer um alvo", "Proteína do sistema imune que se liga a um alvo molecular específico.", "association", 2, 5, ["imunologia"], ["nhgri-genetics"]],
    ["antígeno", "Aciona o reconhecimento das defesas do corpo", "Molécula reconhecida como alvo pelo sistema imune.", "association", 3, 4, ["imunologia"], ["openstax-bio"]],
    ["axônio", "Cabo de saída de um neurônio", "Prolongamento que conduz sinais para longe do corpo do neurônio.", "association", 3, 3, ["neurobiologia"], ["openstax-bio"]],
    ["bactéria", "Vive em uma célula, mas sem núcleo cercado por membrana", "Microrganismo unicelular do grupo dos procariontes.", "association", 2, 5, ["microbiologia"], ["openstax-bio"]],
    ["célula", "O menor andar ainda considerado vivo?", "Unidade estrutural e funcional básica dos seres vivos.", "wordplay", 1, 5, ["biologia-celular"], ["openstax-bio"]],
    ["citoplasma", "O espaço de trabalho entre a membrana e o núcleo", "Região celular que abriga o citosol e várias estruturas internas.", "association", 2, 4, ["biologia-celular"], ["openstax-bio"]],
    ["clone", "Cópia biológica sem Ctrl+C?", "Célula ou organismo geneticamente idêntico ao original.", "wordplay", 2, 5, ["genetica"], ["openstax-bio"]],
    ["cromossomo", "Pacote em que uma longa molécula hereditária viaja organizada", "Estrutura de DNA e proteínas que carrega genes.", "association", 2, 5, ["genetica"], ["nhgri-genetics"]],
    ["DNA", "Arquivo químico passado entre gerações", "Molécula que armazena a informação genética dos seres vivos.", "association", 1, 5, ["genetica"], ["nhgri-genetics"]],
    ["embrião", "Começo multicelular de uma nova vida", "Organismo nas etapas iniciais do desenvolvimento antes do nascimento ou germinação.", "association", 2, 5, ["desenvolvimento"], ["openstax-bio"]],
    ["enzima", "Dá pressa à reação sem acabar no caminho?", "Catalisador biológico que acelera uma reação específica.", "wordplay", 2, 5, ["bioquimica"], ["openstax-bio"]],
    ["evolução", "Mudança que se conta em gerações, não em aniversários", "Alteração de características hereditárias de populações ao longo das gerações.", "association", 2, 5, ["evolucao"], ["openstax-bio"]],
    ["fígado", "Usina química que também produz a bile", "Órgão abdominal que metaboliza substâncias e produz bile.", "association", 1, 5, ["anatomia"], ["openstax-bio"]],
    ["gameta", "Leva metade do baralho cromossômico para a fecundação", "Célula reprodutiva com um conjunto de cromossomos.", "association", 2, 4, ["genetica"], ["openstax-bio"]],
    ["gene", "Trecho de herança escrito em quatro letras químicas", "Segmento de DNA com informação para um produto funcional.", "association", 2, 5, ["genetica"], ["nhgri-genetics"]],
    ["genoma", "A biblioteca genética inteira de um organismo", "Conjunto completo do material genético de um organismo.", "association", 2, 4, ["genetica"], ["nhgri-genetics"]],
    ["hemácia", "Disco vermelho que faz entrega de oxigênio", "Célula do sangue especializada no transporte de gases respiratórios.", "association", 2, 5, ["fisiologia"], ["openstax-bio"]],
    ["hormônio", "Recado químico enviado de um tecido a outro", "Mensageiro químico produzido pelo corpo para regular células e órgãos.", "association", 2, 5, ["fisiologia"], ["openstax-bio"]],
    ["membrana", "Fronteira celular que escolhe o que atravessa", "Camada seletiva que delimita a célula e controla trocas com o meio.", "association", 2, 5, ["biologia-celular"], ["openstax-bio"]],
    ["mitose", "Uma divisão que conserva o jogo de cromossomos", "Processo que reparte cromossomos duplicados entre dois novos núcleos.", "association", 3, 4, ["biologia-celular"], ["openstax-bio"]],
    ["músculo", "Encurta para pôr o corpo em movimento", "Tecido contrátil responsável por força e movimento corporal.", "association", 1, 5, ["anatomia"], ["openstax-bio"]],
    ["mutação", "Edição inesperada no texto genético", "Alteração na sequência do material genético.", "association", 2, 5, ["genetica"], ["nhgri-genetics"]],
    ["neurônio", "Célula que conversa por sinais elétricos e químicos", "Célula especializada em receber e transmitir sinais nervosos.", "association", 2, 5, ["neurobiologia"], ["openstax-bio"]],
    ["núcleo", "Cofre de cromossomos da célula eucariótica", "Compartimento celular envolto por membrana que contém a maior parte do DNA.", "association", 2, 5, ["biologia-celular"], ["openstax-bio"]],
    ["órgão", "Conjunto de tecidos com uma missão comum", "Estrutura corporal formada por tecidos que executam uma função.", "association", 1, 5, ["anatomia"], ["openstax-bio"]],
    ["osso", "Reserva de cálcio que também sustenta o corpo", "Estrutura rígida que compõe o esqueleto dos vertebrados.", "association", 1, 5, ["anatomia"], ["openstax-bio"]],
    ["pele", "A maior fronteira viva do corpo", "Órgão que reveste e protege a superfície corporal.", "association", 1, 5, ["anatomia"], ["openstax-bio"]],
    ["plaqueta", "Fragmento do sangue chamado para estancar vazamentos", "Componente sanguíneo que participa da coagulação.", "association", 2, 5, ["fisiologia"], ["openstax-bio"]],
    ["proteína", "Colar de aminoácidos dobrado para trabalhar", "Macromolécula formada por uma ou mais cadeias de aminoácidos.", "association", 2, 5, ["bioquimica"], ["openstax-bio"]],
    ["pulmão", "Enche e esvazia no ritmo da respiração", "Órgão em que ocorrem trocas gasosas com o ar.", "association", 1, 5, ["anatomia"], ["openstax-bio"]],
    ["retina", "Tela viva onde a luz vira sinal nervoso", "Camada sensível à luz situada no fundo do olho.", "association", 2, 5, ["neurobiologia"], ["openstax-bio"]],
    ["ribossomo", "Oficina celular que monta cadeias de aminoácidos", "Estrutura celular responsável pela síntese de proteínas.", "association", 2, 4, ["biologia-celular"], ["openstax-bio"]],
    ["rim", "Filtra o sangue e acerta a conta de água e sais", "Órgão que forma a urina e ajuda a regular o equilíbrio interno.", "association", 1, 5, ["anatomia"], ["openstax-bio"]],
    ["RNA", "Intermediário versátil entre genes e proteínas", "Ácido nucleico que atua na expressão e regulação da informação genética.", "association", 2, 5, ["genetica"], ["nhgri-genetics"]],
    ["sinapse", "Ponto em que um neurônio passa o recado", "Junção funcional pela qual uma célula nervosa sinaliza outra célula.", "association", 2, 4, ["neurobiologia"], ["openstax-bio"]],
    ["tecido", "Equipe de células parecidas em serviço conjunto", "Grupo organizado de células que desempenham funções relacionadas.", "association", 1, 5, ["anatomia"], ["openstax-bio"]],
    ["vacina", "Treino das defesas antes do confronto real", "Preparação que induz proteção imunológica contra um agente ou doença.", "association", 1, 5, ["imunologia"], ["openstax-bio"]],
    ["vírus", "Invasor acelular que usa a fábrica do hospedeiro", "Agente infeccioso que só se replica dentro de células hospedeiras.", "association", 2, 5, ["microbiologia"], ["openstax-bio"]],
    ["zigoto", "Primeira célula depois do encontro dos gametas", "Célula formada pela fecundação de dois gametas.", "association", 2, 4, ["desenvolvimento"], ["openstax-bio"]],

    // Química — 35
    ["ácido", "Faz o papel de tornassol pender para o vermelho", "Espécie química capaz de doar prótons em uma reação.", "association", 2, 5, ["acido-base"], ["iupac-gold"]],
    ["ânion", "Íon que ficou com sinal de menos", "Íon de carga elétrica negativa.", "association", 2, 4, ["estrutura-atomica"], ["iupac-gold"]],
    ["átomo", "Tijolo químico que ainda guarda a identidade do elemento", "Menor unidade que conserva as propriedades de um elemento químico.", "association", 1, 5, ["estrutura-atomica"], ["iupac-gold"]],
    ["base", "No pH, prefere o lado acima de sete", "Espécie química capaz de aceitar prótons em uma reação.", "association", 2, 5, ["acido-base"], ["iupac-gold"]],
    ["carbono", "Elemento que arma o esqueleto da química orgânica", "Elemento químico de número atômico seis, central nas moléculas orgânicas.", "association", 1, 5, ["elementos"], ["iupac-gold"]],
    ["catalisador", "Abre um atalho energético para a reação", "Substância que aumenta a velocidade de uma reação sem ser consumida no saldo final.", "association", 3, 4, ["reacoes"], ["iupac-gold"]],
    ["cátion", "Íon que carrega um sinal de mais", "Íon de carga elétrica positiva.", "association", 2, 4, ["estrutura-atomica"], ["iupac-gold"]],
    ["composto", "Substância em que dois ou mais elementos firmaram união química", "Substância pura formada por elementos diferentes ligados em proporção definida.", "association", 2, 5, ["materia"], ["iupac-gold"]],
    ["cristal", "Sólido que põe suas partículas em ordem de longo alcance", "Sólido com estrutura interna organizada em padrão periódico.", "association", 3, 4, ["materia"], ["iupac-gold"]],
    ["elemento", "Família de átomos com o mesmo número de prótons", "Classe química definida pelo número de prótons de seus átomos.", "association", 2, 5, ["estrutura-atomica"], ["iupac-gold"]],
    ["halogênio", "Membro da família que reúne flúor e cloro", "Elemento do grupo 17 da tabela periódica.", "trivia", 3, 3, ["tabela-periodica"], ["iupac-gold"]],
    ["hélio", "Gás nobre que sobe com o balão", "Elemento leve e pouco reativo de número atômico dois.", "association", 1, 5, ["elementos"], ["iupac-gold"]],
    ["hidrogênio", "Primeiro na tabela e mais abundante no Universo", "Elemento químico de número atômico um.", "trivia", 1, 5, ["elementos"], ["iupac-gold", "nasa-universe"]],
    ["íon", "Átomo que perdeu a neutralidade", "Átomo ou grupo químico com carga elétrica líquida.", "association", 1, 5, ["estrutura-atomica"], ["iupac-gold"]],
    ["isótopo", "Mesmo elemento, outra contagem de nêutrons", "Forma de um elemento com igual número de prótons e diferente número de nêutrons.", "association", 2, 4, ["estrutura-atomica"], ["iupac-gold"]],
    ["ligação", "O laço que mantém átomos juntos", "Interação química que une átomos ou íons.", "association", 2, 5, ["estrutura-atomica"], ["iupac-gold"]],
    ["metal", "Na tabela periódica, costuma conduzir bem e formar cátion", "Classe de elementos geralmente bons condutores de calor e eletricidade.", "association", 1, 5, ["materiais"], ["iupac-gold"]],
    ["mistura", "Divide o recipiente sem ganhar fórmula química própria", "Combinação física de substâncias que preservam suas identidades.", "association", 1, 5, ["materia"], ["iupac-gold"]],
    ["mol", "Dúzia da química, só que com cerca de 6,022 vezes dez à vigésima terceira unidades", "Unidade do SI para quantidade de matéria.", "association", 2, 4, ["quantidade-de-materia"], ["iupac-gold", "nist-si"]],
    ["molécula", "Pequena sociedade eletricamente neutra de átomos?", "Entidade eletricamente neutra formada por mais de um átomo.", "wordplay", 2, 5, ["estrutura-atomica"], ["iupac-gold"]],
    ["nêutron", "Morador sem carga do núcleo atômico", "Partícula eletricamente neutra encontrada nos núcleos atômicos.", "association", 1, 5, ["estrutura-atomica"], ["iupac-gold"]],
    ["nitrogênio", "Ocupa quase quatro quintos do ar terrestre", "Elemento gasoso que é o principal componente da atmosfera da Terra.", "trivia", 2, 5, ["elementos"], ["iupac-gold"]],
    ["oxigênio", "Elemento que alimenta a respiração e também muita combustão", "Gás do ar utilizado na respiração celular de muitos organismos.", "association", 1, 5, ["elementos"], ["iupac-gold", "openstax-bio"]],
    ["ozônio", "Trio de oxigênios que filtra ultravioleta lá no alto", "Molécula de três átomos de oxigênio presente na estratosfera.", "association", 2, 5, ["atmosfera"], ["iupac-gold", "noaa-weather"]],
    ["plasma", "Estado da matéria em que cargas circulam livres", "Gás ionizado com elétrons e íons livres.", "association", 2, 4, ["estados-da-materia"], ["iupac-gold"]],
    ["polímero", "Macromolécula que repete o mesmo passo muitas vezes", "Material formado por macromoléculas de unidades estruturais repetidas.", "association", 3, 4, ["materiais"], ["iupac-gold"]],
    ["próton", "Morador positivo do núcleo atômico", "Partícula de carga positiva encontrada nos núcleos atômicos.", "association", 1, 5, ["estrutura-atomica"], ["iupac-gold"]],
    ["produto", "O que sai do lado final de uma equação química", "Substância formada em uma reação química.", "association", 2, 5, ["reacoes"], ["iupac-gold"]],
    ["reação", "Troca os parceiros e rearranja os átomos", "Processo químico que transforma reagentes em novas substâncias.", "association", 1, 5, ["reacoes"], ["iupac-gold"]],
    ["reagente", "Entra em cena antes da seta da equação química", "Substância consumida ou transformada durante uma reação.", "association", 2, 5, ["reacoes"], ["iupac-gold"]],
    ["sal", "Parceiro iônico que costuma nascer de ácido com base", "Composto iônico formado por cátions e ânions.", "association", 1, 5, ["acido-base"], ["iupac-gold"]],
    ["solução", "Mistura em que os componentes não formam fases visíveis", "Mistura homogênea de uma ou mais substâncias.", "association", 1, 5, ["misturas"], ["iupac-gold"]],
    ["soluto", "É dissolvido e vira hóspede da solução", "Componente dissolvido em um solvente.", "association", 2, 4, ["misturas"], ["iupac-gold"]],
    ["solvente", "Abre espaço para o soluto na solução", "Componente que dissolve outro e costuma estar em maior proporção numa solução.", "association", 2, 4, ["misturas"], ["iupac-gold"]],
    ["valência", "Poder de combinação ligado aos elétrons mais externos", "Capacidade de combinação química de um átomo.", "association", 3, 3, ["estrutura-atomica"], ["iupac-gold"]],

    // Física — 35
    ["aceleração", "Conta quanto a velocidade muda a cada segundo", "Taxa de variação da velocidade com o tempo.", "association", 1, 5, ["mecanica"], ["openstax-physics"]],
    ["amplitude", "Da linha de equilíbrio até o pico da onda", "Maior afastamento de uma oscilação em relação ao equilíbrio.", "association", 2, 5, ["ondas"], ["openstax-physics"]],
    ["ampere", "Unidade que põe número na corrente elétrica", "Unidade básica do SI para corrente elétrica.", "association", 2, 4, ["eletricidade", "unidades"], ["nist-si"]],
    ["atrito", "Freio que nasce do contato entre superfícies", "Força que se opõe ao deslizamento relativo entre superfícies.", "association", 1, 5, ["mecanica"], ["openstax-physics"]],
    ["calor", "Energia em trânsito por diferença de temperatura", "Transferência de energia causada por uma diferença de temperatura.", "association", 1, 5, ["termodinamica"], ["openstax-physics"]],
    ["campo", "Mapa invisível que atribui uma influência a cada ponto", "Região descrita por uma grandeza física em cada ponto do espaço.", "association", 3, 4, ["fisica-moderna"], ["openstax-physics"]],
    ["corrente", "Fluxo ordenado de cargas num circuito", "Taxa de passagem de carga elétrica por uma seção.", "association", 1, 5, ["eletricidade"], ["openstax-physics"]],
    ["densidade", "Põe a massa na conta de cada volume", "Razão entre massa e volume de um corpo ou material.", "association", 1, 5, ["mecanica"], ["openstax-physics"]],
    ["difração", "A onda contorna a esquina e se espalha pela abertura", "Espalhamento de uma onda ao passar por uma abertura ou obstáculo.", "association", 3, 3, ["ondas"], ["openstax-physics"]],
    ["elétron", "Leva carga negativa ao redor do núcleo", "Partícula elementar de carga elétrica negativa.", "association", 1, 5, ["particulas"], ["openstax-physics"]],
    ["energia", "Muda de roupa entre cinética, térmica e potencial", "Grandeza que se conserva em sistemas isolados e pode produzir transformações.", "association", 1, 5, ["mecanica"], ["openstax-physics"]],
    ["entropia", "Na termodinâmica, mede quantos bastidores cabem no mesmo estado", "Grandeza ligada ao número de configurações microscópicas de um sistema.", "association", 4, 3, ["termodinamica"], ["openstax-physics"]],
    ["força", "Empurrão ou puxão que pode mudar o movimento", "Interação capaz de acelerar ou deformar um corpo.", "association", 1, 5, ["mecanica"], ["openstax-physics"]],
    ["fóton", "Pacote elementar entregue pela luz", "Quantum da radiação eletromagnética.", "association", 2, 4, ["particulas"], ["openstax-physics"]],
    ["frequência", "Quantos ciclos cabem em cada segundo", "Número de oscilações por unidade de tempo.", "association", 1, 5, ["ondas"], ["openstax-physics"]],
    ["gravidade", "Mantém pés no chão e luas em órbita", "Interação fundamental que atua entre corpos com massa e energia.", "association", 1, 5, ["mecanica"], ["openstax-physics"]],
    ["hertz", "Um ciclo por segundo, por extenso", "Unidade do SI equivalente a uma ocorrência por segundo.", "association", 2, 4, ["ondas", "unidades"], ["nist-si"]],
    ["impulso", "Força acumulada no tempo que altera o momento", "Produto da força pelo intervalo de tempo em que ela atua.", "association", 2, 4, ["mecanica"], ["openstax-physics"]],
    ["inércia", "Teimosia física contra mudanças de movimento?", "Propriedade de um corpo de resistir a alterações em seu estado de movimento.", "wordplay", 2, 5, ["mecanica"], ["openstax-physics"]],
    ["laser", "Luz enfileirada pela emissão estimulada", "Dispositivo que produz um feixe coerente e muito direcionado de luz.", "association", 2, 5, ["optica"], ["openstax-physics"]],
    ["magnetismo", "Faz a bússola conversar com o campo da Terra", "Fenômeno associado a campos magnéticos e cargas em movimento.", "association", 2, 5, ["eletromagnetismo"], ["openstax-physics"]],
    ["massa", "Não some quando o astronauta perde peso", "Grandeza que mede a inércia de um corpo.", "association", 1, 5, ["mecanica"], ["openstax-physics"]],
    ["momento", "Massa em movimento, na conta dos físicos?", "Grandeza vetorial igual ao produto da massa pela velocidade.", "wordplay", 3, 4, ["mecanica"], ["openstax-physics"]],
    ["onda", "Viaja levando energia sem carregar o meio junto", "Perturbação que se propaga no espaço e no tempo.", "association", 1, 5, ["ondas"], ["openstax-physics"]],
    ["potência", "Diz quão depressa a energia é transferida", "Taxa de realização de trabalho ou transferência de energia.", "association", 2, 5, ["mecanica"], ["openstax-physics"]],
    ["pressão", "Força que se espalha por uma área", "Razão entre a força perpendicular e a área sobre a qual ela atua.", "association", 1, 5, ["mecanica"], ["openstax-physics"]],
    ["quark", "Peça elementar encontrada dentro de prótons e nêutrons", "Partícula elementar que forma hádrons.", "association", 3, 3, ["particulas"], ["openstax-physics"]],
    ["reflexão", "A luz bate e volta", "Retorno de uma onda ao encontrar uma superfície.", "association", 1, 5, ["optica"], ["openstax-physics"]],
    ["refração", "A luz muda o rumo ao trocar de meio", "Mudança de velocidade e direção de uma onda ao atravessar meios diferentes.", "association", 2, 5, ["optica"], ["openstax-physics"]],
    ["temperatura", "Grandeza que decide para que lado o calor flui", "Medida do estado térmico de um sistema.", "association", 1, 5, ["termodinamica"], ["openstax-physics"]],
    ["tensão", "Diferença elétrica que empurra cargas pelo circuito", "Diferença de potencial elétrico entre dois pontos.", "association", 1, 5, ["eletricidade"], ["openstax-physics"]],
    ["joule", "Unidade que mede energia e trabalho", "Unidade do SI para energia, equivalente a um newton-metro.", "association", 2, 4, ["mecanica", "unidades"], ["nist-si"]],
    ["velocidade", "Tem módulo, direção e pressa?", "Taxa vetorial de mudança da posição com o tempo.", "wordplay", 1, 5, ["mecanica"], ["openstax-physics"]],
    ["volt", "Unidade escrita no empurrão elétrico da tomada", "Unidade do SI para diferença de potencial elétrico.", "association", 1, 5, ["eletricidade", "unidades"], ["nist-si"]],
    ["watt", "Unidade estampada na potência da lâmpada", "Unidade do SI para potência, igual a um joule por segundo.", "association", 1, 5, ["mecanica", "unidades"], ["nist-si"]],

    // Astronomia — 35
    ["anã branca", "Pequeno remanescente quente deixado por uma estrela como o Sol", "Núcleo estelar denso que resta depois que uma estrela de baixa massa perde suas camadas externas.", "association", 3, 3, ["estrelas"], ["nasa-universe"]],
    ["ano-luz", "Um ano no relógio da luz vira medida de distância?", "Distância que a luz percorre no vácuo durante um ano.", "wordplay", 1, 5, ["distancias"], ["nasa-universe"]],
    ["asteroide", "Rocha espacial que prefere orbitar sem virar planeta", "Pequeno corpo predominantemente rochoso que orbita uma estrela.", "association", 1, 5, ["sistema-solar"], ["nasa-universe"]],
    ["astro", "Nome-curinga para estrela, planeta ou outro corpo do céu", "Corpo celeste natural observado no céu.", "association", 1, 5, ["astronomia"], ["nasa-universe"]],
    ["aurora", "Cortina luminosa pintada por partículas solares perto dos polos", "Brilho atmosférico causado pela interação de partículas carregadas com gases em altas latitudes.", "association", 2, 5, ["sistema-solar"], ["nasa-universe"]],
    ["Big Bang", "Começo quente e denso da história cósmica", "Modelo segundo o qual o Universo se expandiu a partir de um estado inicial muito quente e denso.", "association", 1, 5, ["cosmologia"], ["nasa-universe"]],
    ["buraco negro", "Tem gravidade bastante para prender até a luz além do horizonte", "Objeto cuja região interna ao horizonte de eventos não permite escape de luz.", "association", 2, 5, ["cosmologia"], ["nasa-universe"]],
    ["cometa", "Gelo viajante que pode ganhar coma e cauda perto do Sol", "Pequeno corpo rico em gelos que libera gás e poeira ao ser aquecido.", "association", 1, 5, ["sistema-solar"], ["nasa-universe"]],
    ["constelação", "Desenho terrestre que liga estrelas no céu", "Região oficialmente delimitada do céu, associada a um padrão aparente de estrelas.", "association", 1, 5, ["observacao"], ["nasa-universe"]],
    ["cratera", "Cicatriz redonda comum em luas atingidas", "Depressão circular produzida geralmente pelo impacto de um corpo espacial.", "association", 1, 5, ["sistema-solar"], ["nasa-universe"]],
    ["eclipse", "Um astro entra na sombra ou bloqueia outro na nossa visão", "Ocultação total ou parcial de um corpo celeste por alinhamento.", "association", 1, 5, ["observacao"], ["nasa-universe"]],
    ["equinócio", "Data em que o Sol cruza o equador celeste", "Momento anual em que o centro do Sol atravessa o equador celeste.", "trivia", 2, 4, ["movimentos-da-terra"], ["nasa-universe"]],
    ["estrela", "Esfera que brilha com fusão no próprio núcleo", "Esfera autogravitante de plasma que gera energia por fusão nuclear durante grande parte da vida.", "association", 1, 5, ["estrelas"], ["nasa-universe"]],
    ["exoplaneta", "Mundo que gira ao redor de outro sol", "Planeta que orbita uma estrela fora do Sistema Solar.", "association", 1, 5, ["exoplanetas"], ["nasa-universe"]],
    ["galáxia", "Cidade cósmica de estrelas, gás, poeira e matéria escura", "Grande sistema gravitacional formado por estrelas e matéria interestelar.", "association", 1, 5, ["cosmologia"], ["nasa-universe"]],
    ["Lua", "Satélite natural que troca de fase no céu da Terra", "Único satélite natural da Terra.", "trivia", 1, 5, ["sistema-solar"], ["nasa-universe"]],
    ["maré", "Sobe e desce sob a atração da Lua e do Sol", "Variação periódica do nível oceânico causada principalmente pela gravidade lunar e solar.", "association", 1, 5, ["movimentos-da-terra"], ["nasa-universe"]],
    ["meteoro", "Risco luminoso de material espacial atravessando a atmosfera", "Fenômeno de luz produzido por material espacial ao atravessar a atmosfera.", "association", 1, 5, ["sistema-solar"], ["nasa-universe"]],
    ["meteorito", "Visitante espacial que termina a viagem no chão", "Fragmento de meteoroide que sobrevive à atmosfera e alcança a superfície.", "association", 2, 5, ["sistema-solar"], ["nasa-universe"]],
    ["nebulosa", "Nuvem interestelar que pode embalar estrelas novas", "Nuvem de gás e poeira situada entre as estrelas.", "association", 2, 5, ["estrelas"], ["nasa-universe"]],
    ["órbita", "Caminho curvado pela gravidade ao redor de outro corpo", "Trajetória de um corpo submetido à gravidade de outro.", "association", 1, 5, ["mecanica-celeste"], ["nasa-universe"]],
    ["parsec", "Distância cuja paralaxe anual mede um segundo de arco", "Unidade astronômica de distância equivalente a cerca de 3,26 anos-luz.", "trivia", 3, 3, ["distancias"], ["nasa-universe"]],
    ["periélio", "Ponto da órbita mais perto do Sol", "Posição de menor distância ao Sol numa órbita.", "association", 3, 3, ["mecanica-celeste"], ["nasa-universe"]],
    ["planeta", "Domina a vizinhança da volta que dá em sua estrela", "Corpo celeste quase esférico que orbita uma estrela e domina sua vizinhança orbital.", "association", 1, 5, ["sistema-solar"], ["nasa-universe"]],
    ["pulsar", "Farol de estrela de nêutrons que gira depressa", "Estrela de nêutrons rotativa observada por pulsos regulares de radiação.", "association", 3, 3, ["estrelas"], ["nasa-universe"]],
    ["quasar", "Núcleo galáctico tão luminoso que parece estrela distante", "Núcleo galáctico ativo alimentado por matéria que cai num buraco negro supermassivo.", "association", 3, 3, ["cosmologia"], ["nasa-universe"]],
    ["rotação", "Volta que um astro dá em torno do próprio eixo", "Movimento de um corpo em torno de seu eixo.", "association", 1, 5, ["mecanica-celeste"], ["nasa-universe"]],
    ["satélite", "Companheiro natural ou artificial preso a uma órbita", "Corpo que gira ao redor de outro por ação gravitacional.", "association", 1, 5, ["mecanica-celeste"], ["nasa-universe"]],
    ["Sol", "Nossa estrela, sem precisar dizer o nome", "Estrela no centro do Sistema Solar.", "elliptical", 1, 5, ["sistema-solar"], ["nasa-universe"]],
    ["solstício", "Marca o extremo anual da duração do dia", "Momento em que o Sol atinge sua maior distância angular do equador celeste.", "association", 2, 4, ["movimentos-da-terra"], ["nasa-universe"]],
    ["supernova", "Explosão estelar que pode ofuscar uma galáxia", "Explosão extremamente luminosa que encerra certas fases da evolução estelar.", "association", 2, 5, ["estrelas"], ["nasa-universe"]],
    ["telescópio", "Olho que coleta luz de muito longe", "Instrumento que reúne radiação para observar objetos distantes.", "association", 1, 5, ["observacao"], ["nasa-universe"]],
    ["translação", "Viagem orbital da Terra ao redor do Sol", "Movimento de um corpo ao redor de outro.", "association", 1, 5, ["movimentos-da-terra"], ["nasa-universe"]],
    ["universo", "Tudo o que cabe no espaço-tempo", "Totalidade do espaço, do tempo, da matéria e da energia.", "association", 1, 5, ["cosmologia"], ["nasa-universe"]],
    ["zênite", "Ponto do céu exatamente sobre a cabeça", "Ponto da esfera celeste diretamente acima do observador.", "association", 2, 4, ["observacao"], ["nasa-universe"]],

    // Ciências da Terra e atmosfera — 35
    ["aquífero", "Cofre subterrâneo que abastece poços", "Formação geológica permeável que armazena e transmite água subterrânea.", "association", 2, 4, ["hidrologia"], ["usgs-water"]],
    ["arenito", "Rocha que cimenta antigos grãos de areia", "Rocha sedimentar formada principalmente por grãos de areia consolidados.", "association", 2, 4, ["geologia"], ["openstax-earth"]],
    ["basalto", "Rocha escura que nasce de lava resfriada", "Rocha ígnea vulcânica comum, de granulação fina.", "association", 2, 4, ["geologia"], ["openstax-earth"]],
    ["chuva", "Nuvem devolvendo água em gotas", "Precipitação de água líquida que cai da atmosfera.", "association", 1, 5, ["meteorologia"], ["noaa-weather"]],
    ["ciclone", "Sistema de baixa pressão com ventos em rotação", "Circulação atmosférica organizada ao redor de um centro de baixa pressão.", "association", 2, 5, ["meteorologia"], ["noaa-weather"]],
    ["clima", "O tempo quando observado por muitas décadas", "Padrão de condições atmosféricas de uma região em longo prazo.", "association", 1, 5, ["climatologia"], ["noaa-weather"]],
    ["crosta", "Casca rochosa mais externa da Terra", "Camada sólida mais externa do planeta.", "association", 1, 5, ["geologia"], ["openstax-earth"]],
    ["epicentro", "Ponto da superfície diretamente acima do início do abalo", "Local na superfície situado sobre o foco de um terremoto.", "association", 2, 5, ["sismologia"], ["usgs-earthquake"]],
    ["erosão", "Desgasta aqui e transporta o material para lá", "Remoção e transporte de solo ou rocha por água, vento, gelo ou gravidade.", "association", 1, 5, ["geologia"], ["usgs-water"]],
    ["falha", "Fratura da crosta em que blocos se deslocam", "Ruptura geológica ao longo da qual houve movimento relativo.", "association", 2, 5, ["sismologia"], ["usgs-earthquake"]],
    ["fóssil", "Notícia da vida antiga guardada na rocha", "Resto, molde ou vestígio preservado de um organismo do passado.", "association", 1, 5, ["paleontologia"], ["openstax-bio"]],
    ["frente", "Fronteira móvel entre massas de ar", "Zona de transição entre massas de ar com propriedades diferentes.", "association", 2, 5, ["meteorologia"], ["noaa-weather"]],
    ["furacão", "Ciclone tropical que recebe nome no Atlântico", "Nome dado a um ciclone tropical intenso no Atlântico Norte e no nordeste do Pacífico.", "association", 1, 5, ["meteorologia"], ["noaa-weather"]],
    ["geada", "Manto de gelo fino que a madrugada deixa nas superfícies", "Depósito de cristais de gelo formado perto do solo em condições frias.", "association", 1, 5, ["meteorologia"], ["noaa-weather"]],
    ["geosfera", "Parte rochosa do planeta, da crosta ao núcleo", "Conjunto das porções sólidas da Terra.", "association", 2, 4, ["geologia"], ["usgs-earthquake"]],
    ["granito", "Rocha de cristais visíveis que esfria devagar no interior", "Rocha ígnea intrusiva rica em quartzo e feldspato.", "association", 2, 5, ["geologia"], ["openstax-earth"]],
    ["granizo", "Pedra de gelo fabricada por nuvem de tempestade", "Precipitação em bolas ou fragmentos de gelo.", "association", 1, 5, ["meteorologia"], ["noaa-weather"]],
    ["lava", "É magma depois de alcançar a superfície", "Rocha fundida expelida na superfície terrestre.", "association", 1, 5, ["vulcanologia"], ["usgs-volcano"]],
    ["litosfera", "Casca rígida que está quebrada em placas", "Camada rígida formada pela crosta e pela parte superior do manto.", "association", 2, 4, ["tectonica"], ["openstax-earth"]],
    ["magma", "Rocha em fusão que ainda não chegou à superfície", "Mistura de material rochoso fundido, cristais e gases no interior da Terra.", "association", 1, 5, ["vulcanologia"], ["usgs-volcano"]],
    ["manto", "Camada espessa entre a crosta e o núcleo", "Porção interna da Terra situada abaixo da crosta e acima do núcleo.", "association", 1, 5, ["geologia"], ["openstax-earth"]],
    ["mineral", "Sólido natural com receita química e estrutura cristalina", "Sólido natural com composição e arranjo atômico característicos.", "association", 2, 5, ["geologia"], ["usgs-earthquake"]],
    ["monção", "Vento sazonal cuja virada reorganiza as chuvas", "Sistema de ventos que muda de direção conforme a estação do ano.", "association", 3, 4, ["meteorologia"], ["noaa-weather"]],
    ["nuvem", "Suspensão de gotículas que desenha formas no céu", "Conjunto visível de gotículas de água ou cristais de gelo na atmosfera.", "association", 1, 5, ["meteorologia"], ["noaa-weather"]],
    ["placa", "Grande peça rígida do quebra-cabeça da litosfera", "Bloco da litosfera que se move sobre camadas mais dúcteis.", "association", 2, 5, ["tectonica"], ["usgs-earthquake"]],
    ["rocha", "Agregado natural que escreve capítulos da geologia", "Material sólido natural da crosta, geralmente formado por minerais.", "association", 1, 5, ["geologia"], ["openstax-earth"]],
    ["sedimento", "Partícula solta à espera de virar camada", "Material fragmentado transportado e depositado por processos naturais.", "association", 2, 4, ["geologia"], ["usgs-water"]],
    ["sismo", "Abalo que libera energia acumulada numa falha", "Tremor do solo produzido por liberação súbita de energia na Terra.", "association", 1, 5, ["sismologia"], ["usgs-earthquake"]],
    ["tectônica", "A dança lenta das placas do planeta", "Conjunto de processos ligados ao movimento e à deformação da litosfera.", "association", 2, 4, ["tectonica"], ["openstax-earth"]],
    ["tornado", "Coluna de ar giratória que toca nuvem e chão", "Vórtice atmosférico intenso em contato com a superfície e uma nuvem.", "association", 1, 5, ["meteorologia"], ["noaa-weather"]],
    ["troposfera", "Andar mais baixo da atmosfera, onde mora o tempo", "Camada atmosférica junto à superfície em que ocorre a maior parte dos fenômenos meteorológicos.", "association", 2, 4, ["atmosfera"], ["noaa-weather"]],
    ["tsunami", "Série de ondas movida por um grande deslocamento de água", "Trem de ondas oceânicas gerado por deslocamento súbito de grande volume de água.", "association", 1, 5, ["sismologia"], ["usgs-earthquake"]],
    ["umidade", "Diz quanta água invisível o ar carrega", "Quantidade de vapor de água presente no ar.", "association", 1, 5, ["meteorologia"], ["noaa-weather"]],
    ["vento", "Ar em movimento entre diferenças de pressão", "Movimento do ar em relação à superfície terrestre.", "association", 1, 5, ["meteorologia"], ["noaa-weather"]],
    ["vulcão", "Passagem por onde o interior quente alcança a superfície", "Abertura e estrutura geológica associada à saída de magma e gases.", "association", 1, 5, ["vulcanologia"], ["usgs-volcano"]],

    // Matemática e dados — 35
    ["algoritmo", "Receita finita que um computador consegue seguir", "Sequência definida de passos para resolver um problema.", "association", 1, 5, ["computacao"], ["nist-glossary"]],
    ["amostra", "Pequena parte chamada para representar o todo", "Subconjunto de uma população selecionado para análise.", "association", 2, 5, ["estatistica"], ["openstax-stats"]],
    ["ângulo", "Abertura que nasce do encontro de duas semirretas", "Figura formada por duas semirretas com a mesma origem.", "association", 1, 5, ["geometria"], ["openstax-math"]],
    ["área", "Base vezes altura, no caso do retângulo: ___", "Medida da extensão de uma superfície plana.", "fill-blank", 1, 5, ["geometria"], ["openstax-math"]],
    ["círculo", "Redondo por dentro e pela borda?", "Região plana delimitada por uma circunferência.", "wordplay", 1, 5, ["geometria"], ["openstax-math"]],
    ["dado", "Matéria-prima que a estatística organiza", "Valor ou informação obtida por observação ou medição.", "association", 1, 5, ["estatistica"], ["openstax-stats"]],
    ["decimal", "Escrito na base dez, geralmente com vírgula", "Representação numérica baseada em potências de dez.", "association", 1, 5, ["aritmetica"], ["openstax-math"]],
    ["divisor", "O segundo número na conta de dividir", "Número pelo qual outro número é dividido.", "association", 1, 5, ["aritmetica"], ["openstax-math"]],
    ["equação", "Igualdade que põe uma incógnita para trabalhar", "Sentença matemática que afirma a igualdade entre expressões.", "association", 1, 5, ["algebra"], ["openstax-math"]],
    ["evento", "Na probabilidade, um conjunto de resultados possíveis", "Subconjunto do espaço amostral de um experimento aleatório.", "association", 2, 4, ["estatistica"], ["openstax-stats"]],
    ["eixo", "Linha de referência de um gráfico ou rotação", "Reta usada como referência em um sistema de coordenadas.", "association", 1, 5, ["geometria"], ["openstax-math"]],
    ["fator", "Em 3 × 4, cada número ocupa este papel", "Cada termo que participa de uma multiplicação.", "trivia", 1, 5, ["aritmetica"], ["openstax-math"]],
    ["fração", "Põe o numerador sobre o denominador", "Número escrito como quociente de inteiros, com denominador diferente de zero.", "association", 1, 5, ["aritmetica"], ["openstax-math"]],
    ["função", "Máquina matemática que dá uma única saída para cada entrada", "Relação que associa cada elemento do domínio a exatamente um valor.", "association", 2, 5, ["algebra"], ["openstax-math"]],
    ["gráfico", "Transforma números e relações em desenho", "Representação visual de dados ou de uma relação matemática.", "association", 1, 5, ["dados"], ["openstax-stats"]],
    ["incógnita", "A letra que a equação manda descobrir", "Quantidade desconhecida cujo valor deve ser determinado.", "association", 1, 5, ["algebra"], ["openstax-math"]],
    ["infinito", "Horizonte matemático que nunca vira último número", "Ideia de algo sem limite ou fim.", "association", 2, 5, ["fundamentos"], ["openstax-math"]],
    ["lógica", "Ferramenta que separa argumento válido de palpite", "Estudo das regras de inferência e do raciocínio válido.", "association", 2, 5, ["fundamentos"], ["openstax-math"]],
    ["matriz", "Retângulo de números organizado em linhas e colunas", "Arranjo retangular de elementos usado em cálculos algébricos.", "association", 2, 5, ["algebra"], ["openstax-math"]],
    ["média", "Soma tudo e divide pela quantidade", "Valor obtido ao dividir a soma dos dados pelo número de observações.", "association", 1, 5, ["estatistica"], ["openstax-stats"]],
    ["mediana", "Fica no meio depois que os dados entram em ordem", "Valor central de um conjunto de dados ordenado.", "association", 1, 5, ["estatistica"], ["openstax-stats"]],
    ["moda", "O valor que mais se repete nos dados?", "Valor de maior frequência em um conjunto.", "wordplay", 1, 5, ["estatistica"], ["openstax-stats"]],
    ["plano", "Superfície matemática que se estende em duas dimensões", "Superfície bidimensional ideal que se prolonga sem limite.", "association", 1, 5, ["geometria"], ["openstax-math"]],
    ["ponto", "Marca uma posição sem ocupar dimensão", "Elemento geométrico que indica apenas uma localização.", "association", 1, 5, ["geometria"], ["openstax-math"]],
    ["primo", "Só aceita divisão inteira por um e por si mesmo", "Número inteiro maior que um com exatamente dois divisores positivos.", "association", 1, 5, ["aritmetica"], ["openstax-math"]],
    ["probabilidade", "Número entre zero e um que mede a chance", "Medida matemática da possibilidade de um evento ocorrer.", "association", 1, 5, ["estatistica"], ["openstax-stats"]],
    ["raio", "Vai do centro até a borda da circunferência", "Segmento que liga o centro de um círculo à sua circunferência.", "association", 1, 5, ["geometria"], ["openstax-math"]],
    ["razão", "Comparação que se escreve como um quociente", "Quociente usado para comparar duas quantidades.", "association", 1, 5, ["aritmetica"], ["openstax-math"]],
    ["reta", "Caminho sem curva que não termina em nenhum lado", "Linha unidimensional que se prolonga infinitamente nas duas direções.", "association", 1, 5, ["geometria"], ["openstax-math"]],
    ["soma", "Resultado que aparece depois do sinal de mais", "Resultado de uma operação de adição.", "association", 1, 5, ["aritmetica"], ["openstax-math"]],
    ["teorema", "Afirmação matemática que já apresentou sua prova", "Proposição demonstrada a partir de axiomas e resultados anteriores.", "association", 2, 5, ["fundamentos"], ["openstax-math"]],
    ["triângulo", "Três lados fecham esta figura", "Polígono formado por três lados e três ângulos.", "association", 1, 5, ["geometria"], ["openstax-math"]],
    ["vetor", "Módulo e direção cabem nesta seta matemática", "Grandeza representada por magnitude e direção.", "association", 2, 5, ["algebra"], ["openstax-math"]],
    ["volume", "Comprimento vezes largura vezes altura, para um bloco: ___", "Medida do espaço tridimensional ocupado por um corpo.", "fill-blank", 1, 5, ["geometria"], ["openstax-math"]],
    ["zero", "Guarda lugar sem acrescentar quantidade", "Identidade aditiva e número que representa ausência de quantidade.", "association", 1, 5, ["aritmetica"], ["openstax-math"]],

    // Método científico, instrumentos e tecnologia durável — 35
    ["análise", "Desmonta o problema para entender suas partes", "Exame sistemático de dados, materiais ou ideias.", "association", 1, 5, ["metodo-cientifico"], ["openstax-bio"]],
    ["artigo", "Formato em que uma pesquisa entra na conversa acadêmica", "Texto acadêmico que comunica métodos, resultados e conclusões.", "association", 2, 5, ["comunicacao-cientifica"], ["openstax-bio"]],
    ["balança", "No laboratório, põe a massa no visor", "Instrumento usado para determinar a massa de uma amostra.", "association", 1, 5, ["instrumentos"], ["openstax-physics"]],
    ["béquer", "Copo de laboratório com bico, bom para misturar e aquecer", "Recipiente cilíndrico de laboratório usado para conter líquidos.", "association", 2, 4, ["instrumentos"], ["openstax-bio"]],
    ["bit", "Escolha mínima do computador: zero ou um", "Dígito binário que pode assumir um de dois valores.", "association", 1, 5, ["computacao"], ["nist-glossary"]],
    ["byte", "Pacote que normalmente reúne oito bits", "Sequência de oito bits tratada como uma unidade.", "association", 1, 5, ["computacao"], ["nist-glossary"]],
    ["ciência", "Duvida, observa, testa e revisa", "Investigação sistemática do mundo baseada em evidências verificáveis.", "association", 1, 5, ["metodo-cientifico"], ["openstax-bio"]],
    ["citação", "Deixa o endereço de uma ideia emprestada", "Referência que identifica a fonte de uma informação ou argumento.", "association", 2, 5, ["comunicacao-cientifica"], ["openstax-bio"]],
    ["código", "Texto que vira instrução para a máquina", "Conjunto de instruções escritas em linguagem de programação.", "association", 1, 5, ["computacao"], ["nist-glossary"]],
    ["experimento", "Pergunta científica colocada à prova em condições planejadas", "Procedimento controlado usado para testar uma hipótese ou observar um fenômeno.", "association", 1, 5, ["metodo-cientifico"], ["openstax-bio"]],
    ["erro", "Diferença entre o medido e o valor de referência", "Desvio de uma medição em relação a um valor aceito ou verdadeiro.", "association", 2, 5, ["metrologia"], ["openstax-physics"]],
    ["escala", "Do mapa ao termômetro, organiza grandezas em níveis", "Sistema graduado usado para representar ou comparar valores.", "association", 1, 5, ["metrologia"], ["openstax-physics"]],
    ["evidência", "O que uma explicação precisa encarar no mundo real", "Observação ou resultado usado para apoiar ou contestar uma hipótese.", "association", 2, 5, ["metodo-cientifico"], ["openstax-bio"]],
    ["hipótese", "Explicação provisória que aceita ser posta à prova", "Proposição testável formulada para explicar uma observação.", "association", 2, 5, ["metodo-cientifico"], ["openstax-bio"]],
    ["laboratório", "Lugar onde pergunta vira procedimento e medição", "Ambiente equipado para realizar análises e experimentos.", "association", 1, 5, ["instrumentos"], ["openstax-bio"]],
    ["medida", "Número acompanhado de unidade depois da observação", "Resultado quantitativo de comparar uma grandeza com um padrão.", "association", 1, 5, ["metrologia"], ["nist-si"]],
    ["método", "Caminho organizado entre a pergunta e a conclusão", "Conjunto ordenado de procedimentos para investigar um problema.", "association", 1, 5, ["metodo-cientifico"], ["openstax-bio"]],
    ["microscópio", "Empresta tamanho aparente ao que é pequeno demais", "Instrumento que amplia detalhes de objetos muito pequenos.", "association", 1, 5, ["instrumentos"], ["openstax-bio"]],
    ["modelo", "Versão simplificada da realidade usada para explicar ou prever", "Representação conceitual, física ou matemática de um sistema.", "association", 2, 5, ["metodo-cientifico"], ["openstax-bio"]],
    ["pipeta", "Transfere pequenos volumes sem servir de copo", "Instrumento de laboratório usado para medir e transferir líquidos.", "association", 2, 5, ["instrumentos"], ["openstax-bio"]],
    ["proveta", "Cilindro graduado que mede o líquido", "Recipiente alto e graduado usado para medir volumes.", "association", 1, 5, ["instrumentos"], ["openstax-bio"]],
    ["radar", "Encontra distância e velocidade pelo eco de rádio", "Sistema que detecta objetos por ondas de rádio refletidas.", "association", 1, 5, ["sensoriamento"], ["nist-glossary"]],
    ["replicação", "Repete um estudo para ver se o resultado se sustenta", "Repetição independente de um procedimento científico para verificar seus achados.", "association", 3, 4, ["metodo-cientifico"], ["openstax-bio"]],
    ["resumo", "Versão de bolso de um trabalho científico?", "Síntese breve dos objetivos, métodos e resultados de um texto.", "wordplay", 1, 5, ["comunicacao-cientifica"], ["openstax-bio"]],
    ["revisão", "Antes de publicar, põe métodos e conclusões sob outros olhos", "Exame crítico de um trabalho ou conjunto de estudos.", "association", 2, 5, ["comunicacao-cientifica"], ["openstax-bio"]],
    ["robô", "Máquina programável que percebe e age", "Sistema controlado por programa capaz de executar ações no mundo físico.", "association", 1, 5, ["tecnologia"], ["nist-glossary"]],
    ["sensor", "Traduz uma grandeza física para um sinal", "Dispositivo que detecta uma condição e produz uma resposta mensurável.", "association", 1, 5, ["sensoriamento"], ["nist-glossary"]],
    ["síntese", "Remonta as partes numa explicação conjunta", "Integração de informações separadas em um todo coerente.", "association", 2, 5, ["metodo-cientifico"], ["openstax-bio"]],
    ["sonar", "Procura objetos pelo eco do som, geralmente na água", "Sistema de detecção e localização que utiliza ondas sonoras.", "association", 1, 5, ["sensoriamento"], ["openstax-physics"]],
    ["sonda", "Instrumento enviado para medir onde o cientista não alcança", "Dispositivo que explora um ambiente e coleta medições.", "association", 1, 5, ["sensoriamento"], ["nasa-universe"]],
    ["teoria", "Na ciência, é explicação robusta, não mero palpite", "Explicação ampla sustentada por evidências e testes repetidos.", "association", 1, 5, ["metodo-cientifico"], ["openstax-bio"]],
    ["teste", "Põe uma previsão diante dos fatos", "Procedimento usado para avaliar uma hipótese, material ou sistema.", "association", 1, 5, ["metodo-cientifico"], ["openstax-bio"]],
    ["unidade", "Padrão que acompanha o número numa medição", "Quantidade definida adotada como referência para medir uma grandeza.", "association", 1, 5, ["metrologia"], ["nist-si"]],
    ["variável", "Fator que muda ou é medido no experimento", "Característica que pode assumir diferentes valores numa investigação.", "association", 1, 5, ["metodo-cientifico"], ["openstax-bio"]],
    ["viés", "Inclinação sistemática que entorta o resultado?", "Tendência sistemática que afasta uma estimativa ou conclusão da realidade.", "wordplay", 2, 4, ["metodo-cientifico"], ["openstax-stats"]],
  ],
} as const satisfies BiomeBundle;

export const cienciaEntries = entriesFromBundle(cienciaBundle);

// Auditoria: 250 registros (40 legados), 250 chaves únicas, comprimentos 71/171/8
// (3–5/6–10/11–18), 14 fontes conferidas e 0 colisões com os 120 legados externos.
