import { entriesFromBundle, type BiomeBundle } from "./shared.js";

const LEXICAL_SOURCES = ["unitex-pb", "volp-abl", "priberam"] as const;

const cotidianoBundle = {
  biome: "cotidiano",
  prefix: "cot",
  editorialSource: "curadoria-cruzaverso-cotidiano-v3",
  sources: [
    {
      sourceId: "unitex-pb",
      title: "Unitex/GramLab — recursos linguísticos para Português do Brasil",
      url: "https://github.com/UnitexGramLab/unitex-lingua/tree/master/pt-BR",
      license: "LGPLLR",
      role: "lexical",
    },
    {
      sourceId: "volp-abl",
      title: "Vocabulário Ortográfico da Língua Portuguesa — Academia Brasileira de Letras",
      url: "https://www.academia.org.br/nossa-lingua/busca-no-vocabulario",
      license: "consulta oficial; conteúdo-fonte não reproduzido",
      role: "orthographic",
    },
    {
      sourceId: "priberam",
      title: "Dicionário Priberam da Língua Portuguesa — consulta em português do Brasil",
      url: "https://dicionario.priberam.org/",
      license: "consulta lexicográfica; conteúdo-fonte não reproduzido",
      role: "lexical",
    },
  ],
  records: [
    // Casa e seus espaços (25)
    ["cozinha", "Onde a fome começa a virar almoço", "Cômodo destinado ao preparo de alimentos.", "association", 2, 5, ["casa", "comodos"], LEXICAL_SOURCES],
    ["despensa", "Estoque doméstico que cabe num cômodo", "Lugar da casa reservado a mantimentos.", "association", 2, 4, ["casa", "organizacao"], LEXICAL_SOURCES],
    ["garagem", "Dormitório de carro?", "Espaço coberto usado para guardar veículos.", "wordplay", 2, 5, ["casa", "transporte"], LEXICAL_SOURCES],
    ["interruptor", "Um toque nele muda o clima da sala", "Peça que abre ou fecha o circuito de uma lâmpada.", "association", 2, 5, ["casa", "eletricidade"], LEXICAL_SOURCES],
    ["janela", "Moldura da paisagem na parede", "Abertura que permite entrada de luz e ventilação.", "elliptical", 1, 5, ["casa", "estrutura"], LEXICAL_SOURCES],
    ["quintal", "Pedaço de céu que pertence à casa", "Área descoberta ligada a uma residência.", "association", 2, 5, ["casa", "area-externa"], LEXICAL_SOURCES],
    ["rodapé", "Acabamento no encontro da parede com o chão", "Faixa instalada na base das paredes.", "elliptical", 2, 4, ["casa", "acabamento"], LEXICAL_SOURCES],
    ["sala", "___ de estar ou de jantar", "Parte da casa geralmente usada para convivência.", "fill-blank", 1, 5, ["casa", "comodos"], LEXICAL_SOURCES],
    ["quarto", "Endereço do sono dentro de casa", "Cômodo onde normalmente ficam cama e guarda-roupa.", "association", 2, 5, ["casa", "comodos"], LEXICAL_SOURCES],
    ["banheiro", "Cômodo de banho e espelho", "Parte da casa com vaso sanitário e chuveiro.", "elliptical", 1, 5, ["casa", "comodos"], LEXICAL_SOURCES],
    ["varanda", "Pausa coberta entre a casa e o lado de fora", "Área aberta ou semiaberta ligada à fachada.", "association", 2, 5, ["casa", "area-externa"], LEXICAL_SOURCES],
    ["corredor", "Passagem que costura os cômodos", "Trecho estreito que liga partes de uma construção.", "association", 2, 5, ["casa", "estrutura"], LEXICAL_SOURCES],
    ["telhado", "Guarda-chuva imóvel da casa?", "Cobertura externa formada por telhas.", "wordplay", 2, 5, ["casa", "estrutura"], LEXICAL_SOURCES],
    ["parede", "Limite vertical que também recebe quadros", "Estrutura que separa ou fecha ambientes.", "association", 1, 5, ["casa", "estrutura"], LEXICAL_SOURCES],
    ["teto", "O piso do andar de cima, visto por baixo?", "Superfície que fecha um ambiente na parte superior.", "wordplay", 3, 5, ["casa", "estrutura"], LEXICAL_SOURCES],
    ["piso", "Onde os passos deixam suas marcas", "Superfície sobre a qual se caminha num ambiente.", "association", 2, 5, ["casa", "acabamento"], LEXICAL_SOURCES],
    ["porta", "Abre caminho sem sair da parede", "Peça móvel que permite ou impede a passagem.", "association", 2, 5, ["casa", "estrutura"], LEXICAL_SOURCES],
    ["portão", "___ eletrônico, na entrada do condomínio", "Fechamento móvel de uma entrada externa.", "fill-blank", 1, 5, ["casa", "estrutura"], LEXICAL_SOURCES],
    ["muro", "Fronteira de tijolos entre terrenos", "Construção vertical que cerca uma propriedade.", "elliptical", 1, 5, ["casa", "estrutura"], LEXICAL_SOURCES],
    ["escada", "Caminho que sobe em pequenos patamares", "Conjunto de degraus que liga níveis diferentes.", "association", 1, 5, ["casa", "estrutura"], LEXICAL_SOURCES],
    ["sacada", "Varanda que avança sobre a fachada", "Plataforma externa elevada, acessível por um cômodo.", "elliptical", 2, 4, ["casa", "area-externa"], LEXICAL_SOURCES],
    ["sótão", "Cômodo espremido logo abaixo do telhado", "Espaço interno situado na parte mais alta da casa.", "association", 2, 4, ["casa", "comodos"], LEXICAL_SOURCES],
    ["porão", "Cômodo que mora abaixo do térreo?", "Espaço de uma construção situado sob o nível principal.", "wordplay", 3, 4, ["casa", "comodos"], LEXICAL_SOURCES],
    ["campainha", "Visita anunciada em som", "Dispositivo sonoro usado para chamar quem está dentro.", "association", 2, 5, ["casa", "entrada"], LEXICAL_SOURCES],
    ["tomada", "Par na parede para os pinos do plugue", "Ponto fixo que fornece conexão à rede elétrica.", "elliptical", 1, 5, ["casa", "eletricidade"], LEXICAL_SOURCES],

    // Cozinha e utensílios (25)
    ["cafeteira", "Acorda a casa pelo aroma", "Aparelho ou utensílio usado para preparar café.", "association", 1, 5, ["cozinha", "utensilios"], LEXICAL_SOURCES],
    ["escorredor", "Estação da louça entre a pia e o armário", "Suporte vazado onde pratos e copos secam.", "association", 2, 4, ["cozinha", "utensilios"], LEXICAL_SOURCES],
    ["receita", "Mapa de um prato?", "Lista de ingredientes acompanhada do modo de preparo.", "wordplay", 2, 5, ["cozinha", "preparo"], LEXICAL_SOURCES],
    ["xícara", "Pequena, com asa, mas não voa?", "Recipiente com alça usado para bebidas quentes.", "wordplay", 2, 5, ["cozinha", "utensilios"], LEXICAL_SOURCES],
    ["panela", "Onde os ingredientes dividem o fogo", "Recipiente fundo usado para preparar comida no fogão.", "association", 2, 5, ["cozinha", "utensilios"], LEXICAL_SOURCES],
    ["frigideira", "Palco raso do ovo frito", "Utensílio baixo, com cabo, usado para fritar alimentos.", "association", 2, 5, ["cozinha", "utensilios"], LEXICAL_SOURCES],
    ["chaleira", "Pode assoviar quando a água está no ponto", "Recipiente com bico próprio para aquecer água.", "association", 1, 5, ["cozinha", "utensilios"], LEXICAL_SOURCES],
    ["garfo", "Talher de dentes que não mastigam?", "Utensílio com pontas usado para espetar alimentos.", "wordplay", 2, 5, ["cozinha", "talheres"], LEXICAL_SOURCES],
    ["faca", "Talher que ganha fio, não linha?", "Instrumento de lâmina usado para cortar.", "wordplay", 2, 5, ["cozinha", "talheres"], LEXICAL_SOURCES],
    ["colher", "Talher em forma de pequena concha", "Utensílio usado para levar líquidos ou porções à boca.", "elliptical", 1, 5, ["cozinha", "talheres"], LEXICAL_SOURCES],
    ["prato", "A mesa põe um lugar para cada um", "Recipiente individual e baixo em que a comida é servida.", "association", 2, 5, ["cozinha", "louca"], LEXICAL_SOURCES],
    ["copo", "Entre a garrafa e o gole", "Recipiente sem alça usado para beber.", "elliptical", 1, 5, ["cozinha", "louca"], LEXICAL_SOURCES],
    ["tigela", "Recipiente fundo para sopa ou cereal", "Vasilha arredondada, mais funda que um prato.", "elliptical", 1, 5, ["cozinha", "louca"], LEXICAL_SOURCES],
    ["travessa", "Vai cheia da cozinha ao centro da mesa", "Recipiente largo usado para servir alimentos.", "association", 2, 5, ["cozinha", "louca"], LEXICAL_SOURCES],
    ["assadeira", "Forma que encara o forno", "Recipiente próprio para levar alimentos ao forno.", "association", 2, 5, ["cozinha", "utensilios"], LEXICAL_SOURCES],
    ["peneira", "Deixa os finos passar e segura os maiores", "Utensílio perfurado usado para separar partículas.", "association", 2, 5, ["cozinha", "utensilios"], LEXICAL_SOURCES],
    ["ralador", "Transforma o queijo em fios ou farelos", "Utensílio de superfície áspera usado para reduzir alimentos.", "association", 1, 5, ["cozinha", "utensilios"], LEXICAL_SOURCES],
    ["concha", "Colher funda que mergulha na sopa", "Utensílio de cabo longo usado para servir líquidos.", "association", 2, 5, ["cozinha", "talheres"], LEXICAL_SOURCES],
    ["espátula", "Vira o hambúrguer sem usar a mão", "Utensílio de lâmina larga usado para mexer ou virar alimentos.", "association", 2, 5, ["cozinha", "utensilios"], LEXICAL_SOURCES],
    ["avental", "Escudo de tecido contra respingos", "Peça usada sobre a roupa para protegê-la durante tarefas.", "association", 1, 5, ["cozinha", "roupa"], LEXICAL_SOURCES],
    ["guardanapo", "A pausa da boca durante a refeição", "Pedaço de papel ou tecido usado para limpar os lábios.", "association", 2, 5, ["cozinha", "mesa"], LEXICAL_SOURCES],
    ["fogão", "Quatro bocas que alimentam a casa?", "Aparelho com queimadores usado para preparar comida.", "wordplay", 2, 5, ["cozinha", "eletrodomesticos"], LEXICAL_SOURCES],
    ["forno", "Calor fechado para assar", "Compartimento aquecido onde se assam alimentos.", "elliptical", 1, 5, ["cozinha", "eletrodomesticos"], LEXICAL_SOURCES],
    ["geladeira", "Armário que trabalha no frio?", "Eletrodoméstico que conserva alimentos em baixa temperatura.", "wordplay", 2, 5, ["cozinha", "eletrodomesticos"], LEXICAL_SOURCES],
    ["tábua", "Base do corte que poupa a bancada", "Peça plana usada como apoio para cortar alimentos.", "association", 2, 5, ["cozinha", "utensilios"], LEXICAL_SOURCES],

    // Alimentos, refeições e compras (25)
    ["abacaxi", "Fruta de coroa e armadura?", "Fruto tropical de casca áspera e polpa amarela.", "wordplay", 2, 5, ["alimentos", "frutas"], LEXICAL_SOURCES],
    ["almoço", "A refeição que divide o expediente", "Refeição principal feita perto do meio do dia.", "association", 2, 5, ["alimentos", "refeicoes"], LEXICAL_SOURCES],
    ["feira", "Compras ao ar livre, banca por banca", "Mercado periódico formado por vendedores em barracas.", "elliptical", 1, 5, ["compras", "cidade"], LEXICAL_SOURCES],
    ["mercado", "Carrinho cheio, despensa abastecida", "Estabelecimento que vende alimentos e itens domésticos.", "association", 2, 5, ["compras", "servicos"], LEXICAL_SOURCES],
    ["pipoca", "Milho que a panela faz pular", "Grão de milho estourado pelo calor.", "association", 2, 5, ["alimentos", "lanches"], LEXICAL_SOURCES],
    ["pão", "Companheiro de chapa da manteiga", "Alimento assado feito basicamente de farinha e água.", "association", 2, 5, ["alimentos", "padaria"], LEXICAL_SOURCES],
    ["arroz", "Grão branco que faz dupla com o feijão", "Cereal cozido muito presente nas refeições brasileiras.", "association", 1, 5, ["alimentos", "refeicoes"], LEXICAL_SOURCES],
    ["feijão", "Metade escura de uma dupla brasileira no prato", "Grão comestível geralmente servido com caldo.", "association", 2, 5, ["alimentos", "refeicoes"], LEXICAL_SOURCES],
    ["leite", "Vai da caixa ao copo ou ao café", "Líquido branco consumido como bebida e ingrediente.", "association", 2, 5, ["alimentos", "bebidas"], LEXICAL_SOURCES],
    ["café", "___ da manhã, primeira refeição do dia", "Bebida escura e estimulante feita de grãos torrados.", "fill-blank", 1, 5, ["alimentos", "bebidas"], LEXICAL_SOURCES],
    ["chá", "Folhas em infusão dentro da xícara", "Bebida preparada ao deixar ervas em água quente.", "elliptical", 1, 5, ["alimentos", "bebidas"], LEXICAL_SOURCES],
    ["suco", "Fruta que cabe no copo?", "Bebida obtida ao espremer ou processar frutos.", "wordplay", 2, 5, ["alimentos", "bebidas"], LEXICAL_SOURCES],
    ["bolo", "Cereja do ___, na expressão", "Massa doce assada, comum em aniversários.", "fill-blank", 1, 5, ["alimentos", "doces"], LEXICAL_SOURCES],
    ["queijo", "O leite depois de ganhar forma", "Alimento sólido produzido pela coagulação do leite.", "association", 2, 5, ["alimentos", "laticinios"], LEXICAL_SOURCES],
    ["ovo", "Casca por fora, clara e gema por dentro", "Alimento oval produzido por aves.", "elliptical", 1, 5, ["alimentos", "ingredientes"], LEXICAL_SOURCES],
    ["fruta", "Do pomar direto para a fruteira", "Parte comestível de uma planta, muitas vezes doce.", "association", 1, 5, ["alimentos", "hortifruti"], LEXICAL_SOURCES],
    ["legume", "Habitante comum da gaveta de verduras", "Vegetal culinário como cenoura, abobrinha ou chuchu.", "association", 2, 5, ["alimentos", "hortifruti"], LEXICAL_SOURCES],
    ["verdura", "Folhas que costumam chegar à salada", "Folha ou talo comestível, como alface ou couve.", "association", 1, 5, ["alimentos", "hortifruti"], LEXICAL_SOURCES],
    ["salada", "Mistura fresca servida antes ou ao lado do prato", "Preparação de vegetais crus ou cozidos combinados.", "association", 1, 5, ["alimentos", "refeicoes"], LEXICAL_SOURCES],
    ["sopa", "Refeição que se toma de colher", "Preparação líquida servida quente ou fria.", "association", 1, 5, ["alimentos", "refeicoes"], LEXICAL_SOURCES],
    ["molho", "Cobertura que dá sabor e umidade ao prato", "Preparação líquida ou cremosa servida com alimentos.", "association", 2, 5, ["alimentos", "preparo"], LEXICAL_SOURCES],
    ["tempero", "Pequeno acréscimo, grande mudança de sabor", "Ingrediente usado para realçar o gosto da comida.", "association", 2, 5, ["alimentos", "ingredientes"], LEXICAL_SOURCES],
    ["açúcar", "Doçura em cristais", "Substância doce usada em bebidas e receitas.", "elliptical", 1, 5, ["alimentos", "ingredientes"], LEXICAL_SOURCES],
    ["manteiga", "Derrete sobre o pão quente", "Produto gorduroso feito ao bater creme de leite.", "association", 1, 5, ["alimentos", "ingredientes"], LEXICAL_SOURCES],
    ["farinha", "Pó que pode virar pão, bolo ou massa", "Ingrediente moído feito de cereais ou outras plantas.", "association", 1, 5, ["alimentos", "ingredientes"], LEXICAL_SOURCES],

    // Roupas e acessórios (25)
    ["camiseta", "Uniforme informal dos dias quentes", "Peça leve que cobre o tronco e costuma ter mangas curtas.", "association", 2, 5, ["roupas", "vestuario"], LEXICAL_SOURCES],
    ["sapato", "Proteção dos pés que vem aos pares", "Calçado fechado usado para caminhar.", "association", 2, 5, ["roupas", "calcados"], LEXICAL_SOURCES],
    ["zíper", "Fecho que corre sobre dentes", "Sistema de duas fileiras unidas por um cursor.", "association", 2, 5, ["roupas", "fechos"], LEXICAL_SOURCES],
    ["camisa", "Peça de botões que pode ter colarinho", "Roupa para o tronco, geralmente aberta na frente.", "association", 2, 5, ["roupas", "vestuario"], LEXICAL_SOURCES],
    ["calça", "Duas pernas de tecido numa só peça", "Roupa que cobre separadamente cada perna até abaixo do joelho.", "elliptical", 1, 5, ["roupas", "vestuario"], LEXICAL_SOURCES],
    ["bermuda", "Calça que termina antes dos joelhos", "Peça curta que cobre a cintura e parte das pernas.", "association", 1, 5, ["roupas", "vestuario"], LEXICAL_SOURCES],
    ["saia", "Roupa que dá a volta na cintura", "Peça sem divisão entre as pernas, presa à cintura.", "association", 1, 5, ["roupas", "vestuario"], LEXICAL_SOURCES],
    ["vestido", "Uma peça só, do tronco à saia", "Roupa de uma só parte que desce dos ombros sobre as pernas.", "elliptical", 1, 5, ["roupas", "vestuario"], LEXICAL_SOURCES],
    ["casaco", "Camada que sai do armário quando esfria", "Peça externa usada sobre outras roupas para aquecer.", "association", 2, 5, ["roupas", "frio"], LEXICAL_SOURCES],
    ["meia", "Vai dentro do calçado e costuma perder o par", "Peça de tecido que cobre o pé e parte da perna.", "association", 2, 5, ["roupas", "vestuario"], LEXICAL_SOURCES],
    ["tênis", "Calçado que saiu das quadras para as ruas", "Peça esportiva de sola flexível usada nos pés.", "trivia", 1, 5, ["roupas", "calcados"], LEXICAL_SOURCES],
    ["chinelo", "Calçado aberto que anuncia passos pela casa", "Peça leve, sem cobertura no calcanhar, usada nos pés.", "association", 1, 5, ["roupas", "calcados"], LEXICAL_SOURCES],
    ["bota", "Calçado que sobe pelo tornozelo", "Peça fechada que cobre o pé e parte da perna.", "elliptical", 1, 5, ["roupas", "calcados"], LEXICAL_SOURCES],
    ["boné", "Aba que faz sombra no rosto", "Cobertura de tecido para a cabeça, com viseira.", "association", 1, 5, ["roupas", "acessorios"], LEXICAL_SOURCES],
    ["chapéu", "Cobertura da cabeça com copa e aba", "Acessório usado sobre a cabeça para proteção ou enfeite.", "elliptical", 1, 5, ["roupas", "acessorios"], LEXICAL_SOURCES],
    ["cinto", "Dá uma volta na cintura para segurar a calça", "Faixa com fivela usada ao redor da cintura.", "association", 1, 5, ["roupas", "acessorios"], LEXICAL_SOURCES],
    ["bolso", "Pequeno depósito costurado na roupa", "Compartimento de tecido para carregar objetos junto ao corpo.", "association", 1, 5, ["roupas", "vestuario"], LEXICAL_SOURCES],
    ["botão", "Fecha a camisa atravessando uma casa", "Peça pequena que se encaixa numa abertura da roupa.", "association", 1, 5, ["roupas", "fechos"], LEXICAL_SOURCES],
    ["cadarço", "Laço que mantém o tênis no pé", "Cordão passado por furos para ajustar um calçado.", "association", 1, 5, ["roupas", "calcados"], LEXICAL_SOURCES],
    ["pijama", "Roupa com expediente noturno?", "Conjunto confortável usado para dormir.", "wordplay", 2, 5, ["roupas", "sono"], LEXICAL_SOURCES],
    ["cueca", "Roupa íntima de corte tradicionalmente masculino", "Peça íntima de modelagem masculina usada entre a cintura e as coxas.", "elliptical", 1, 5, ["roupas", "intimas"], LEXICAL_SOURCES],
    ["calcinha", "Roupa íntima de corte tradicionalmente feminino", "Peça íntima de modelagem feminina usada entre a cintura e a virilha.", "elliptical", 1, 5, ["roupas", "intimas"], LEXICAL_SOURCES],
    ["sutiã", "Sustentação usada sob a blusa", "Peça íntima feminina que apoia os seios.", "elliptical", 1, 5, ["roupas", "intimas"], LEXICAL_SOURCES],
    ["gravata", "Faixa formal que termina em nó no colarinho", "Acessório comprido usado ao redor do pescoço com camisa social.", "association", 2, 5, ["roupas", "acessorios"], LEXICAL_SOURCES],
    ["uniforme", "___ escolar ou profissional", "Vestuário padronizado de uma escola ou profissão.", "fill-blank", 1, 5, ["roupas", "trabalho"], LEXICAL_SOURCES],

    // Quarto, banho e limpeza (25)
    ["fronha", "A roupa do travesseiro", "Capa de tecido que envolve o apoio da cabeça na cama.", "association", 1, 5, ["casa", "roupa-de-cama"], LEXICAL_SOURCES],
    ["chuveiro", "Chuva particular dentro do banheiro?", "Aparelho que lança água para o banho.", "wordplay", 2, 5, ["casa", "banho"], LEXICAL_SOURCES],
    ["cama", "Móvel onde o dia termina", "Estrutura usada para deitar e dormir.", "association", 1, 5, ["casa", "quarto"], LEXICAL_SOURCES],
    ["colchão", "A parte macia entre a cama e o sono", "Peça acolchoada sobre a qual se deita.", "association", 1, 5, ["casa", "quarto"], LEXICAL_SOURCES],
    ["travesseiro", "Companhia da cabeça durante a noite", "Almofada comprida usada para apoiar a cabeça ao dormir.", "association", 1, 5, ["casa", "quarto"], LEXICAL_SOURCES],
    ["lençol", "Tecido que cobre o colchão ou quem dorme", "Peça ampla e fina da roupa de cama.", "elliptical", 1, 5, ["casa", "roupa-de-cama"], LEXICAL_SOURCES],
    ["cobertor", "Calor guardado para a hora de dormir", "Peça grossa usada sobre o corpo na cama.", "association", 1, 5, ["casa", "roupa-de-cama"], LEXICAL_SOURCES],
    ["edredom", "Coberta que traz o enchimento junto", "Peça acolchoada e quente usada sobre a cama.", "association", 2, 5, ["casa", "roupa-de-cama"], LEXICAL_SOURCES],
    ["toalha", "Jogar a ___: desistir", "Tecido absorvente retangular usado após o banho ou sobre a mesa.", "fill-blank", 1, 5, ["casa", "banho"], LEXICAL_SOURCES],
    ["sabonete", "Espuma perfumada do banho", "Produto sólido ou líquido usado para lavar a pele.", "association", 1, 5, ["higiene", "banho"], LEXICAL_SOURCES],
    ["xampu", "Faz espuma no cabelo", "Produto líquido usado para lavar os fios e o couro cabeludo.", "association", 1, 5, ["higiene", "banho"], LEXICAL_SOURCES],
    ["pente", "Uma fileira de dentes para o cabelo?", "Objeto dentado usado para desembaraçar e arrumar os fios.", "wordplay", 2, 5, ["higiene", "cabelo"], LEXICAL_SOURCES],
    ["escova", "Muitas cerdas trabalhando juntas", "Utensílio com cerdas usado para limpar ou pentear.", "association", 1, 5, ["higiene", "limpeza"], LEXICAL_SOURCES],
    ["espelho", "Devolve o olhar sem dizer nada", "Superfície que reflete a imagem de quem está diante dela.", "association", 2, 5, ["casa", "banho"], LEXICAL_SOURCES],
    ["vaso", "Trono informal do banheiro?", "Peça sanitária usada para receber dejetos.", "wordplay", 2, 5, ["casa", "banho"], LEXICAL_SOURCES],
    ["descarga", "Leva embora o que ficou no vaso", "Mecanismo que libera água para limpar a peça sanitária.", "association", 2, 5, ["casa", "banho"], LEXICAL_SOURCES],
    ["ralo", "Saída da água pelo chão", "Abertura com grade por onde líquidos escoam.", "elliptical", 2, 5, ["casa", "limpeza"], LEXICAL_SOURCES],
    ["balde", "Recipiente que carrega água pela alça", "Vasilha funda, geralmente cilíndrica, com uma asa móvel.", "association", 2, 5, ["casa", "limpeza"], LEXICAL_SOURCES],
    ["vassoura", "Cerdas que empurram a sujeira pelo chão", "Utensílio de cabo longo usado para varrer.", "association", 1, 5, ["casa", "limpeza"], LEXICAL_SOURCES],
    ["rodo", "Puxa a água do piso para o ralo", "Utensílio com lâmina de borracha usado para secar o chão.", "association", 1, 5, ["casa", "limpeza"], LEXICAL_SOURCES],
    ["pano", "Quadrado de tecido promovido a faxineiro?", "Retalho usado para limpar, secar ou tirar pó.", "wordplay", 3, 5, ["casa", "limpeza"], LEXICAL_SOURCES],
    ["esponja", "Lava a louça com um lado macio e outro áspero", "Material poroso usado para esfregar e absorver líquidos.", "association", 1, 5, ["casa", "limpeza"], LEXICAL_SOURCES],
    ["sabão", "Espuma que enfrenta roupa ou louça suja", "Produto de limpeza feito para remover gordura e sujeira.", "association", 1, 5, ["casa", "limpeza"], LEXICAL_SOURCES],
    ["varal", "Linha de chegada da roupa lavada?", "Estrutura de fios onde peças úmidas são penduradas para secar.", "wordplay", 2, 5, ["casa", "lavanderia"], LEXICAL_SOURCES],
    ["pregador", "Prende a roupa sem fazer sermão?", "Pequena pinça usada para fixar peças no varal.", "wordplay", 3, 5, ["casa", "lavanderia"], LEXICAL_SOURCES],

    // Ferramentas, consertos e trabalho manual (25)
    ["alicate", "Mandíbulas de metal movidas pela mão", "Ferramenta articulada usada para segurar peças ou cortar fios.", "association", 2, 5, ["ferramentas", "reparo"], LEXICAL_SOURCES],
    ["lixa", "Aspereza usada para deixar liso", "Material abrasivo empregado para desgastar ou polir superfícies.", "association", 2, 5, ["ferramentas", "reparo"], LEXICAL_SOURCES],
    ["martelo", "Dá a palavra final ao prego?", "Ferramenta de cabeça pesada usada para bater.", "wordplay", 2, 5, ["ferramentas", "reparo"], LEXICAL_SOURCES],
    ["prego", "Entra na madeira sob pressão do martelo", "Haste metálica pontuda usada para fixar peças.", "association", 2, 5, ["ferramentas", "fixacao"], LEXICAL_SOURCES],
    ["parafuso", "Fixador que avança dando voltas", "Peça roscada apertada com uma chave apropriada.", "association", 2, 5, ["ferramentas", "fixacao"], LEXICAL_SOURCES],
    ["porca", "Parceira rosqueada do parafuso", "Peça com furo interno helicoidal usada numa fixação.", "association", 2, 5, ["ferramentas", "fixacao"], LEXICAL_SOURCES],
    ["chave", "___ de fenda ou inglesa", "Ferramenta manual usada para girar peças de fixação.", "fill-blank", 1, 5, ["ferramentas", "reparo"], LEXICAL_SOURCES],
    ["serrote", "Dentes que atravessam madeira", "Ferramenta de lâmina dentada movida à mão.", "association", 2, 5, ["ferramentas", "corte"], LEXICAL_SOURCES],
    ["furadeira", "Motor que põe a broca para girar", "Ferramenta elétrica usada para abrir furos.", "association", 2, 5, ["ferramentas", "reparo"], LEXICAL_SOURCES],
    ["broca", "Ponta giratória que abre caminho na parede", "Peça cortante encaixada numa ferramenta de perfuração.", "association", 2, 5, ["ferramentas", "reparo"], LEXICAL_SOURCES],
    ["trena", "Fita que sai da caixa para medir", "Instrumento retrátil marcado com unidades de comprimento.", "association", 2, 5, ["ferramentas", "medicao"], LEXICAL_SOURCES],
    ["régua", "Trinta centímetros comuns no estojo", "Instrumento reto e graduado usado para medir ou traçar linhas.", "trivia", 1, 5, ["ferramentas", "medicao"], LEXICAL_SOURCES],
    ["nível", "Denuncia quando a prateleira está torta", "Instrumento que verifica alinhamento horizontal ou vertical.", "association", 2, 4, ["ferramentas", "medicao"], LEXICAL_SOURCES],
    ["fita", "Faixa que cola, amarra ou mede, conforme o tipo", "Tira longa e estreita de material flexível.", "association", 2, 5, ["ferramentas", "materiais"], LEXICAL_SOURCES],
    ["cola", "Faz duas superfícies permanecerem juntas", "Substância adesiva usada para unir materiais.", "association", 1, 5, ["ferramentas", "materiais"], LEXICAL_SOURCES],
    ["tesoura", "Duas lâminas que cortam ao se encontrar", "Instrumento articulado usado para recortar.", "association", 1, 5, ["ferramentas", "corte"], LEXICAL_SOURCES],
    ["agulha", "Abre para a linha um caminho no tecido", "Haste fina e pontuda, com orifício, usada na costura.", "association", 2, 5, ["costura", "ferramentas"], LEXICAL_SOURCES],
    ["linha", "Passa pelo buraco da agulha", "Material de costura vendido em carretel e passado pela agulha.", "association", 1, 5, ["costura", "materiais"], LEXICAL_SOURCES],
    ["enxada", "Lâmina de cabo longo que revolve a terra", "Ferramenta manual usada para capinar e cavar o solo.", "elliptical", 2, 5, ["jardim", "ferramentas"], LEXICAL_SOURCES],
    ["foice", "Uma lua de metal que corta capim?", "Ferramenta de lâmina curva usada para ceifar plantas.", "wordplay", 2, 4, ["jardim", "ferramentas"], LEXICAL_SOURCES],
    ["ancinho", "Pente de cabo longo para o jardim?", "Ferramenta dentada usada para juntar folhas ou nivelar terra.", "wordplay", 3, 4, ["jardim", "ferramentas"], LEXICAL_SOURCES],
    ["mangueira", "Leva a torneira para passear pelo quintal?", "Tubo flexível usado para conduzir água.", "wordplay", 3, 5, ["jardim", "ferramentas"], LEXICAL_SOURCES],
    ["corda", "Muitos fios torcidos para puxar ou amarrar", "Feixe resistente e flexível usado em nós e tração.", "elliptical", 1, 5, ["materiais", "ferramentas"], LEXICAL_SOURCES],
    ["cadeado", "Fechadura que viaja com o objeto", "Trava portátil aberta por chave ou segredo.", "association", 2, 5, ["seguranca", "objetos"], LEXICAL_SOURCES],
    ["lanterna", "Luz de bolso para quando falta luz", "Aparelho portátil que projeta um feixe luminoso.", "association", 1, 5, ["ferramentas", "eletricidade"], LEXICAL_SOURCES],

    // Objetos pessoais, papelaria e organização (25)
    ["agenda", "Onde o futuro vira compromisso escrito", "Caderno ou aplicativo usado para organizar datas e tarefas.", "association", 2, 5, ["objetos", "organizacao"], LEXICAL_SOURCES],
    ["carteira", "Casa de bolso para dinheiro e documentos", "Objeto dobrável usado para guardar cartões e notas.", "association", 2, 5, ["objetos", "pessoais"], LEXICAL_SOURCES],
    ["mochila", "Bagagem que pega carona nas costas", "Bolsa com duas alças usada atrás do corpo.", "association", 2, 5, ["objetos", "pessoais"], LEXICAL_SOURCES],
    ["bolsa", "Carrega pequenos pertences pela alça", "Acessório flexível, com alças e fecho, para objetos pessoais.", "association", 2, 5, ["objetos", "pessoais"], LEXICAL_SOURCES],
    ["mala", "Armário portátil de viagem?", "Bagagem rígida ou flexível usada para levar roupas.", "wordplay", 2, 5, ["objetos", "viagem"], LEXICAL_SOURCES],
    ["chaveiro", "Argola que impede as chaves de se dispersarem", "Objeto que mantém várias chaves reunidas.", "association", 1, 5, ["objetos", "pessoais"], LEXICAL_SOURCES],
    ["relógio", "Contador de horas no pulso ou na parede", "Instrumento que indica o horário.", "association", 1, 5, ["objetos", "tempo"], LEXICAL_SOURCES],
    ["óculos", "Duas lentes apoiadas no rosto", "Armação usada diante dos olhos para corrigir ou proteger a visão.", "elliptical", 1, 5, ["objetos", "pessoais"], LEXICAL_SOURCES],
    ["guarda-chuva", "Teto portátil dos dias molhados", "Acessório dobrável aberto sobre a cabeça contra a chuva.", "association", 1, 5, ["objetos", "clima"], LEXICAL_SOURCES],
    ["guarda-sol", "Sombra portátil fincada na areia", "Cobertura móvel usada para bloquear a luz solar.", "association", 2, 5, ["objetos", "lazer"], LEXICAL_SOURCES],
    ["caderno", "___ de anotações, sobre a mesa", "Conjunto de páginas de papel usado para escrever.", "fill-blank", 1, 5, ["papelaria", "estudo"], LEXICAL_SOURCES],
    ["livro", "Muitas páginas entre duas capas", "Obra escrita ou ilustrada reunida em folhas encadernadas.", "elliptical", 1, 5, ["papelaria", "leitura"], LEXICAL_SOURCES],
    ["lápis", "Escreve, mas aceita a borracha", "Instrumento de grafite envolto em madeira.", "association", 1, 5, ["papelaria", "escrita"], LEXICAL_SOURCES],
    ["caneta", "Deixa tinta por onde a ponta passa", "Instrumento tubular usado para escrever com tinta.", "association", 1, 5, ["papelaria", "escrita"], LEXICAL_SOURCES],
    ["borracha", "Faz o lápis voltar atrás?", "Material usado para apagar marcas de grafite.", "wordplay", 2, 5, ["papelaria", "escrita"], LEXICAL_SOURCES],
    ["estojo", "Garagem escolar de lápis e canetas?", "Pequeno recipiente que guarda material de escrita.", "wordplay", 2, 5, ["papelaria", "estudo"], LEXICAL_SOURCES],
    ["papel", "Folha que recebe tinta, dobra ou embrulho", "Material fino em folhas usado para escrever e embalar.", "association", 1, 5, ["papelaria", "materiais"], LEXICAL_SOURCES],
    ["envelope", "Roupa de papel de uma carta?", "Invólucro plano usado para guardar correspondência.", "wordplay", 2, 5, ["papelaria", "correspondencia"], LEXICAL_SOURCES],
    ["pasta", "Reúne documentos sem virar arquivo digital", "Capa ou recipiente usado para organizar papéis.", "association", 1, 5, ["papelaria", "organizacao"], LEXICAL_SOURCES],
    ["clipe", "Abraço de metal em algumas folhas?", "Pequena peça dobrada usada para prender papéis.", "wordplay", 3, 5, ["papelaria", "organizacao"], LEXICAL_SOURCES],
    ["grampeador", "Aperta para unir folhas com metal", "Aparelho que prende papéis usando pequenos grampos.", "association", 1, 5, ["papelaria", "escritorio"], LEXICAL_SOURCES],
    ["carimbo", "Assinatura de borracha e tinta", "Instrumento que imprime uma marca repetida sobre uma superfície.", "association", 2, 5, ["papelaria", "escritorio"], LEXICAL_SOURCES],
    ["etiqueta", "Pequeno pedaço que conta preço, nome ou cuidado", "Rótulo preso a um produto para informar algo.", "association", 1, 5, ["objetos", "compras"], LEXICAL_SOURCES],
    ["pacote", "Conteúdo embrulhado e pronto para entrega", "Volume envolvido em papel, plástico ou caixa.", "elliptical", 1, 5, ["objetos", "entrega"], LEXICAL_SOURCES],
    ["sacola", "Vai vazia à loja e volta carregada", "Bolsa simples usada para transportar compras.", "association", 1, 5, ["objetos", "compras"], LEXICAL_SOURCES],

    // Trabalho, escola e vida digital (25)
    ["crachá", "Nome e função pendurados no peito", "Cartão visível usado para identificar uma pessoa.", "elliptical", 1, 5, ["trabalho", "identificacao"], LEXICAL_SOURCES],
    ["escola", "Lugar onde a turma divide aula e recreio", "Instituição dedicada ao ensino de estudantes.", "association", 1, 5, ["estudo", "rotina"], LEXICAL_SOURCES],
    ["rascunho", "Texto que ainda pode mudar de ideia?", "Versão provisória feita antes do acabamento final.", "wordplay", 3, 5, ["escrita", "trabalho"], LEXICAL_SOURCES],
    ["trabalho", "Ocupa o expediente e paga as contas", "Atividade profissional realizada em troca de renda.", "association", 1, 5, ["profissao", "rotina"], LEXICAL_SOURCES],
    ["emprego", "Vaga que virou vínculo profissional", "Ocupação remunerada mantida por uma pessoa.", "association", 1, 5, ["profissao", "rotina"], LEXICAL_SOURCES],
    ["salário", "Valor que chega depois do mês trabalhado", "Pagamento periódico recebido por um empregado.", "association", 1, 5, ["trabalho", "dinheiro"], LEXICAL_SOURCES],
    ["reunião", "Quando as agendas encontram o mesmo horário", "Encontro de pessoas para discutir um assunto.", "association", 1, 5, ["trabalho", "comunicacao"], LEXICAL_SOURCES],
    ["tarefa", "Item da lista que pede execução", "Atividade determinada para ser realizada.", "association", 1, 5, ["trabalho", "organizacao"], LEXICAL_SOURCES],
    ["prazo", "Dentro do ___, sem atraso", "Período limite para concluir ou entregar algo.", "fill-blank", 1, 5, ["trabalho", "tempo"], LEXICAL_SOURCES],
    ["turno", "Fatia do dia reservada ao expediente", "Período em que uma equipe trabalha ou estuda.", "association", 2, 5, ["trabalho", "tempo"], LEXICAL_SOURCES],
    ["chefe", "Quem distribui tarefas e cobra resultados", "Pessoa que dirige uma equipe ou setor.", "association", 1, 5, ["trabalho", "pessoas"], LEXICAL_SOURCES],
    ["colega", "Divide a firma ou a turma, não a família", "Pessoa que estuda ou trabalha no mesmo lugar que outra.", "association", 1, 5, ["trabalho", "relacoes"], LEXICAL_SOURCES],
    ["cliente", "Chega com uma necessidade e pode sair com uma compra", "Pessoa que contrata um serviço ou compra em um estabelecimento.", "association", 1, 5, ["trabalho", "servicos"], LEXICAL_SOURCES],
    ["escritório", "Mesa, computador e expediente sob o mesmo teto", "Local destinado a atividades administrativas ou profissionais.", "elliptical", 1, 5, ["trabalho", "lugares"], LEXICAL_SOURCES],
    ["mesa", "Superfície onde o trabalho ou a refeição se apoia", "Móvel de tampo horizontal sustentado por pés ou base.", "association", 1, 5, ["trabalho", "moveis"], LEXICAL_SOURCES],
    ["cadeira", "Lugar individual à mesa", "Assento para uma pessoa, geralmente com encosto.", "elliptical", 1, 5, ["trabalho", "moveis"], LEXICAL_SOURCES],
    ["computador", "Máquina de muitas janelas e nenhuma cortina?", "Equipamento eletrônico que processa dados e executa programas.", "wordplay", 3, 5, ["tecnologia", "trabalho"], LEXICAL_SOURCES],
    ["teclado", "Letras enfileiradas para os dedos", "Conjunto de teclas usado para inserir dados num aparelho.", "association", 1, 5, ["tecnologia", "trabalho"], LEXICAL_SOURCES],
    ["mouse", "Rato de mesa que move uma seta?", "Dispositivo manual que controla o ponteiro do computador.", "wordplay", 2, 5, ["tecnologia", "trabalho"], LEXICAL_SOURCES],
    ["tela", "Onde o computador mostra seu trabalho", "Superfície eletrônica que exibe imagens e textos.", "association", 1, 5, ["tecnologia", "trabalho"], LEXICAL_SOURCES],
    ["senha", "Segredo solicitado antes da entrada", "Sequência reservada usada para confirmar acesso.", "association", 1, 5, ["tecnologia", "seguranca"], LEXICAL_SOURCES],
    ["planilha", "Linhas e colunas a serviço das contas", "Documento digital de células usado para organizar dados e cálculos.", "association", 2, 5, ["tecnologia", "organizacao"], LEXICAL_SOURCES],
    ["e-mail", "Carta que dispensa envelope e carteiro?", "Mensagem enviada entre endereços eletrônicos.", "wordplay", 2, 5, ["tecnologia", "comunicacao"], LEXICAL_SOURCES],
    ["aula", "Tempo em que uma turma aprende com alguém", "Período de ensino dedicado a uma matéria.", "association", 1, 5, ["estudo", "rotina"], LEXICAL_SOURCES],
    ["prova", "Perguntas valendo nota", "Avaliação usada para medir conhecimentos ou habilidades.", "elliptical", 1, 5, ["estudo", "avaliacao"], LEXICAL_SOURCES],

    // Cidade, serviços e deslocamentos (25)
    ["bicicleta", "Duas rodas movidas no pedal", "Veículo leve impulsionado pelas pernas do ciclista.", "association", 1, 5, ["cidade", "transporte"], LEXICAL_SOURCES],
    ["gorjeta", "Agradecimento que aumenta a conta", "Valor extra dado voluntariamente por um atendimento.", "association", 2, 5, ["servicos", "dinheiro"], LEXICAL_SOURCES],
    ["viagem", "Rotina deixada para trás por alguns quilômetros", "Deslocamento para um lugar distante do habitual.", "association", 1, 5, ["transporte", "lazer"], LEXICAL_SOURCES],
    ["carro", "Quatro rodas à procura de vaga", "Veículo particular movido por motor.", "association", 1, 5, ["cidade", "transporte"], LEXICAL_SOURCES],
    ["ônibus", "Transporte coletivo que segue uma linha", "Veículo grande que leva vários passageiros por uma rota.", "association", 1, 5, ["cidade", "transporte-publico"], LEXICAL_SOURCES],
    ["metrô", "Trem urbano que frequentemente passa por baixo", "Sistema ferroviário de transporte dentro de uma cidade.", "association", 1, 5, ["cidade", "transporte-publico"], LEXICAL_SOURCES],
    ["trem", "Vagões seguindo uns aos outros sobre trilhos", "Veículo ferroviário formado por locomotiva e carros ligados.", "elliptical", 1, 5, ["cidade", "transporte"], LEXICAL_SOURCES],
    ["táxi", "Carro que começa a corrida ao ligar o marcador da tarifa", "Automóvel identificado para transporte pago com tarifa por corrida.", "association", 1, 5, ["cidade", "transporte"], LEXICAL_SOURCES],
    ["moto", "Duas rodas e um propulsor entre elas", "Veículo motorizado de duas rodas conduzido com o piloto montado.", "elliptical", 1, 5, ["cidade", "transporte"], LEXICAL_SOURCES],
    ["van", "No meio do caminho entre carro e ônibus", "Veículo fechado usado para transportar pequenos grupos.", "association", 2, 5, ["cidade", "transporte"], LEXICAL_SOURCES],
    ["caminhão", "Leva carga onde o carro levaria passageiros", "Veículo grande destinado ao transporte de mercadorias.", "association", 1, 5, ["cidade", "transporte"], LEXICAL_SOURCES],
    ["rua", "Endereço por onde também passam carros", "Via urbana ladeada por casas e edifícios.", "association", 1, 5, ["cidade", "vias"], LEXICAL_SOURCES],
    ["avenida", "Rua de maior porte e trânsito", "Via urbana ampla, geralmente importante para a circulação.", "association", 1, 5, ["cidade", "vias"], LEXICAL_SOURCES],
    ["calçada", "Faixa da rua reservada aos passos", "Parte lateral de uma via destinada a pedestres.", "association", 1, 5, ["cidade", "vias"], LEXICAL_SOURCES],
    ["faixa", "Marca no asfalto que dá vez ao pedestre", "Sinalização pintada na via para organizar travessias ou tráfego.", "association", 2, 5, ["cidade", "vias"], LEXICAL_SOURCES],
    ["esquina", "Encontro de duas ruas", "Ponto onde duas vias se cruzam ou mudam de direção.", "elliptical", 1, 5, ["cidade", "vias"], LEXICAL_SOURCES],
    ["praça", "Sala de estar a céu aberto da cidade?", "Espaço público aberto destinado à convivência.", "wordplay", 3, 5, ["cidade", "lugares"], LEXICAL_SOURCES],
    ["ponte", "Caminho sustentado sobre o obstáculo", "Estrutura que permite atravessar rio, vale ou outra via.", "association", 1, 5, ["cidade", "vias"], LEXICAL_SOURCES],
    ["túnel", "Atalho que atravessa por dentro", "Passagem subterrânea ou aberta através de uma elevação.", "association", 2, 5, ["cidade", "vias"], LEXICAL_SOURCES],
    ["parada", "___ de ônibus, na calçada", "Local demarcado para embarque em transporte coletivo.", "fill-blank", 1, 5, ["cidade", "transporte-publico"], LEXICAL_SOURCES],
    ["posto", "___ de gasolina, à beira da via", "Estabelecimento que vende combustível para veículos.", "fill-blank", 1, 5, ["cidade", "servicos"], LEXICAL_SOURCES],
    ["farmácia", "Balcão entre a receita médica e o remédio", "Estabelecimento que vende medicamentos e produtos de saúde.", "association", 1, 5, ["cidade", "servicos"], LEXICAL_SOURCES],
    ["padaria", "Cheiro de pão no comércio da esquina", "Estabelecimento que produz ou vende pães e outros assados.", "association", 1, 5, ["cidade", "servicos"], LEXICAL_SOURCES],
    ["oficina", "Consultório de carros e máquinas?", "Local onde veículos ou equipamentos são consertados.", "wordplay", 3, 5, ["cidade", "servicos"], LEXICAL_SOURCES],
    ["passagem", "___ de ida e volta", "Nome dado ao bilhete ou ao valor pago por uma viagem.", "fill-blank", 1, 5, ["cidade", "transporte"], LEXICAL_SOURCES],

    // Relações, comunicação e tempo livre (25)
    ["amizade", "Laço que não precisa de parentesco", "Relação de afeto, confiança e companheirismo.", "association", 1, 5, ["relacoes", "convivencia"], LEXICAL_SOURCES],
    ["domingo", "Quando o despertador costuma ganhar folga", "Dia posterior ao sábado e anterior à segunda-feira.", "association", 1, 5, ["tempo", "rotina"], LEXICAL_SOURCES],
    ["família", "Parentesco, afeto e cuidado sob o mesmo nome", "Grupo de pessoas ligadas por parentesco ou vínculos de cuidado.", "association", 1, 5, ["relacoes", "convivencia"], LEXICAL_SOURCES],
    ["mutirão", "Muitas mãos para uma tarefa comum", "Trabalho coletivo organizado em benefício de um grupo.", "association", 2, 4, ["relacoes", "comunidade"], LEXICAL_SOURCES],
    ["sorriso", "Curva no rosto em momento feliz", "Expressão facial feita ao elevar os cantos da boca.", "association", 1, 5, ["relacoes", "expressoes"], LEXICAL_SOURCES],
    ["telefone", "Faz a voz chegar longe", "Aparelho usado para conversar à distância.", "association", 1, 5, ["comunicacao", "objetos"], LEXICAL_SOURCES],
    ["vizinho", "Mora perto, mesmo sem dividir a casa", "Pessoa que vive ao lado ou nas proximidades.", "association", 1, 5, ["relacoes", "comunidade"], LEXICAL_SOURCES],
    ["amigo", "Família escolhida, segundo o afeto", "Pessoa com quem se mantém afeição e confiança.", "association", 1, 5, ["relacoes", "convivencia"], LEXICAL_SOURCES],
    ["casal", "Dupla unida por relação amorosa", "Par de pessoas que mantém vínculo afetivo.", "elliptical", 1, 5, ["relacoes", "afetos"], LEXICAL_SOURCES],
    ["namoro", "Relação que pode começar com um encontro", "Vínculo amoroso entre duas pessoas.", "association", 1, 5, ["relacoes", "afetos"], LEXICAL_SOURCES],
    ["festa", "Reunião em que a alegria é convidada", "Celebração com pessoas, comida, música ou dança.", "association", 1, 5, ["relacoes", "lazer"], LEXICAL_SOURCES],
    ["convite", "Pedido que abre lugar na comemoração", "Mensagem que chama alguém para participar de algo.", "association", 1, 5, ["relacoes", "comunicacao"], LEXICAL_SOURCES],
    ["visita", "Chegada de quem não mora na casa", "Permanência temporária na companhia de outra pessoa.", "association", 1, 5, ["relacoes", "convivencia"], LEXICAL_SOURCES],
    ["conversa", "Troca em que cada fala espera escuta", "Comunicação oral entre duas ou mais pessoas.", "association", 1, 5, ["relacoes", "comunicacao"], LEXICAL_SOURCES],
    ["abraço", "Carinho dado com os braços", "Gesto de envolver alguém junto ao peito.", "association", 1, 5, ["relacoes", "afetos"], LEXICAL_SOURCES],
    ["beijo", "Carinho que encosta os lábios", "Toque dos lábios em alguém ou algo como gesto de afeto.", "association", 1, 5, ["relacoes", "afetos"], LEXICAL_SOURCES],
    ["ajuda", "Força emprestada a quem precisa", "Apoio oferecido para facilitar uma tarefa ou situação.", "association", 1, 5, ["relacoes", "cooperacao"], LEXICAL_SOURCES],
    ["favor", "Por ___, forma de iniciar um pedido", "Ato realizado para beneficiar outra pessoa.", "fill-blank", 1, 5, ["relacoes", "cooperacao"], LEXICAL_SOURCES],
    ["recado", "Mensagem curta deixada para depois", "Comunicação breve transmitida a alguém.", "association", 1, 5, ["comunicacao", "rotina"], LEXICAL_SOURCES],
    ["notícia", "Fato que vira informação para circular", "Relato recente divulgado ao público ou a alguém.", "association", 1, 5, ["comunicacao", "informacao"], LEXICAL_SOURCES],
    ["manhã", "Parte do dia que começa com o amanhecer", "Período entre o nascer do sol e o meio-dia.", "association", 1, 5, ["tempo", "rotina"], LEXICAL_SOURCES],
    ["tarde", "Depois do almoço, antes da noite", "Período que vai do meio-dia ao começo da noite.", "elliptical", 1, 5, ["tempo", "rotina"], LEXICAL_SOURCES],
    ["noite", "Quando o céu escurece e a casa acende", "Período entre o fim do dia e o amanhecer.", "association", 1, 5, ["tempo", "rotina"], LEXICAL_SOURCES],
    ["semana", "Fim de ___: sábado e domingo", "Período formado por sete dias consecutivos.", "fill-blank", 1, 5, ["tempo", "calendario"], LEXICAL_SOURCES],
    ["férias", "Pausa longa com data para voltar", "Período de descanso concedido entre etapas de trabalho ou estudo.", "association", 1, 5, ["tempo", "lazer"], LEXICAL_SOURCES],
  ],
} satisfies BiomeBundle;

export const cotidianoEntries = entriesFromBundle(cotidianoBundle);

// Auditoria: 250 registros (40 legados), 250 normalizações únicas, comprimentos 99/148/3
// (3–5/6–10/11–18), estilos 163/37/14/34/2 (assoc./elípt./lacuna/trocad./trivia) e 0 vazamentos.
