import { entriesFromBundle, type BiomeBundle } from "./shared.js";

const CINEMA_SOURCES = ["unitex-pb", "volp-abl", "ancine-glossario"] as const;
const MUSIC_SOURCES = ["unitex-pb", "volp-abl", "funarte-artes"] as const;
const LITERATURE_SOURCES = ["unitex-pb", "volp-abl", "bn-digital"] as const;
const COMICS_SOURCES = ["unitex-pb", "volp-abl", "loc-comics"] as const;
const GAME_SOURCES = ["unitex-pb", "volp-abl", "museum-play"] as const;
const WEB_SOURCES = ["unitex-pb", "volp-abl", "mdn-glossary"] as const;
const EMOJI_SOURCES = ["unitex-pb", "volp-abl", "unicode-emoji"] as const;

const culturaPopBundle = {
  biome: "cultura-pop",
  prefix: "pop",
  editorialSource: "curadoria-cruzaverso-cultura-pop-v3",
  sources: [
    {
      sourceId: "unitex-pb",
      title: "Unitex/GramLab — recursos linguísticos para Português do Brasil",
      url: "https://github.com/UnitexGramLab/unitex-lingua/tree/master/pt-BR",
      license: "LGPLLR",
      role: "lexical",
    },
    {
      sourceId: "volp-abl",
      title: "Vocabulário Ortográfico da Língua Portuguesa — Academia Brasileira de Letras",
      url: "https://www.academia.org.br/nossa-lingua/busca-no-vocabulario",
      license: "consulta oficial; conteúdo-fonte não reproduzido",
      role: "orthographic",
    },
    {
      sourceId: "ancine-glossario",
      title: "ANCINE — Glossário da atividade cinematográfica e audiovisual",
      url: "https://www.gov.br/ancine/pt-br/assuntos/noticias/ancine-lanca-glossario-de-termos-da-atividade-cinematografica-e-audiovisual-rio-de-janeiro-17-05-2005/",
      license: "conteúdo institucional; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "funarte-artes",
      title: "Funarte — áreas artísticas e missão institucional",
      url: "https://www.gov.br/funarte/pt-br/acesso-a-informacao-lai/institucional/institucional",
      license: "conteúdo institucional; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "bn-digital",
      title: "Fundação Biblioteca Nacional — BNDigital",
      url: "https://bndigital.bn.gov.br/",
      license: "Documentos em domínio público ou publicados com autorização; consulta factual",
      role: "factual",
    },
    {
      sourceId: "loc-comics",
      title: "Library of Congress — Comics and Cartoons Collections Policy",
      url: "https://www.loc.gov/acq/devpol/comics.pdf",
      license: "documento institucional; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "museum-play",
      title: "The Strong National Museum of Play — Video Game History Timeline",
      url: "https://www.museumofplay.org/video-game-history-timeline/",
      license: "Copyright The Strong; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "mdn-glossary",
      title: "MDN Web Docs — Glossary of Web Terms",
      url: "https://developer.mozilla.org/en-US/docs/Glossary",
      license: "CC BY-SA 2.5; usado apenas como referência factual",
      role: "factual",
    },
    {
      sourceId: "unicode-emoji",
      title: "Unicode Technical Standard #51 — Unicode Emoji",
      url: "https://www.unicode.org/reports/tr51/",
      license: "Copyright Unicode Consortium; consulta factual sem reprodução",
      role: "factual",
    },
  ],
  records: [
    // Cinema, produção e exibição (30)
    ["cinema", "A sala escurece para a história ganhar luz", "Arte e indústria de produzir e exibir obras audiovisuais.", "association", 1, 5, ["cinema", "audiovisual"], CINEMA_SOURCES],
    ["claquete", "Bate antes da cena, mas não aplaude?", "Placa articulada usada para identificar e sincronizar uma tomada audiovisual.", "wordplay", 2, 5, ["cinema", "producao"], CINEMA_SOURCES],
    ["documentário", "A realidade também pede montagem", "Obra audiovisual não ficcional sobre pessoas, fatos ou temas reais.", "association", 2, 5, ["cinema", "generos"], CINEMA_SOURCES],
    ["dublagem", "Outra voz, os mesmos lábios na tela", "Substituição das falas originais por vozes gravadas em outro idioma.", "association", 2, 5, ["cinema", "som"], CINEMA_SOURCES],
    ["roteiro", "Cenas e falas antes de virarem filme", "Texto que organiza ações, diálogos e situações de uma obra audiovisual.", "elliptical", 1, 5, ["cinema", "escrita"], CINEMA_SOURCES],
    ["filme", "História que corre em imagens projetadas", "Obra audiovisual formada por imagens em movimento.", "elliptical", 1, 5, ["cinema", "obra"], CINEMA_SOURCES],
    ["cena", "Vai do “ação” ao “corta”", "Trecho contínuo de uma obra audiovisual situado numa ação ou ambiente.", "association", 1, 5, ["cinema", "narrativa"], CINEMA_SOURCES],
    ["montagem", "Costura planos até nascer o ritmo da obra", "Organização e combinação dos trechos gravados de um audiovisual.", "association", 2, 5, ["cinema", "pos-producao"], CINEMA_SOURCES],
    ["edição", "Escolhe, corta e ordena o material gravado", "Processo de selecionar e combinar imagem e som numa obra.", "association", 1, 5, ["cinema", "pos-producao"], CINEMA_SOURCES],
    ["direção", "Comando criativo entre o texto e a tela", "Função responsável por orientar a realização artística de uma obra.", "elliptical", 2, 5, ["cinema", "producao"], CINEMA_SOURCES],
    ["diretor", "Diz “ação” e responde pela visão do filme", "Profissional que coordena as escolhas artísticas de uma produção audiovisual.", "association", 1, 5, ["cinema", "profissoes"], CINEMA_SOURCES],
    ["atriz", "___ principal, nome feminino no topo do elenco", "Mulher que representa um papel numa produção dramática.", "fill-blank", 1, 5, ["cinema", "profissoes"], CINEMA_SOURCES],
    ["ator", "___ principal, nome masculino no topo do elenco", "Homem que representa um personagem numa produção dramática.", "fill-blank", 1, 5, ["cinema", "profissoes"], CINEMA_SOURCES],
    ["elenco", "Todos os papéis diante da câmera", "Conjunto de intérpretes de uma produção artística.", "elliptical", 1, 5, ["cinema", "profissoes"], CINEMA_SOURCES],
    ["câmera", "Olho mecânico da filmagem?", "Aparelho usado para registrar imagens fixas ou em movimento.", "wordplay", 2, 5, ["cinema", "equipamento"], CINEMA_SOURCES],
    ["fotograma", "Um instante imóvel dentro do movimento", "Cada imagem individual que compõe uma sequência filmada.", "elliptical", 3, 4, ["cinema", "imagem"], CINEMA_SOURCES],
    ["cenário", "Lugar construído para a história morar", "Ambiente real ou criado em que uma cena é representada.", "elliptical", 2, 5, ["cinema", "producao"], CINEMA_SOURCES],
    ["figurino", "Guarda-roupa que revela o personagem", "Conjunto de roupas e acessórios concebido para uma produção.", "elliptical", 2, 5, ["cinema", "producao"], CINEMA_SOURCES],
    ["maquiagem", "Transformação que acontece antes do close", "Aplicação de produtos no rosto ou corpo para caracterizar intérpretes.", "elliptical", 1, 5, ["cinema", "producao"], CINEMA_SOURCES],
    ["efeito", "___ especial, façanha dos bastidores", "Recurso técnico usado para criar uma impressão visual ou sonora.", "fill-blank", 1, 5, ["cinema", "pos-producao"], CINEMA_SOURCES],
    ["crédito", "Nome na tela para quem trabalhou fora dela", "Menção que reconhece a participação de alguém numa obra.", "elliptical", 2, 5, ["cinema", "producao"], CINEMA_SOURCES],
    ["legenda", "Fala que chega escrita na parte de baixo", "Texto exibido na imagem para traduzir ou transcrever diálogos.", "association", 1, 5, ["cinema", "acessibilidade"], CINEMA_SOURCES],
    ["estreia", "Primeira vez diante do público", "Exibição ou apresentação pública inicial de uma obra.", "elliptical", 1, 5, ["cinema", "exibicao"], CINEMA_SOURCES],
    ["sessão", "Uma hora marcada para a tela grande", "Período programado de exibição de um filme numa sala.", "association", 1, 5, ["cinema", "exibicao"], CINEMA_SOURCES],
    ["projeção", "A luz leva a imagem até a tela", "Exibição de imagens ampliadas sobre uma superfície.", "association", 2, 5, ["cinema", "exibicao"], CINEMA_SOURCES],
    ["ingresso", "Papel ou código que abre a sala de exibição", "Comprovante que autoriza a entrada num espetáculo.", "elliptical", 1, 5, ["cinema", "exibicao"], CINEMA_SOURCES],
    ["curta", "___-metragem, obra para uma sessão breve", "Nome reduzido de uma obra cinematográfica de pequena duração.", "fill-blank", 2, 5, ["cinema", "formatos"], CINEMA_SOURCES],
    ["longa", "___-metragem, obra da sessão principal", "Nome reduzido de uma obra cinematográfica de duração extensa.", "fill-blank", 2, 5, ["cinema", "formatos"], CINEMA_SOURCES],
    ["animação", "Desenhos ou objetos convencidos a se mover?", "Técnica que cria movimento aparente a partir de imagens sucessivas.", "wordplay", 2, 5, ["cinema", "tecnica"], CINEMA_SOURCES],
    ["produtor", "Faz orçamento, equipe e filmagem caberem no mesmo projeto", "Profissional que organiza recursos e execução de uma produção audiovisual.", "association", 2, 5, ["cinema", "profissoes"], CINEMA_SOURCES],

    // Televisão, rádio e mídia falada (25)
    ["episódio", "Uma história inteira dentro de uma série maior", "Cada parte individual de uma obra seriada.", "elliptical", 1, 5, ["televisao", "series"], CINEMA_SOURCES],
    ["novela", "Muitos capítulos e um horário quase diário", "Narrativa televisiva longa exibida em capítulos frequentes.", "elliptical", 1, 5, ["televisao", "formatos"], CINEMA_SOURCES],
    ["seriado", "Os mesmos personagens de volta a cada semana", "Produção audiovisual organizada em episódios recorrentes.", "elliptical", 1, 5, ["televisao", "series"], CINEMA_SOURCES],
    ["podcast", "Programa que chega aos ouvidos sob demanda", "Produção sonora distribuída em episódios pela internet.", "association", 1, 5, ["audio", "internet"], WEB_SOURCES],
    ["streaming", "A mídia começa antes de terminar de chegar", "Transmissão contínua de áudio ou vídeo por uma rede.", "association", 2, 5, ["audiovisual", "internet"], WEB_SOURCES],
    ["televisão", "Janela eletrônica com canais?", "Meio audiovisual que transmite programas para aparelhos receptores.", "wordplay", 1, 5, ["televisao", "midia"], CINEMA_SOURCES],
    ["rádio", "A voz atravessa o ar sem levar imagem", "Meio de comunicação sonora transmitido por ondas ou pela internet.", "association", 1, 5, ["radio", "midia"], MUSIC_SOURCES],
    ["canal", "Número no controle e identidade na programação", "Faixa ou emissora pela qual conteúdo televisivo é transmitido.", "elliptical", 2, 5, ["televisao", "midia"], CINEMA_SOURCES],
    ["programa", "Conteúdo com horário reservado na grade", "Conteúdo de rádio ou televisão apresentado como unidade regular.", "elliptical", 1, 5, ["televisao", "radio"], CINEMA_SOURCES],
    ["grade", "Calendário diário de uma emissora", "Organização dos programas segundo horários de transmissão.", "association", 2, 5, ["televisao", "programacao"], CINEMA_SOURCES],
    ["âncora", "Mantém o telejornal firme entre as notícias?", "Apresentador principal que conduz um programa jornalístico.", "wordplay", 2, 5, ["televisao", "jornalismo"], CINEMA_SOURCES],
    ["locutor", "Voz profissional atrás do microfone", "Pessoa que apresenta ou anuncia conteúdo em rádio e outros meios.", "elliptical", 1, 5, ["radio", "profissoes"], MUSIC_SOURCES],
    ["vinheta", "Assinatura curta de som e imagem", "Trecho breve que identifica um programa, emissora ou quadro.", "elliptical", 2, 5, ["televisao", "radio"], CINEMA_SOURCES],
    ["intervalo", "Pausa do programa ocupada por anúncios", "Período que interrompe temporariamente uma transmissão.", "association", 1, 5, ["televisao", "programacao"], CINEMA_SOURCES],
    ["comercial", "Filme curto interessado em vender", "Anúncio audiovisual produzido para divulgar produto, serviço ou campanha.", "elliptical", 2, 5, ["televisao", "publicidade"], CINEMA_SOURCES],
    ["audiência", "Quem assiste — e também o número que mede?", "Público de uma transmissão ou medida de quantas pessoas a acompanham.", "wordplay", 2, 5, ["televisao", "publico"], CINEMA_SOURCES],
    ["transmissão", "Conteúdo viajando da emissora ao público", "Envio de som ou imagem para receptores distantes.", "elliptical", 2, 5, ["televisao", "radio"], CINEMA_SOURCES],
    ["ao vivo", "Sem gravação para corrigir depois", "Apresentado ao público no mesmo momento em que acontece.", "elliptical", 1, 5, ["televisao", "radio"], CINEMA_SOURCES],
    ["temporada", "Um conjunto de episódios antes da próxima pausa", "Grupo de episódios lançado como uma etapa de uma série.", "elliptical", 1, 5, ["televisao", "series"], CINEMA_SOURCES],
    ["capítulo", "A novela serve um por dia", "Cada divisão narrativa de uma novela ou obra escrita.", "association", 1, 5, ["televisao", "formatos"], CINEMA_SOURCES],
    ["minissérie", "Poucos episódios e final já previsto", "Produção seriada concebida com quantidade limitada de episódios.", "elliptical", 2, 5, ["televisao", "series"], CINEMA_SOURCES],
    ["reprise", "Programa que volta sem ser novo", "Nova exibição de conteúdo já transmitido anteriormente.", "elliptical", 1, 5, ["televisao", "programacao"], CINEMA_SOURCES],
    ["plateia", "Público sentado diante do palco ou estúdio", "Conjunto de espectadores presentes numa apresentação.", "elliptical", 1, 5, ["televisao", "publico"], MUSIC_SOURCES],
    ["entrevista", "Perguntas de um lado, respostas do outro", "Conversa conduzida para obter declarações ou informações de alguém.", "elliptical", 1, 5, ["televisao", "radio"], CINEMA_SOURCES],
    ["microfone", "Faz a voz entrar na transmissão", "Dispositivo que converte som em sinal elétrico ou digital.", "association", 1, 5, ["audio", "equipamento"], MUSIC_SOURCES],

    // Música e apresentação (35)
    ["acorde", "Notas que chegam juntas ao ouvido", "Conjunto de notas musicais soadas simultaneamente.", "elliptical", 2, 5, ["musica", "teoria-musical"], MUSIC_SOURCES],
    ["discografia", "Carreira contada lançamento por lançamento", "Relação organizada das gravações publicadas por um artista.", "association", 2, 4, ["musica", "gravacao"], MUSIC_SOURCES],
    ["karaokê", "O microfone passa para quem trouxe coragem", "Entretenimento de cantar sobre acompanhamento instrumental e letra exibida.", "association", 1, 5, ["musica", "lazer"], MUSIC_SOURCES],
    ["musical", "Quando a história resolve cantar?", "Obra dramática em que canções participam da narrativa.", "wordplay", 2, 5, ["musica", "teatro"], MUSIC_SOURCES],
    ["música", "Som organizado para ganhar ritmo e expressão", "Arte de combinar sons e silêncios no tempo.", "association", 1, 5, ["musica", "arte"], MUSIC_SOURCES],
    ["canção", "Melodia que encontrou palavras", "Composição musical feita para ser cantada.", "elliptical", 1, 5, ["musica", "composicao"], MUSIC_SOURCES],
    ["melodia", "Notas em fila que o ouvido reconhece", "Sequência organizada de sons percebida como uma linha musical.", "elliptical", 2, 5, ["musica", "teoria-musical"], MUSIC_SOURCES],
    ["harmonia", "O acordo entre sons que chegam juntos", "Organização das relações entre acordes numa composição.", "elliptical", 2, 5, ["musica", "teoria-musical"], MUSIC_SOURCES],
    ["ritmo", "Organiza batidas no relógio da música?", "Distribuição de durações, pulsos e acentos no tempo musical.", "wordplay", 2, 5, ["musica", "teoria-musical"], MUSIC_SOURCES],
    ["nota", "Dó, ré ou mi, por exemplo", "Símbolo ou som de altura musical determinada.", "trivia", 1, 5, ["musica", "teoria-musical"], MUSIC_SOURCES],
    ["tom", "Dá altura à nota e cor à conversa?", "Altura de um som ou centro de referência de uma composição.", "wordplay", 2, 5, ["musica", "teoria-musical"], MUSIC_SOURCES],
    ["voz", "Instrumento que já vem com o cantor?", "Som produzido pelo aparelho fonador humano.", "wordplay", 1, 5, ["musica", "canto"], MUSIC_SOURCES],
    ["coro", "Muitas vozes na mesma obra", "Conjunto de pessoas que cantam de forma coordenada.", "elliptical", 1, 5, ["musica", "canto"], MUSIC_SOURCES],
    ["dueto", "Canção dividida entre duas vozes", "Composição ou apresentação para dois intérpretes.", "elliptical", 1, 5, ["musica", "formacoes"], MUSIC_SOURCES],
    ["trio", "Grupo musical que não precisa de uma quarta cadeira", "Formação composta por três intérpretes.", "elliptical", 1, 5, ["musica", "formacoes"], MUSIC_SOURCES],
    ["banda", "Instrumentos reunidos sob o mesmo nome", "Grupo de músicos que se apresenta em conjunto.", "elliptical", 1, 5, ["musica", "formacoes"], MUSIC_SOURCES],
    ["orquestra", "Muitos instrumentos seguindo uma só batuta", "Grande conjunto instrumental dividido em famílias sonoras.", "elliptical", 1, 5, ["musica", "formacoes"], MUSIC_SOURCES],
    ["maestro", "A batuta aponta para ele e obedece a todos", "Profissional que conduz uma orquestra, coro ou conjunto.", "association", 2, 5, ["musica", "profissoes"], MUSIC_SOURCES],
    ["intérprete", "Dá voz ou instrumento à composição alheia", "Artista que executa uma obra musical ou representa um papel.", "association", 2, 5, ["musica", "profissoes"], MUSIC_SOURCES],
    ["álbum", "Várias faixas sob a mesma capa", "Conjunto de gravações musicais lançado como uma obra.", "elliptical", 1, 5, ["musica", "gravacao"], MUSIC_SOURCES],
    ["disco", "Suporte que já girou para a música tocar", "Suporte circular de gravação e, por extensão, um lançamento musical.", "elliptical", 1, 5, ["musica", "gravacao"], MUSIC_SOURCES],
    ["refrão", "___ da canção, trecho que sempre volta", "Trecho musical e verbal repetido ao longo de uma composição.", "fill-blank", 1, 5, ["musica", "composicao"], MUSIC_SOURCES],
    ["verso", "Uma linha da letra, antes da próxima", "Cada linha poética de uma canção ou poema.", "elliptical", 1, 5, ["musica", "composicao"], MUSIC_SOURCES],
    ["rima", "Quando finais de versos combinam pelo ouvido", "Repetição ou semelhança de sons em palavras de posições correspondentes.", "association", 1, 5, ["musica", "composicao"], MUSIC_SOURCES],
    ["letra", "Palavras que a melodia leva para cantar", "Texto verbal de uma canção.", "association", 1, 5, ["musica", "composicao"], MUSIC_SOURCES],
    ["partitura", "A música antes de ganhar som", "Representação escrita de uma composição musical.", "elliptical", 2, 5, ["musica", "notacao"], MUSIC_SOURCES],
    ["violão", "Seis cordas no colo do músico", "Instrumento acústico de cordas dedilhadas, com corpo oco.", "elliptical", 1, 5, ["musica", "instrumentos"], MUSIC_SOURCES],
    ["guitarra", "Cordas elétricas prontas para o amplificador", "Instrumento de cordas geralmente elétrico e tocado com os dedos ou palheta.", "association", 1, 5, ["musica", "instrumentos"], MUSIC_SOURCES],
    ["baixo", "Quatro cordas comuns nas frequências graves", "Instrumento que executa as notas graves de um conjunto popular.", "association", 2, 5, ["musica", "instrumentos"], MUSIC_SOURCES],
    ["bateria", "Pratos e tambores cercando um músico", "Conjunto de instrumentos de percussão tocado por uma pessoa.", "association", 1, 5, ["musica", "instrumentos"], MUSIC_SOURCES],
    ["piano", "Teclas que acionam cordas escondidas", "Instrumento de teclado em que martelos internos percutem cordas.", "association", 1, 5, ["musica", "instrumentos"], MUSIC_SOURCES],
    ["flauta", "Sopro que atravessa um tubo e vira melodia", "Instrumento de sopro em forma de tubo com orifícios.", "association", 1, 5, ["musica", "instrumentos"], MUSIC_SOURCES],
    ["saxofone", "Metal por fora, palheta no sopro", "Instrumento de sopro feito de metal e tocado com palheta simples.", "association", 2, 5, ["musica", "instrumentos"], MUSIC_SOURCES],
    ["palco", "Piso elevado onde o espetáculo acontece", "Espaço destinado à apresentação de artistas diante do público.", "elliptical", 1, 5, ["musica", "espetaculo"], MUSIC_SOURCES],
    ["show", "Música ao vivo diante da plateia", "Apresentação pública de música ou entretenimento.", "elliptical", 1, 5, ["musica", "espetaculo"], MUSIC_SOURCES],

    // Literatura popular e narrativa (30)
    ["aventura", "O perigo convida o protagonista a sair de casa", "Gênero narrativo centrado em jornadas, riscos e descobertas.", "association", 1, 5, ["literatura", "generos"], LITERATURE_SOURCES],
    ["detetive", "Segue pistas até o mistério perder o álibi", "Investigador, real ou fictício, que procura esclarecer um caso.", "association", 1, 5, ["literatura", "personagens"], LITERATURE_SOURCES],
    ["romance", "Narrativa longa que não precisa falar de amor?", "Obra ficcional extensa escrita em prosa.", "wordplay", 2, 5, ["literatura", "formatos"], LITERATURE_SOURCES],
    ["conto", "Ficção que chega ao fim em poucas páginas", "Narrativa literária breve, geralmente concentrada num conflito.", "association", 1, 5, ["literatura", "formatos"], LITERATURE_SOURCES],
    ["poema", "Versos reunidos como uma obra", "Composição literária construída com ritmo, imagens e linguagem poética.", "elliptical", 1, 5, ["literatura", "poesia"], LITERATURE_SOURCES],
    ["poesia", "A linguagem trabalhando além do sentido literal", "Arte literária que explora ritmo, som e múltiplos sentidos das palavras.", "association", 2, 5, ["literatura", "poesia"], LITERATURE_SOURCES],
    ["fábula", "Animais falam para a moral chegar ao leitor", "Narrativa breve, frequentemente com animais personificados e ensinamento final.", "association", 1, 5, ["literatura", "tradicao"], LITERATURE_SOURCES],
    ["lenda", "História que a tradição conta como se pudesse ter acontecido", "Narrativa tradicional ligada a lugares, pessoas ou fatos transformados pelo imaginário.", "association", 2, 5, ["literatura", "tradicao"], LITERATURE_SOURCES],
    ["mito", "Explica o mundo com deuses e símbolos", "Narrativa tradicional de caráter sagrado ou simbólico sobre origens e acontecimentos.", "association", 2, 5, ["literatura", "tradicao"], LITERATURE_SOURCES],
    ["biografia", "Uma vida contada por outra pessoa", "Narrativa da trajetória de alguém escrita por um autor diferente do retratado.", "association", 1, 5, ["literatura", "nao-ficcao"], LITERATURE_SOURCES],
    ["autobiografia", "Autor e personagem principal dividem o mesmo nome", "Relato que uma pessoa escreve sobre a própria vida.", "association", 2, 5, ["literatura", "nao-ficcao"], LITERATURE_SOURCES],
    ["autor", "Assina a obra antes de encontrar o leitor", "Pessoa responsável pela criação intelectual de um texto ou obra.", "association", 1, 5, ["literatura", "profissoes"], LITERATURE_SOURCES],
    ["narrador", "A voz que sabe como a história será contada", "Instância ficcional que relata os acontecimentos de uma narrativa.", "association", 2, 5, ["literatura", "narrativa"], LITERATURE_SOURCES],
    ["personagem", "Vive na história sem precisar existir fora dela", "Figura humana, animal ou imaginária que participa de uma narrativa.", "association", 1, 5, ["literatura", "narrativa"], LITERATURE_SOURCES],
    ["protagonista", "O enredo costuma seguir seus passos", "Figura central cujos objetivos conduzem a narrativa.", "association", 1, 5, ["literatura", "personagens"], LITERATURE_SOURCES],
    ["antagonista", "Faz oposição ao objetivo central da história", "Figura ou força que se contrapõe ao protagonista.", "association", 2, 5, ["literatura", "personagens"], LITERATURE_SOURCES],
    ["enredo", "Fio que amarra os acontecimentos", "Organização dos fatos e conflitos de uma narrativa.", "association", 1, 5, ["literatura", "narrativa"], LITERATURE_SOURCES],
    ["trama", "Rede de acontecimentos tecida pelo autor?", "Encadeamento de ações e conflitos de uma história.", "wordplay", 2, 5, ["literatura", "narrativa"], LITERATURE_SOURCES],
    ["parágrafo", "Bloco de frases entre dois recuos", "Unidade de texto formada por uma ou mais frases relacionadas.", "association", 1, 5, ["literatura", "escrita"], LITERATURE_SOURCES],
    ["prefácio", "Vem antes da obra para apresentá-la", "Texto introdutório colocado antes do corpo principal de um livro.", "association", 2, 4, ["literatura", "livro"], LITERATURE_SOURCES],
    ["epílogo", "A história termina, mas ele ainda tem algo a dizer", "Trecho final que mostra consequências ou encerra uma narrativa.", "association", 2, 4, ["literatura", "narrativa"], LITERATURE_SOURCES],
    ["prólogo", "Abre a história antes do primeiro capítulo", "Parte introdutória que antecede o desenvolvimento principal de uma obra.", "association", 2, 4, ["literatura", "narrativa"], LITERATURE_SOURCES],
    ["sinopse", "A obra inteira em poucas linhas", "Resumo breve que apresenta o conteúdo de um livro, filme ou programa.", "association", 1, 5, ["literatura", "divulgacao"], LITERATURE_SOURCES],
    ["capa", "Primeiro encontro do olhar com o livro", "Parte externa que protege e identifica uma publicação.", "association", 1, 5, ["literatura", "livro"], LITERATURE_SOURCES],
    ["editora", "Casa que prepara textos para encontrar leitores", "Empresa ou instituição que publica obras.", "association", 2, 5, ["literatura", "publicacao"], LITERATURE_SOURCES],
    ["livraria", "Prateleiras onde livros esperam compradores", "Estabelecimento dedicado à venda de publicações.", "association", 1, 5, ["literatura", "publicacao"], LITERATURE_SOURCES],
    ["biblioteca", "Acervo com porta aberta para leitores", "Instituição que organiza e oferece acesso a livros e outros documentos.", "association", 1, 5, ["literatura", "instituicoes"], LITERATURE_SOURCES],
    ["saga", "Uma história grande demais para uma aventura só", "Narrativa extensa que acompanha conflitos por várias etapas ou gerações.", "association", 2, 5, ["literatura", "formatos"], LITERATURE_SOURCES],
    ["mistério", "Pergunta que sustenta a história até a solução", "Gênero ou conflito narrativo baseado em algo oculto a esclarecer.", "association", 1, 5, ["literatura", "generos"], LITERATURE_SOURCES],
    ["ficção", "___ científica, gênero de futuros possíveis", "Narrativa criada pela imaginação, ainda que use elementos da realidade.", "fill-blank", 2, 5, ["literatura", "generos"], LITERATURE_SOURCES],

    // Quadrinhos, cartum e animação (30)
    ["anime", "Animação produzida no Japão, na acepção brasileira", "Nome dado, no Brasil, às obras de animação produzidas no Japão.", "trivia", 1, 5, ["quadrinhos", "animacao"], COMICS_SOURCES],
    ["mangá", "___ japonês, leitura em quadros que pode começar pelo outro lado", "Nome dado aos quadrinhos de tradição japonesa.", "fill-blank", 1, 5, ["quadrinhos", "japao"], COMICS_SOURCES],
    ["onomatopeia", "Som que virou palavra no meio do quadro", "Palavra que imita ou sugere um ruído, como “bum” e “toc”.", "association", 2, 5, ["quadrinhos", "linguagem"], COMICS_SOURCES],
    ["quadrinho", "História contada entre traços e balões", "Narrativa visual organizada em imagens sequenciais, geralmente acompanhadas de texto.", "association", 1, 5, ["quadrinhos", "formatos"], COMICS_SOURCES],
    ["tirinha", "Poucos quadros bastam para chegar à graça", "Sequência curta de quadrinhos, frequentemente humorística.", "association", 1, 5, ["quadrinhos", "formatos"], COMICS_SOURCES],
    ["cartum", "Desenho de humor que dispensa a notícia do dia", "Ilustração humorística geralmente compreensível sem contexto imediato.", "association", 2, 5, ["quadrinhos", "humor"], COMICS_SOURCES],
    ["charge", "O traço comenta o assunto do momento", "Desenho humorístico ou crítico ligado a um acontecimento reconhecível.", "association", 2, 5, ["quadrinhos", "humor"], COMICS_SOURCES],
    ["caricatura", "O retrato exagera para ficar mais parecido?", "Representação que acentua traços marcantes de uma pessoa ou figura.", "wordplay", 2, 5, ["quadrinhos", "desenho"], COMICS_SOURCES],
    ["balão", "Guarda a fala sem deixar o quadro flutuar?", "Forma gráfica que contém fala ou pensamento numa história em quadrinhos.", "wordplay", 1, 5, ["quadrinhos", "linguagem"], COMICS_SOURCES],
    ["requadro", "A moldura que separa um instante do seguinte", "Linha ou contorno que delimita uma imagem numa página de quadrinhos.", "association", 3, 4, ["quadrinhos", "linguagem"], COMICS_SOURCES],
    ["quadro", "Um instante da história cercado por linhas", "Cada unidade visual delimitada de uma sequência em quadrinhos.", "association", 1, 5, ["quadrinhos", "linguagem"], COMICS_SOURCES],
    ["página", "Vários quadros dividindo o mesmo papel", "Cada lado de uma folha numa publicação.", "elliptical", 1, 5, ["quadrinhos", "publicacao"], COMICS_SOURCES],
    ["gibi", "Revista que abre passagem para heróis desenhados", "Nome popular brasileiro para revista em quadrinhos.", "association", 1, 5, ["quadrinhos", "publicacao"], COMICS_SOURCES],
    ["desenhista", "Dá corpo aos personagens com lápis ou tela", "Profissional que produz os desenhos de uma obra visual.", "association", 1, 5, ["quadrinhos", "profissoes"], COMICS_SOURCES],
    ["roteirista", "Escreve o que o desenho ainda vai mostrar", "Profissional que cria a estrutura, as ações e as falas de uma narrativa visual.", "association", 2, 5, ["quadrinhos", "profissoes"], COMICS_SOURCES],
    ["colorista", "Põe luz e cor sobre os traços prontos", "Profissional responsável pelas cores de uma história em quadrinhos.", "association", 2, 4, ["quadrinhos", "profissoes"], COMICS_SOURCES],
    ["nanquim", "Tinta escura que firma o traço no papel", "Tinta preta de grande intensidade usada em desenho e ilustração.", "association", 2, 4, ["quadrinhos", "materiais"], COMICS_SOURCES],
    ["superpoder", "Talento impossível que cabe numa capa", "Habilidade extraordinária atribuída a personagens heroicos.", "association", 1, 5, ["quadrinhos", "personagens"], COMICS_SOURCES],
    ["coleção", "Números reunidos na estante sem perder a ordem", "Conjunto de publicações ou objetos agrupados segundo um critério.", "association", 1, 5, ["quadrinhos", "publicacao"], COMICS_SOURCES],
    ["almanaque", "Muitas histórias reunidas entre duas capas", "Publicação que compila textos, quadrinhos ou informações variadas.", "association", 2, 4, ["quadrinhos", "publicacao"], COMICS_SOURCES],
    ["desenho", "Linhas que aprendem a contar uma história", "Representação visual feita por traços sobre uma superfície.", "association", 1, 5, ["quadrinhos", "arte"], COMICS_SOURCES],
    ["cartunista", "Faz o humor caber num só desenho", "Artista que cria cartuns.", "association", 2, 4, ["quadrinhos", "profissoes"], COMICS_SOURCES],
    ["ilustrador", "Cria imagens para conversar com o texto", "Profissional que produz imagens para acompanhar ou interpretar uma obra.", "association", 1, 5, ["quadrinhos", "profissoes"], COMICS_SOURCES],
    ["ilustração", "Imagem que acompanha, explica ou amplia a leitura", "Representação visual criada para complementar um texto ou publicação.", "association", 1, 5, ["quadrinhos", "arte"], COMICS_SOURCES],
    ["esboço", "Primeiros traços antes da arte final", "Desenho inicial que registra a ideia geral de uma imagem.", "elliptical", 1, 5, ["quadrinhos", "processo"], COMICS_SOURCES],
    ["sarjeta", "Espaço vazio em que o leitor imagina o movimento", "Intervalo entre os quadros de uma página de quadrinhos.", "association", 3, 4, ["quadrinhos", "linguagem"], COMICS_SOURCES],
    ["traço", "Assinatura visual na ponta do lápis", "Linha característica que forma um desenho.", "association", 1, 5, ["quadrinhos", "arte"], COMICS_SOURCES],
    ["acetato", "Folha transparente dos desenhos animados tradicionais", "Lâmina transparente usada para pintar elementos de animação quadro a quadro.", "association", 3, 4, ["animacao", "tecnica"], COMICS_SOURCES],
    ["movimento", "Ilusão criada entre uma imagem e a próxima", "Mudança aparente de posição produzida por imagens sucessivas na animação.", "association", 2, 5, ["animacao", "tecnica"], COMICS_SOURCES],
    ["sequência", "Quadros ou cenas postos para avançar juntos", "Série ordenada de imagens ou acontecimentos narrativos.", "association", 2, 5, ["quadrinhos", "narrativa"], COMICS_SOURCES],

    // Jogos de mesa, lógica e videogame (35)
    ["arcade", "Máquina de ficha, tela e recorde", "Máquina pública de videogame, comum em salões de jogos.", "association", 2, 4, ["jogos", "videogame"], GAME_SOURCES],
    ["baralho", "Cinquenta e duas cartas na forma francesa tradicional", "Conjunto tradicional de cartas dividido em naipes.", "trivia", 1, 5, ["jogos", "cartas"], GAME_SOURCES],
    ["controle", "Comandos do jogador na palma das mãos", "Dispositivo usado para dar comandos a um videogame.", "association", 1, 5, ["jogos", "videogame"], GAME_SOURCES],
    ["pixel", "Menor quadradinho de uma imagem na tela", "Elemento mínimo de uma imagem digital matricial.", "association", 1, 5, ["jogos", "imagem-digital"], GAME_SOURCES],
    ["sudoku", "Nove por nove, sem repetir algarismos", "Passatempo lógico de completar uma grade com números sem repetições por linha, coluna e bloco.", "trivia", 1, 5, ["jogos", "logica"], GAME_SOURCES],
    ["tabuleiro", "Campo de disputa que cabe sobre a mesa", "Superfície marcada em que se movem peças de um jogo.", "association", 1, 5, ["jogos", "mesa"], GAME_SOURCES],
    ["videogame", "O jogador entra na ação pela tela", "Jogo eletrônico com imagens exibidas num dispositivo de vídeo.", "association", 1, 5, ["jogos", "eletronicos"], GAME_SOURCES],
    ["jogo", "Regras, objetivo e vontade de vencer", "Atividade estruturada por regras, desafios e um resultado possível.", "association", 1, 5, ["jogos", "conceitos"], GAME_SOURCES],
    ["jogador", "Move a peça ou aperta o botão", "Pessoa que participa de um jogo.", "association", 1, 5, ["jogos", "participantes"], GAME_SOURCES],
    ["partida", "Do começo ao resultado, uma disputa completa", "Cada realização completa de um jogo entre participantes.", "association", 1, 5, ["jogos", "conceitos"], GAME_SOURCES],
    ["fase", "Trecho vencido antes do próximo desafio", "Etapa de progressão num jogo eletrônico.", "association", 1, 5, ["jogos", "videogame"], GAME_SOURCES],
    ["placar", "Os pontos ficam à vista nele", "Registro visível do resultado ou da pontuação de uma disputa.", "association", 1, 5, ["jogos", "resultado"], GAME_SOURCES],
    ["pontuação", "Soma que transforma jogadas em resultado", "Quantidade de pontos obtida por um participante.", "association", 1, 5, ["jogos", "resultado"], GAME_SOURCES],
    ["peão", "Peça mais numerosa na abertura do xadrez", "Peça de menor valor no xadrez ou marcador movido em jogos de mesa.", "trivia", 1, 5, ["jogos", "pecas"], GAME_SOURCES],
    ["carta", "Tem frente reveladora e verso discreto", "Peça plana de um baralho, identificada por valor e naipe.", "association", 1, 5, ["jogos", "cartas"], GAME_SOURCES],
    ["naipe", "Família de cartas marcada por um símbolo", "Cada uma das categorias em que se divide um baralho.", "association", 2, 5, ["jogos", "cartas"], GAME_SOURCES],
    ["coringa", "Carta sem posto fixo no baralho", "Carta que pode assumir funções especiais ou substituir outras.", "association", 1, 5, ["jogos", "cartas"], GAME_SOURCES],
    ["rei", "No baralho, fica acima da dama", "Carta de figura que normalmente tem valor superior ao da dama.", "trivia", 1, 5, ["jogos", "cartas"], GAME_SOURCES],
    ["rainha", "Peça que domina linhas e diagonais", "Peça mais móvel do xadrez, capaz de avançar em várias direções.", "association", 1, 5, ["jogos", "xadrez"], GAME_SOURCES],
    ["torre", "Peça que corre reto pelo tabuleiro de xadrez", "Peça de xadrez que se move por linhas e colunas.", "trivia", 1, 5, ["jogos", "xadrez"], GAME_SOURCES],
    ["bispo", "Peça que cruza o xadrez sem sair da diagonal", "Peça de xadrez que se move somente pelas diagonais.", "trivia", 1, 5, ["jogos", "xadrez"], GAME_SOURCES],
    ["xadrez", "Jogo de ___, com reis ameaçados em 64 casas", "Jogo de estratégia para duas pessoas disputado num tabuleiro quadriculado.", "fill-blank", 1, 5, ["jogos", "tabuleiro"], GAME_SOURCES],
    ["damas", "Jogo em que peças saltam e são coroadas", "Jogo em que peças avançam na diagonal e capturam por salto.", "trivia", 1, 5, ["jogos", "tabuleiro"], GAME_SOURCES],
    ["dominó", "Peças retangulares se encontram pelos pontos", "Jogo de combinar peças divididas em duas pontas numeradas.", "association", 1, 5, ["jogos", "mesa"], GAME_SOURCES],
    ["truco", "Blefe e desafio valendo três", "Jogo de cartas popular no Brasil, marcado por apostas sucessivas sobre a rodada.", "association", 2, 5, ["jogos", "cartas"], GAME_SOURCES],
    ["pôquer", "Cartas, apostas e uma expressão indecifrável", "Família de jogos de cartas baseada em combinações e rodadas de aposta.", "association", 2, 5, ["jogos", "cartas"], GAME_SOURCES],
    ["roleta", "A sorte gira antes de escolher um número", "Jogo de aposta em que uma bola indica um compartimento numerado.", "association", 1, 5, ["jogos", "sorte"], GAME_SOURCES],
    ["bingo", "Números cantados até completar a cartela", "Jogo de sorte em que se marcam números sorteados numa cartela.", "association", 1, 5, ["jogos", "sorte"], GAME_SOURCES],
    ["quebra-cabeça", "Peças separadas procuram a mesma imagem", "Passatempo de montar uma figura ou resolver um problema por partes.", "association", 1, 5, ["jogos", "logica"], GAME_SOURCES],
    ["labirinto", "Muitos caminhos treinados para esconder a saída", "Rede de passagens em que se procura um percurso até a saída.", "association", 1, 5, ["jogos", "logica"], GAME_SOURCES],
    ["enigma", "Pergunta que prefere não entregar a resposta?", "Problema apresentado de forma obscura para ser decifrado.", "wordplay", 1, 5, ["jogos", "logica"], GAME_SOURCES],
    ["estratégia", "Plano feito antes que a próxima jogada cobre", "Organização de ações para alcançar um objetivo num jogo.", "association", 2, 5, ["jogos", "conceitos"], GAME_SOURCES],
    ["missão", "Objetivo que põe o personagem em movimento", "Tarefa ou conjunto de objetivos proposto ao jogador.", "association", 1, 5, ["jogos", "videogame"], GAME_SOURCES],
    ["console", "Aparelho que leva o jogo à tela", "Equipamento eletrônico dedicado principalmente a executar videogames.", "association", 1, 5, ["jogos", "videogame"], GAME_SOURCES],
    ["cartucho", "Jogo guardado numa peça que entra no aparelho", "Módulo removível que armazena software para certos videogames.", "association", 2, 5, ["jogos", "videogame"], GAME_SOURCES],

    // Internet, linguagem digital e comunidades (35)
    ["emoji", "Um rostinho pode ocupar o lugar da frase", "Símbolo pictográfico codificado para uso em mensagens digitais.", "association", 1, 5, ["internet", "linguagem-digital"], EMOJI_SOURCES],
    ["hashtag", "Cerquilha que transforma expressão em etiqueta", "Palavra ou expressão precedida de cerquilha para identificar um assunto nas redes.", "association", 1, 5, ["internet", "linguagem-digital"], WEB_SOURCES],
    ["meme", "A piada muda de legenda enquanto atravessa a rede", "Conteúdo cultural que circula, é imitado e ganha variações na internet.", "association", 1, 5, ["internet", "cultura-digital"], WEB_SOURCES],
    ["internet", "Rede das redes ao alcance de uma conexão", "Infraestrutura mundial que interliga redes de computadores.", "association", 1, 5, ["internet", "infraestrutura"], WEB_SOURCES],
    ["web", "Páginas ligadas por caminhos clicáveis", "Sistema de documentos e recursos interligados acessados pela internet.", "association", 1, 5, ["internet", "web"], WEB_SOURCES],
    ["site", "Endereço com páginas sob o mesmo teto digital?", "Conjunto de páginas e recursos publicados sob um domínio na web.", "wordplay", 1, 5, ["internet", "web"], WEB_SOURCES],
    ["blog", "Publicações em ordem de quem chegou por último", "Página ou site atualizado com textos ou outros conteúdos datados.", "association", 1, 5, ["internet", "publicacao"], WEB_SOURCES],
    ["rede", "Conexões que também aproximam perfis?", "Conjunto de sistemas interligados para trocar dados ou conteúdo.", "wordplay", 1, 5, ["internet", "infraestrutura"], WEB_SOURCES],
    ["link", "Clique que abre caminho para outro endereço", "Elemento que leva de um recurso digital a outro.", "association", 1, 5, ["internet", "navegacao"], WEB_SOURCES],
    ["hiperlink", "Ponte clicável entre documentos", "Ligação eletrônica que aponta para outra página, seção ou recurso.", "association", 2, 5, ["internet", "navegacao"], WEB_SOURCES],
    ["navegador", "Programa que abre janelas para a web", "Aplicativo usado para acessar e exibir páginas da web.", "association", 1, 5, ["internet", "software"], WEB_SOURCES],
    ["busca", "Pergunta digitada à procura de resultados", "Ação de localizar informações por meio de um sistema de pesquisa.", "association", 1, 5, ["internet", "navegacao"], WEB_SOURCES],
    ["perfil", "Foto de ___, rosto escolhido para a conta", "Conjunto de informações que representa um usuário num serviço digital.", "fill-blank", 1, 5, ["internet", "identidade"], WEB_SOURCES],
    ["avatar", "Rosto escolhido para aparecer no lugar do usuário", "Imagem ou figura que representa alguém num ambiente digital.", "association", 1, 5, ["internet", "identidade"], WEB_SOURCES],
    ["usuário", "Quem entra, clica e deixa rastros no sistema", "Pessoa que utiliza um serviço, programa ou dispositivo.", "association", 1, 5, ["internet", "identidade"], WEB_SOURCES],
    ["login", "Entrada digital que pede credenciais", "Processo de identificação para obter acesso a um sistema.", "association", 1, 5, ["internet", "acesso"], WEB_SOURCES],
    ["curtida", "Um toque de aprovação abaixo da postagem", "Sinal de reação positiva atribuído a um conteúdo numa plataforma.", "association", 1, 5, ["internet", "interacao"], WEB_SOURCES],
    ["comentário", "Resposta pública que cresce sob o conteúdo", "Mensagem acrescentada por um usuário a uma publicação.", "association", 1, 5, ["internet", "interacao"], WEB_SOURCES],
    ["postagem", "Conteúdo colocado na linha do tempo", "Publicação feita por um usuário num serviço digital.", "association", 1, 5, ["internet", "publicacao"], WEB_SOURCES],
    ["feed", "Fila renovável de conteúdos na tela", "Fluxo de publicações apresentado continuamente a um usuário.", "association", 2, 4, ["internet", "publicacao"], WEB_SOURCES],
    ["viral", "Conteúdo que se espalha sem espirrar?", "Diz-se do conteúdo que alcança ampla circulação em pouco tempo.", "wordplay", 1, 5, ["internet", "circulacao"], WEB_SOURCES],
    ["tópico", "Assunto que abre uma conversa na comunidade", "Tema ou fio de discussão organizado num espaço digital.", "association", 1, 5, ["internet", "comunidades"], WEB_SOURCES],
    ["chat", "Conversa digitada em tempo quase real", "Sistema de troca imediata de mensagens entre pessoas.", "association", 1, 5, ["internet", "comunicacao"], WEB_SOURCES],
    ["mensagem", "Texto que viaja de uma tela a outra", "Conteúdo enviado digitalmente a um destinatário.", "association", 1, 5, ["internet", "comunicacao"], WEB_SOURCES],
    ["grupo", "Vários perfis reunidos pela mesma conversa", "Espaço digital compartilhado por múltiplos participantes.", "association", 1, 5, ["internet", "comunidades"], WEB_SOURCES],
    ["comunidade", "Pessoas ligadas por interesse antes de endereço", "Conjunto de participantes reunidos por afinidade num espaço digital.", "association", 1, 5, ["internet", "comunidades"], WEB_SOURCES],
    ["moderador", "Cuida da conversa e das regras do espaço", "Pessoa que acompanha discussões e aplica normas numa comunidade.", "association", 2, 5, ["internet", "comunidades"], WEB_SOURCES],
    ["GIF", "Imagem curta que recomeça sem pedir bis", "Formato de imagem digital capaz de exibir animação em repetição.", "association", 2, 4, ["internet", "imagem-digital"], WEB_SOURCES],
    ["vídeo", "Imagem em movimento pronta para compartilhar", "Registro ou conteúdo audiovisual digital.", "association", 1, 5, ["internet", "midia"], WEB_SOURCES],
    ["foto", "Um instante publicado em imagem", "Imagem fixa obtida por meio de uma câmera.", "elliptical", 1, 5, ["internet", "imagem-digital"], WEB_SOURCES],
    ["selfie", "Retrato em que fotógrafo e modelo são a mesma pessoa", "Fotografia que alguém faz de si próprio, geralmente com um dispositivo móvel.", "association", 1, 5, ["internet", "imagem-digital"], WEB_SOURCES],
    ["figurinha", "Imagem pequena que responde no lugar de palavras", "Ilustração pronta enviada como elemento expressivo numa conversa digital.", "association", 1, 5, ["internet", "linguagem-digital"], WEB_SOURCES],
    ["filtro", "Efeito aplicado antes de a imagem aparecer", "Recurso que altera visualmente uma foto ou um vídeo.", "association", 1, 5, ["internet", "imagem-digital"], WEB_SOURCES],
    ["spam", "Mensagem indesejada que chega sem convite", "Conteúdo eletrônico não solicitado, geralmente enviado em massa.", "association", 1, 5, ["internet", "comunicacao"], WEB_SOURCES],
    ["download", "Arquivo vindo da rede para o aparelho", "Transferência de dados de um sistema remoto para um dispositivo local.", "association", 2, 5, ["internet", "transferencia"], WEB_SOURCES],

    // Gêneros, figuras e cultura de fãs (30)
    ["cosplay", "Fã que veste o personagem por inteiro", "Prática de usar roupa e caracterização para representar uma figura ficcional.", "association", 1, 5, ["fandom", "praticas"], COMICS_SOURCES],
    ["dragão", "Asas, escamas e fogo no bestiário fantástico", "Criatura lendária geralmente representada como grande réptil alado.", "association", 1, 5, ["fantasia", "criaturas"], LITERATURE_SOURCES],
    ["fandom", "Comunidade erguida em torno de uma obra", "Conjunto de fãs e práticas culturais ligados a uma obra ou artista.", "association", 2, 4, ["fandom", "comunidades"], WEB_SOURCES],
    ["fantasia", "Gênero em que a magia não precisa pedir licença", "Ficção ambientada em mundos ou situações com elementos sobrenaturais.", "association", 1, 5, ["literatura", "generos"], LITERATURE_SOURCES],
    ["herói", "Enfrenta o perigo pelo bem de outros", "Figura central admirada por coragem e ações extraordinárias.", "association", 1, 5, ["ficcao", "personagens"], COMICS_SOURCES],
    ["magia", "O impossível tratado como habilidade", "Força ou prática sobrenatural em narrativas fantásticas.", "association", 1, 5, ["fantasia", "conceitos"], LITERATURE_SOURCES],
    ["super-herói", "Capa, identidade secreta e dever extraordinário", "Personagem heroico dotado de poderes ou habilidades fora do comum.", "association", 1, 5, ["quadrinhos", "personagens"], COMICS_SOURCES],
    ["vilão", "Faz do plano do protagonista um problema", "Personagem que pratica o mal ou se opõe ao herói.", "association", 1, 5, ["ficcao", "personagens"], COMICS_SOURCES],
    ["zumbi", "Morto que ainda insiste em caminhar?", "Cadáver reanimado frequente em narrativas de terror.", "wordplay", 1, 5, ["terror", "criaturas"], LITERATURE_SOURCES],
    ["terror", "Gênero que convida o medo para a sessão", "Gênero narrativo criado para provocar medo e inquietação.", "association", 1, 5, ["ficcao", "generos"], LITERATURE_SOURCES],
    ["comédia", "___ romântica, gênero de amor e humor", "Forma narrativa ou dramática voltada ao humor.", "fill-blank", 1, 5, ["ficcao", "generos"], CINEMA_SOURCES],
    ["drama", "Conflitos humanos no centro do palco ou da tela", "Obra ou gênero de caráter sério centrado em conflitos humanos.", "association", 1, 5, ["ficcao", "generos"], CINEMA_SOURCES],
    ["ação", "Perseguições e confrontos aceleram a história", "Gênero marcado por movimento, perigo e conflitos físicos.", "association", 1, 5, ["ficcao", "generos"], CINEMA_SOURCES],
    ["suspense", "A resposta demora enquanto a tensão cresce", "Gênero que mantém expectativa e incerteza sobre o que acontecerá.", "association", 1, 5, ["ficcao", "generos"], CINEMA_SOURCES],
    ["policial", "Crime e investigação dividem o enredo", "Gênero narrativo centrado em delitos e sua apuração.", "association", 2, 5, ["ficcao", "generos"], LITERATURE_SOURCES],
    ["épico", "Aventura em escala maior que seus personagens", "Obra de tom grandioso sobre feitos extraordinários ou coletivos.", "association", 2, 5, ["ficcao", "generos"], LITERATURE_SOURCES],
    ["distopia", "O futuro imaginado como aviso", "Ficção que representa uma sociedade opressiva ou indesejável.", "association", 2, 5, ["ficcao", "generos"], LITERATURE_SOURCES],
    ["utopia", "Sociedade perfeita que só existe no projeto", "Representação imaginária de uma organização social ideal.", "association", 2, 5, ["ficcao", "generos"], LITERATURE_SOURCES],
    ["cyberpunk", "Alta tecnologia sob um céu social baixo", "Vertente de ficção científica que combina tecnologia avançada e degradação social.", "association", 3, 4, ["ficcao", "generos"], LITERATURE_SOURCES],
    ["monstro", "Criatura feita para desafiar a forma comum", "Ser imaginário de aspecto ou comportamento assustador.", "association", 1, 5, ["ficcao", "criaturas"], LITERATURE_SOURCES],
    ["alienígena", "Visitante que veio de fora da Terra", "Ser originário de outro planeta ou mundo.", "association", 1, 5, ["ficcao", "criaturas"], LITERATURE_SOURCES],
    ["vampiro", "A noite abre o apetite de suas presas?", "Criatura lendária que se alimenta do sangue dos vivos.", "wordplay", 1, 5, ["terror", "criaturas"], LITERATURE_SOURCES],
    ["lobisomem", "A lua cheia muda homem e fera de lugar", "Criatura lendária que assume forma de lobo ou híbrido humano.", "association", 1, 5, ["terror", "criaturas"], LITERATURE_SOURCES],
    ["bruxa", "Vassoura e feitiço no imaginário popular", "Figura lendária ou ficcional associada à prática de feitiçaria.", "association", 1, 5, ["fantasia", "personagens"], LITERATURE_SOURCES],
    ["fantasma", "Presença do ausente numa casa mal-assombrada", "Aparição atribuída ao espírito de uma pessoa morta.", "association", 1, 5, ["terror", "criaturas"], LITERATURE_SOURCES],
    ["ídolo", "Figura admirada que reúne seguidores", "Pessoa ou personagem alvo de grande admiração pública.", "association", 1, 5, ["fandom", "figuras"], WEB_SOURCES],
    ["autógrafo", "Assinatura que vira lembrança para o admirador", "Assinatura de uma pessoa conhecida oferecida a um fã.", "association", 1, 5, ["fandom", "praticas"], WEB_SOURCES],
    ["convenção", "Fãs, painéis e fantasias sob o mesmo teto", "Encontro organizado de admiradores e profissionais de um campo cultural.", "association", 2, 5, ["fandom", "eventos"], WEB_SOURCES],
    ["fanfic", "O fã continua a história por conta própria", "Narrativa criada por admiradores a partir de personagens ou universos existentes.", "association", 2, 4, ["fandom", "criacao"], WEB_SOURCES],
    ["spoiler", "Revelação que chega antes da surpresa", "Informação que antecipa parte importante do enredo de uma obra.", "association", 1, 5, ["fandom", "linguagem"], WEB_SOURCES],
  ],
} satisfies BiomeBundle;

export const culturaPopEntries = entriesFromBundle(culturaPopBundle);

// Auditoria: 250 registros (40 legados), 250 normalizações únicas, comprimentos 77/165/8
// (3–5/6–10/11–18), estilos 164/46/11/20/9 (assoc./elípt./lacuna/trocad./trivia) e 0 vazamentos.
