import { entriesFromBundle, type BiomeBundle } from "./shared.js";

const historiaBundle = {
  biome: "historia",
  prefix: "his",
  editorialSource: "curadoria-cruzaverso-historia-v3",
  sources: [
    {
      sourceId: "iphan-arqueologico",
      title: "IPHAN — Patrimônio Arqueológico",
      url: "https://www.gov.br/iphan/pt-br/patrimonio-cultural/patrimonio-arqueologico",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "iphan-material",
      title: "IPHAN — Patrimônio Material",
      url: "https://www.gov.br/iphan/pt-br/patrimonio-cultural/patrimonio-material/",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "arquivo-nacional",
      title: "Arquivo Nacional — Sobre o acervo",
      url: "https://www.gov.br/arquivonacional/pt-br/acesso-a-informacao/institucional/acervo",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "bn-digital",
      title: "Fundação Biblioteca Nacional — BNDigital",
      url: "https://bndigital.bn.gov.br/",
      license: "Documentos em domínio público ou publicados com autorização; consulta factual",
      role: "factual",
    },
    {
      sourceId: "cpdoc",
      title: "FGV CPDOC — Dicionários histórico-biográficos",
      url: "https://cpdoc.fgv.br/acervo/dicionarios",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "camara-constituicoes",
      title: "Câmara dos Deputados — Portal da Constituição Cidadã",
      url: "https://www2.camara.leg.br/atividade-legislativa/legislacao/Constituicoes_Brasileiras/constituicao-cidada",
      license: "Uso informativo institucional; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "tse-voto",
      title: "TSE — História da Justiça Eleitoral e do voto feminino",
      url: "https://www.tse.jus.br/comunicacao/noticias/2024/Fevereiro/justica-eleitoral-completa-92-anos-primeiro-codigo-eleitoral-garantiu-o-direito-ao-voto-as-mulheres",
      license: "Uso informativo institucional; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "palmares",
      title: "Fundação Cultural Palmares — Informações Quilombolas",
      url: "https://www.gov.br/palmares/pt-br/departamentos/protecao-preservacao-e-articulacao/informacoes-quilombolas/",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "arquivo-bahia",
      title: "Fundação Pedro Calmon — Revolta dos Malês",
      url: "https://www.ba.gov.br/fpc/2023/01/25/revolta-dos-males-movimento-emancipatorio-completa-188-anos",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "funai",
      title: "Funai — Constituição de 1988 e direitos dos povos indígenas",
      url: "https://www.gov.br/funai/pt-br/atuacao/povos-indigenas/direitos-sociais/apresentacao",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "british-galleries",
      title: "British Museum — Galleries and world collections",
      url: "https://www.britishmuseum.org/collection/galleries",
      license: "Copyright The Trustees of the British Museum; consulta factual",
      role: "factual",
    },
    {
      sourceId: "penn-near-east",
      title: "Penn Museum — Near East Section",
      url: "https://www.penn.museum/about-collections/curatorial-sections/near-east-section",
      license: "Copyright Penn Museum; consulta factual",
      role: "factual",
    },
    {
      sourceId: "penn-global",
      title: "Penn Museum — Galleries and exhibitions",
      url: "https://www.penn.museum/on-view/galleries-exhibitions",
      license: "Copyright Penn Museum; consulta factual",
      role: "factual",
    },
    {
      sourceId: "unesco-silk",
      title: "UNESCO — About the Silk Roads",
      url: "https://www.unesco.org/en/silk-roads/about-silk-roads",
      license: "Copyright UNESCO; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "unesco-slavery",
      title: "UNESCO — Slave Trade Archives",
      url: "https://www.unesco.org/en/articles/slave-trade-archives",
      license: "Copyright UNESCO; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "unesco-africa",
      title: "UNESCO — General History of Africa",
      url: "https://www.unesco.org/en/general-history-africa",
      license: "Copyright UNESCO; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "inah-mexico",
      title: "INAH — Museo Nacional de Antropología",
      url: "https://lugares.inah.gob.mx/es/node/4237",
      license: "Direitos reservados INAH; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "larco-peru",
      title: "Museo Larco — Cultures of Ancient Peru",
      url: "https://www.museolarco.org/en/exhibition/permanent-exhibition/online-exhibition/cultures-of-ancient-peru/",
      license: "Direitos reservados Museo Larco; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "british-asia",
      title: "British Museum — China and South Asia",
      url: "https://www.britishmuseum.org/collection/galleries/china-and-south-asia",
      license: "Copyright The Trustees of the British Museum; consulta factual",
      role: "factual",
    },
    {
      sourceId: "india-national",
      title: "National Museum, New Delhi — Archaeology Collections",
      url: "https://www.nationalmuseumindia.gov.in/en/collections/index/7",
      license: "Direitos reservados National Museum; consulta factual",
      role: "factual",
    },
    {
      sourceId: "kyoto-museum",
      title: "Kyoto National Museum — Swords of Kyoto",
      url: "https://www.kyohaku.go.jp/old/eng/special/koremade/katana_2018.html",
      license: "Copyright Kyoto National Museum; consulta factual",
      role: "factual",
    },
    {
      sourceId: "iphan-missoes",
      title: "IPHAN — Missões Jesuíticas Guarani",
      url: "https://www.gov.br/iphan/pt-br/assuntos/noticias/400-anos-das-missoes-jesuiticas-guarani-iphan-participa-do-inicio-das-celebracoes-no-rs",
      license: "Direitos reservados; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "smithsonian-africa",
      title: "Smithsonian National Museum of African Art — Collection",
      url: "https://africa.si.edu/collection",
      license: "Smithsonian terms of use; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "national-archives-uk",
      title: "The National Archives — Education resources",
      url: "https://www.nationalarchives.gov.uk/education/",
      license: "Crown copyright; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "loc-industrial",
      title: "Library of Congress — The Industrial Revolution",
      url: "https://www.loc.gov/classroom-materials/industrial-revolution-in-the-united-states/",
      license: "Materiais com direitos indicados por item; consulta factual",
      role: "factual",
    },
    {
      sourceId: "archives-us",
      title: "U.S. National Archives — Founding Documents",
      url: "https://www.archives.gov/founding-docs",
      license: "Obras do governo federal dos EUA geralmente em domínio público; consulta factual",
      role: "factual",
    },
    {
      sourceId: "un-direitos",
      title: "United Nations — Universal Declaration of Human Rights",
      url: "https://www.un.org/en/about-us/universal-declaration-of-human-rights",
      license: "Copyright United Nations; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "un-genocidio",
      title: "United Nations — Convention on the Prevention and Punishment of the Crime of Genocide",
      url: "https://www.un.org/en/genocide-prevention/1948-convention",
      license: "Copyright United Nations; consulta factual sem reprodução",
      role: "factual",
    },
    {
      sourceId: "ushmm",
      title: "United States Holocaust Memorial Museum — Holocaust Encyclopedia",
      url: "https://encyclopedia.ushmm.org/",
      license: "Copyright United States Holocaust Memorial Museum; consulta factual",
      role: "factual",
    },
    {
      sourceId: "govza-history",
      title: "South African Government — History: the rise and fall of apartheid",
      url: "https://www.gov.za/about-sa/history",
      license: "Copyright South African Government; consulta factual sem reprodução",
      role: "factual",
    },
  ],
  records: [
    // Ofício da história, fontes e patrimônio (30)
    ["acervo", "O conjunto que dá trabalho ao curador", "Conjunto de documentos ou objetos mantidos por uma instituição ou pessoa.", "association", 2, 5, ["historiografia", "patrimonio"], ["arquivo-nacional"]],
    ["anais", "O ano passado a limpo, volume após volume?", "Registro cronológico de acontecimentos, muitas vezes organizado por ano.", "wordplay", 3, 3, ["historiografia", "documento"], ["bn-digital"]],
    ["arqueologia", "Onde uma camada de terra pode valer um capítulo", "Disciplina que estuda sociedades por seus vestígios materiais.", "association", 2, 5, ["historiografia", "pesquisa"], ["iphan-arqueologico"]],
    ["artefato", "Objeto que chega da escavação com contexto", "Objeto produzido ou modificado por seres humanos e estudado como vestígio cultural.", "association", 2, 4, ["historiografia", "cultura-material"], ["iphan-arqueologico"]],
    ["arquivo", "Passado guardado em caixas bem catalogadas", "Instituição ou conjunto organizado que preserva documentos.", "association", 1, 5, ["historiografia", "documento"], ["arquivo-nacional"]],
    ["cerâmica", "Sobrevive em cacos e ainda conta como se vivia", "Material de argila queimada comum entre vestígios arqueológicos.", "association", 2, 5, ["arqueologia", "cultura-material"], ["iphan-arqueologico"]],
    ["códice", "Livro antigo que também pode falar por imagens", "Manuscrito em formato de livro, produzido antes ou no início da imprensa.", "elliptical", 3, 3, ["historiografia", "escrita"], ["bn-digital", "inah-mexico"]],
    ["crônica", "Entre o testemunho do tempo e a arte de narrá-lo", "Narrativa de acontecimentos dispostos no tempo, usada também como fonte histórica.", "association", 2, 4, ["historiografia", "narrativa"], ["bn-digital"]],
    ["cronologia", "Põe o antes e o depois em ordem", "Organização de acontecimentos segundo sua sequência temporal.", "association", 1, 5, ["historiografia", "tempo"], ["arquivo-nacional"]],
    ["década", "Os anos 20, por exemplo", "Período de dez anos.", "trivia", 1, 5, ["historiografia", "tempo"], ["arquivo-nacional"]],
    ["documento", "Pode ser carta, mapa, processo ou fotografia", "Registro escrito, visual ou sonoro que serve como fonte de informação.", "trivia", 1, 5, ["historiografia", "fonte"], ["arquivo-nacional"]],
    ["escavação", "Pesquisa que avança enquanto o terreno abaixa?", "Remoção metódica de camadas de um sítio para estudar seus vestígios.", "wordplay", 2, 4, ["arqueologia", "pesquisa"], ["iphan-arqueologico"]],
    ["escrita", "Fez a memória caber em sinais", "Sistema de representação da linguagem por sinais gráficos.", "association", 1, 5, ["historiografia", "comunicacao"], ["bn-digital"]],
    ["estela", "Pedra erguida que pode carregar texto ou imagem", "Monumento vertical de pedra, muitas vezes inscrito ou esculpido.", "association", 3, 3, ["arqueologia", "cultura-material"], ["british-galleries"]],
    ["fonte", "Sem ela, afirmação histórica vira palpite", "Vestígio ou registro usado para produzir conhecimento sobre o passado.", "association", 1, 5, ["historiografia", "pesquisa"], ["arquivo-nacional"]],
    ["inscrição", "Mensagem que atravessa séculos gravada em pedra", "Texto gravado ou marcado de modo duradouro numa superfície.", "association", 2, 4, ["historiografia", "escrita"], ["british-galleries"]],
    ["manuscrito", "Texto que nasceu da mão, não da prensa", "Documento escrito à mão.", "association", 2, 5, ["historiografia", "documento"], ["bn-digital"]],
    ["memória", "O passado lembrado — e também disputado", "Conjunto de lembranças pelo qual pessoas e grupos elaboram o passado.", "elliptical", 2, 5, ["historiografia", "sociedade"], ["arquivo-nacional"]],
    ["museu", "Casa onde objetos ganham contexto e público", "Instituição que pesquisa, conserva e expõe patrimônio.", "association", 1, 5, ["historiografia", "patrimonio"], ["iphan-material"]],
    ["numismática", "A história examinada moeda por moeda", "Estudo de moedas, medalhas e objetos monetários.", "association", 4, 2, ["historiografia", "moeda"], ["british-galleries"]],
    ["oralidade", "Quando a lembrança viaja de boca em boca", "Transmissão de conhecimentos e memórias pela fala.", "association", 2, 4, ["historiografia", "memoria"], ["arquivo-nacional"]],
    ["paleografia", "Lê a letra difícil que o tempo deixou", "Estudo de escritas antigas e de sua leitura.", "association", 4, 2, ["historiografia", "escrita"], ["bn-digital"]],
    ["patrimônio", "Herança coletiva que pede cuidado", "Bem cultural reconhecido como referência de memória e identidade.", "association", 2, 5, ["historiografia", "preservacao"], ["iphan-material"]],
    ["ruína", "O edifício caiu, mas não ficou mudo?", "Remanescente de uma construção destruída ou deteriorada.", "wordplay", 2, 5, ["arqueologia", "arquitetura"], ["iphan-arqueologico"]],
    ["século", "Cabe cem anos nesta medida", "Período de cem anos.", "trivia", 1, 5, ["historiografia", "tempo"], ["arquivo-nacional"]],
    ["sítio", "Lugar onde o contexto importa tanto quanto o achado", "Local com vestígios de atividades humanas estudados pela arqueologia.", "association", 2, 4, ["arqueologia", "pesquisa"], ["iphan-arqueologico"]],
    ["tombamento", "Proteção legal que não transforma bem em túmulo?", "Ato administrativo de reconhecimento e proteção de um bem cultural.", "wordplay", 3, 4, ["patrimonio", "preservacao"], ["iphan-material"]],
    ["abolição", "O fim na lei que não apaga as consequências", "Extinção legal de uma instituição ou prática, como a escravidão.", "association", 2, 5, ["direitos", "escravidao"], ["arquivo-nacional", "unesco-slavery"]],
    ["vestígio", "Pista material deixada por quem veio antes", "Marca ou objeto remanescente de atividade passada.", "association", 1, 5, ["arqueologia", "fonte"], ["iphan-arqueologico"]],
    ["epígrafe", "Texto curto que uma pedra resolveu conservar", "Inscrição breve gravada num monumento ou objeto.", "association", 3, 3, ["historiografia", "escrita"], ["british-galleries"]],

    // Antiguidade mediterrânea e do Oriente Próximo (43)
    ["acrópole", "Atenas vista do alto", "Parte elevada e fortificada de uma antiga cidade grega.", "trivia", 2, 4, ["grecia", "cidade"], ["british-galleries"]],
    ["ágora", "Praça grega de comércio e debate", "Espaço público central das cidades da Grécia antiga.", "elliptical", 2, 4, ["grecia", "cidade"], ["british-galleries"]],
    ["ânfora", "Duas alças para o vinho cruzar o Mediterrâneo", "Vaso antigo de corpo alongado e duas alças, usado para armazenar e transportar produtos.", "association", 3, 3, ["mediterraneo", "cultura-material"], ["british-galleries"]],
    ["aqueduto", "A água chegava à cidade por seus arcos", "Canal construído para conduzir água, notável na engenharia romana.", "association", 1, 5, ["roma", "engenharia"], ["british-galleries"]],
    ["armadura", "Metal entre o golpe e o combatente", "Conjunto de peças defensivas usado para proteger o corpo em combate.", "association", 1, 5, ["guerra", "cultura-material"], ["british-galleries"]],
    ["assírio", "De Nínive, em muitos relevos palacianos", "Relativo à antiga Assíria, potência da Mesopotâmia.", "trivia", 3, 3, ["mesopotamia", "povo"], ["penn-near-east"]],
    ["babilônia", "Cidade de Hamurábi às margens do Eufrates", "Antiga cidade mesopotâmica que foi centro de importantes impérios.", "trivia", 2, 5, ["mesopotamia", "cidade"], ["penn-near-east"]],
    ["cuneiforme", "Escrita em forma de cunha sobre argila", "Sistema de escrita gravado com sinais em forma de cunha, usado na Mesopotâmia.", "association", 3, 4, ["mesopotamia", "escrita"], ["penn-near-east"]],
    ["dinastia", "O trono fica em família por gerações", "Sequência de governantes pertencentes à mesma família.", "association", 1, 5, ["politica", "monarquia"], ["british-galleries"]],
    ["Egito", "Reino antigo que seguiu o ritmo do Nilo", "Civilização antiga desenvolvida no vale do rio Nilo.", "association", 1, 5, ["africa", "antiguidade"], ["british-galleries"]],
    ["escriba", "Profissional da pena antes da gráfica", "Pessoa treinada para escrever e copiar registros nas sociedades antigas.", "association", 2, 4, ["escrita", "trabalho"], ["british-galleries"]],
    ["faraó", "Usava a dupla coroa no vale do Nilo", "Título dos soberanos do Egito antigo.", "association", 1, 5, ["egito", "monarquia"], ["british-galleries"]],
    ["fórum", "O coração público de uma cidade romana", "Praça central romana destinada a comércio, política e cerimônias.", "association", 2, 4, ["roma", "cidade"], ["british-galleries"]],
    ["gladiador", "Entrava na arena para lutar diante da plateia", "Combatente que participava de espetáculos armados na Roma antiga.", "association", 1, 5, ["roma", "espetaculo"], ["british-galleries"]],
    ["helenismo", "A cultura grega viajou com as conquistas de Alexandre", "Expansão e mistura de referências gregas após as conquistas de Alexandre.", "trivia", 3, 3, ["grecia", "intercambio"], ["british-galleries"]],
    ["hieróglifo", "Sinal que desenha e escreve ao mesmo tempo", "Caractere do sistema de escrita monumental do Egito antigo.", "association", 2, 4, ["egito", "escrita"], ["british-galleries"]],
    ["hoplita", "Escudo redondo na infantaria grega", "Soldado de infantaria pesada das cidades gregas antigas.", "association", 4, 2, ["grecia", "guerra"], ["british-galleries"]],
    ["império", "Muitos povos sob um centro de poder", "Estado extenso que exerce domínio sobre diferentes territórios e populações.", "association", 1, 5, ["politica", "estado"], ["british-galleries"]],
    ["legião", "Unidade que marchava sob as águias de Roma", "Grande unidade do exército romano.", "trivia", 2, 5, ["roma", "guerra"], ["british-galleries"]],
    ["mesopotâmia", "Terra entre o Tigre e o Eufrates", "Região histórica situada entre e ao redor dos rios Tigre e Eufrates.", "trivia", 1, 5, ["oriente-proximo", "antiguidade"], ["penn-near-east"]],
    ["moeda", "Pequeno metal que circula com a marca do poder", "Peça padronizada usada como meio de pagamento e emitida por uma autoridade.", "association", 1, 5, ["economia", "cultura-material"], ["british-galleries"]],
    ["múmia", "Corpo preparado para atravessar o tempo", "Corpo preservado por processos naturais ou técnicas funerárias.", "association", 1, 5, ["egito", "funerario"], ["british-galleries"]],
    ["obelisco", "Monumento alto que termina em ponta", "Pilar monumental de seção quadrada e topo piramidal, associado ao Egito antigo.", "elliptical", 2, 5, ["egito", "arquitetura"], ["british-galleries"]],
    ["papiro", "Página do Nilo antes do papel", "Suporte de escrita feito da planta de mesmo nome no mundo antigo.", "association", 2, 5, ["egito", "escrita"], ["british-galleries"]],
    ["patrício", "No topo da velha hierarquia romana", "Membro da ordem aristocrática tradicional de Roma.", "elliptical", 3, 3, ["roma", "sociedade"], ["british-galleries"]],
    ["persa", "Do império que ligou o Irã ao Mediterrâneo", "Relativo aos povos e impérios históricos originados na Pérsia.", "trivia", 2, 5, ["oriente-proximo", "povo"], ["penn-near-east"]],
    ["pirâmide", "Base larga, ápice estreito e fama faraônica", "Construção monumental de faces triangulares, célebre no Egito antigo.", "association", 1, 5, ["egito", "arquitetura"], ["british-galleries"]],
    ["plebe", "A maioria livre fora da elite patrícia", "Camada de cidadãos comuns situada fora da ordem patrícia na Roma antiga.", "association", 3, 4, ["roma", "sociedade"], ["british-galleries"]],
    ["pólis", "Mais que cidade, uma comunidade política grega", "Cidade-Estado da Grécia antiga.", "association", 2, 4, ["grecia", "politica"], ["british-galleries"]],
    ["Roma", "Começou cidade e virou centro de um vasto domínio", "Cidade que originou a República e o Império romanos.", "trivia", 1, 5, ["roma", "cidade"], ["british-galleries"]],
    ["sarcófago", "Caixa de pedra para uma viagem sem volta", "Caixão de pedra, frequentemente decorado, usado em sepultamentos antigos.", "association", 2, 5, ["funerario", "cultura-material"], ["british-galleries"]],
    ["senado", "Casa de anciãos no nome e de política na prática?", "Assembleia política cujo nome e tradição remontam à Roma antiga.", "wordplay", 2, 5, ["roma", "politica"], ["british-galleries"]],
    ["sumério", "De Ur e das primeiras cidades mesopotâmicas", "Relativo à Suméria, civilização do sul da Mesopotâmia.", "trivia", 3, 3, ["mesopotamia", "povo"], ["penn-near-east"]],
    ["templo", "Casa de culto que também pode virar monumento", "Edifício destinado a práticas religiosas.", "association", 1, 5, ["religiao", "arquitetura"], ["british-galleries"]],
    ["trono", "Assento que representa muito mais que conforto", "Assento cerimonial associado ao poder soberano.", "association", 1, 5, ["monarquia", "simbolo"], ["british-galleries"]],
    ["zigurate", "Torre escalonada da paisagem mesopotâmica", "Construção religiosa mesopotâmica em plataformas sobrepostas.", "elliptical", 3, 3, ["mesopotamia", "arquitetura"], ["penn-near-east"]],
    ["cetro", "Bastão que prolonga a autoridade do soberano", "Bastão cerimonial que simboliza poder de governo.", "association", 2, 5, ["monarquia", "simbolo"], ["british-galleries"]],
    ["coroa", "Vai à cabeça quando o poder é hereditário", "Adorno usado como símbolo de soberania monárquica.", "association", 1, 5, ["monarquia", "simbolo"], ["british-galleries"]],
    ["cônsul", "Um dos dois chefes anuais da República romana", "Magistrado de mais alto posto na República romana.", "trivia", 3, 4, ["roma", "politica"], ["british-galleries"]],
    ["tribuno", "Magistrado romano que podia defender a plebe", "Representante político da plebe na República romana.", "trivia", 3, 3, ["roma", "politica"], ["british-galleries"]],
    ["república", "O cargo máximo deixa de ser herança de família", "Forma de governo em que a chefia do Estado não é hereditária.", "association", 1, 5, ["politica", "estado"], ["archives-us"]],
    ["colônia", "Território governado de fora", "Território submetido ao domínio político de outra potência.", "elliptical", 1, 5, ["politica", "colonialismo"], ["national-archives-uk"]],
    ["tratado", "Acordo que cruza fronteiras com assinatura oficial", "Acordo formal celebrado entre Estados ou autoridades políticas.", "association", 1, 5, ["politica", "diplomacia"], ["un-direitos"]],

    // Mundo medieval, islâmico e eurasiático (32)
    ["abadia", "Mosteiro sob a direção de um abade ou abadessa", "Comunidade monástica e seu conjunto de edifícios, dirigida por abade ou abadessa.", "association", 2, 4, ["medieval", "religiao"], ["british-galleries"]],
    ["bizantino", "Romano do Oriente, com capital em Constantinopla", "Relativo ao Império Romano do Oriente, cuja capital era Constantinopla.", "trivia", 2, 4, ["medieval", "mediterraneo"], ["penn-near-east"]],
    ["burgo", "Núcleo urbano que cresceu entre muralhas medievais", "Povoação fortificada ou núcleo urbano medieval.", "association", 2, 4, ["medieval", "cidade"], ["british-galleries"]],
    ["califa", "Sucessor no título político da primeira comunidade islâmica", "Título de liderança político-religiosa usado em diferentes Estados islâmicos.", "association", 3, 3, ["islam", "politica"], ["penn-near-east"]],
    ["califado", "De Damasco a Bagdá, uma forma histórica de governo", "Estado governado por um califa em diferentes períodos da história islâmica.", "trivia", 3, 3, ["islam", "politica"], ["penn-near-east"]],
    ["castelo", "Moradia nobre com muralhas para tempos inseguros", "Residência fortificada associada à elite medieval.", "association", 1, 5, ["medieval", "arquitetura"], ["british-galleries"]],
    ["catedral", "Igreja onde o bispo tem sua cadeira", "Igreja que abriga a sede de um bispo.", "association", 1, 5, ["medieval", "religiao"], ["british-galleries"]],
    ["cavaleiro", "Guerreiro montado que também virou título social", "Combatente a cavalo, associado na Europa medieval a uma posição de elite.", "association", 1, 5, ["medieval", "guerra"], ["british-galleries"]],
    ["cruzada", "Expedição armada medieval proclamada em nome da fé", "Campanha militar cristã medieval legitimada pela Igreja, sobretudo rumo ao Mediterrâneo oriental.", "association", 2, 5, ["medieval", "religiao"], ["british-galleries", "penn-near-east"]],
    ["dracar", "Navio comprido que ganhou cabeça de dragão no imaginário", "Tipo de embarcação longa associado às viagens escandinavas medievais.", "association", 3, 3, ["viking", "navegacao"], ["british-galleries"]],
    ["emirado", "Território histórico sob um emir", "Estado ou território governado por um emir.", "elliptical", 3, 3, ["islam", "politica"], ["penn-near-east"]],
    ["feudalismo", "Terra, dependência e poder local na Europa medieval", "Conceito usado para descrever relações sociais e políticas da Europa medieval ligadas a feudos e dependências.", "association", 2, 5, ["medieval", "sociedade"], ["national-archives-uk"]],
    ["feudo", "Terra ou rendimento no centro de um vínculo vassálico", "Bem ou direito concedido no contexto de relações vassálicas medievais.", "association", 2, 5, ["medieval", "sociedade"], ["national-archives-uk"]],
    ["guilda", "Ofício medieval organizado em associação", "Associação de mercadores ou artesãos que regulava uma atividade.", "association", 2, 4, ["medieval", "trabalho"], ["british-galleries"]],
    ["hégira", "A jornada a Medina que abre o calendário islâmico", "Migração de Maomé e seus seguidores de Meca para Medina, marco inicial do calendário islâmico.", "trivia", 3, 3, ["islam", "cronologia"], ["penn-near-east"]],
    ["islã", "Fé que se expandiu a partir da Arábia no século VII", "Religião monoteísta surgida na Arábia no século VII.", "trivia", 1, 5, ["islam", "religiao"], ["penn-near-east"]],
    ["mosteiro", "Comunidade religiosa atrás de claustros", "Edifício ou conjunto onde vive uma comunidade monástica.", "association", 1, 5, ["medieval", "religiao"], ["british-galleries"]],
    ["otomano", "Do império com capital em Constantinopla após 1453", "Relativo ao império governado pela dinastia turca otomana.", "trivia", 2, 4, ["islam", "imperio"], ["penn-near-east"]],
    ["pergaminho", "Pele preparada que virou página", "Suporte de escrita feito de pele animal tratada.", "association", 2, 5, ["medieval", "escrita"], ["bn-digital"]],
    ["peste", "A Negra marcou profundamente a Europa do século XIV", "Doença infecciosa que causou grandes mortandades na Europa medieval.", "trivia", 1, 5, ["medieval", "sociedade"], ["national-archives-uk"]],
    ["runa", "Letra talhada do norte germânico", "Caractere dos alfabetos usados por povos germânicos, sobretudo na Escandinávia medieval.", "association", 2, 4, ["viking", "escrita"], ["british-galleries"]],
    ["samurai", "Espada e serviço na elite guerreira japonesa", "Membro da classe guerreira que teve papel militar, político e cultural no Japão.", "association", 1, 5, ["japao", "guerra"], ["kyoto-museum"]],
    ["servo", "Preso à dependência, não exatamente uma pessoa escravizada", "Camponês medieval submetido a obrigações para com um senhor e ligado à terra.", "association", 2, 4, ["medieval", "sociedade"], ["national-archives-uk"]],
    ["sultão", "Título que comandou diferentes Estados islâmicos", "Título de soberano usado em diversos Estados do mundo islâmico.", "association", 2, 4, ["islam", "politica"], ["penn-near-east"]],
    ["suserano", "Recebia fidelidade de um vassalo", "Senhor a quem um vassalo devia fidelidade numa relação feudal.", "association", 3, 3, ["medieval", "sociedade"], ["national-archives-uk"]],
    ["vassalo", "Jurava fidelidade e recebia proteção ou benefício", "Pessoa ligada a um senhor por compromisso de fidelidade no mundo feudal.", "association", 2, 4, ["medieval", "sociedade"], ["national-archives-uk"]],
    ["viking", "Navegador escandinavo da Alta Idade Média", "Nome dado a participantes de expedições marítimas escandinavas medievais.", "elliptical", 1, 5, ["viking", "navegacao"], ["british-galleries"]],
    ["xogum", "Comandante militar que governou em nome do imperador", "Título do chefe militar que exerceu o governo do Japão em longos períodos.", "association", 2, 4, ["japao", "politica"], ["kyoto-museum"]],
    ["daimio", "Senhor territorial do Japão dos guerreiros", "Senhor feudal japonês que controlava domínios e vassalos.", "association", 4, 2, ["japao", "politica"], ["kyoto-museum"]],
    ["horda", "Confederação nômade que também deu nome a Estados da estepe", "Grande agrupamento político-militar associado a povos nômades eurasiáticos.", "association", 3, 3, ["eurasia", "politica"], ["unesco-silk"]],
    ["mongol", "Do povo que formou o maior império terrestre contínuo", "Relativo aos mongóis, povo da Ásia Interior que criou um vasto império no século XIII.", "trivia", 2, 5, ["eurasia", "imperio"], ["unesco-silk"]],
    ["caravançará", "Pouso de mercadores e animais nas rotas da seda", "Hospedaria fortificada para caravanas em rotas comerciais da Ásia e do Oriente Médio.", "association", 4, 2, ["eurasia", "comercio"], ["unesco-silk"]],

    // África, diásporas e descolonização (20)
    ["apartheid", "A segregação virou política de Estado na África do Sul", "Regime sul-africano que institucionalizou a segregação e a dominação racial entre 1948 e 1994.", "trivia", 2, 5, ["africa", "segregacao"], ["govza-history"]],
    ["axum", "Reino antigo do Chifre da África que cunhava moedas", "Antigo reino centrado no norte da atual Etiópia e na Eritreia.", "trivia", 4, 2, ["africa", "antiguidade"], ["unesco-africa"]],
    ["banto", "Família de línguas em uma vasta expansão africana", "Termo linguístico para um grande grupo de línguas faladas na África central, oriental e austral.", "association", 3, 4, ["africa", "linguas"], ["unesco-africa"]],
    ["Benim", "Reino do obá e dos bronzes saqueados em 1897", "Reino histórico da região da atual Nigéria, governado por um obá.", "trivia", 3, 3, ["africa", "reino"], ["smithsonian-africa"]],
    ["diáspora", "Um povo disperso que mantém e recria vínculos", "Dispersão de uma população para diferentes regiões, voluntária ou forçada.", "association", 2, 5, ["migracao", "africa"], ["unesco-slavery"]],
    ["gana", "Império medieval da África Ocidental anterior ao país moderno", "Nome de um antigo império comercial do Sahel, distinto do atual país homônimo.", "trivia", 3, 4, ["africa", "imperio"], ["unesco-africa"]],
    ["griô", "Arquivo vivo em voz, música e narrativa", "Guardião e transmissor oral de histórias e genealogias em sociedades da África Ocidental.", "association", 3, 3, ["africa", "oralidade"], ["unesco-africa"]],
    ["kush", "Reino núbio ao sul do Egito", "Antigo reino da Núbia, no vale do Nilo ao sul do Egito.", "elliptical", 4, 2, ["africa", "antiguidade"], ["british-galleries", "unesco-africa"]],
    ["mali", "Império de Mansa Musa e do ouro saariano", "Império medieval da África Ocidental ligado ao comércio transaariano.", "trivia", 2, 5, ["africa", "imperio"], ["unesco-africa"]],
    ["meroé", "Capital núbia conhecida por suas pirâmides", "Cidade que foi centro do reino de Kush, no atual Sudão.", "trivia", 4, 2, ["africa", "cidade"], ["british-galleries", "unesco-africa"]],
    ["núbia", "Região nilótica entre o sul do Egito e o Sudão", "Região histórica do vale do Nilo ao sul do Egito.", "trivia", 3, 3, ["africa", "antiguidade"], ["british-galleries", "unesco-africa"]],
    ["obá", "Título real no Benim histórico", "Título do soberano do reino de Benim.", "elliptical", 4, 2, ["africa", "monarquia"], ["smithsonian-africa"]],
    ["sahel", "Faixa de antigos reinos ao sul do Saara", "Região africana de transição ao sul do deserto do Saara.", "association", 2, 4, ["africa", "geografia-historica"], ["unesco-africa"]],
    ["songai", "Império do Níger que sucedeu o Mali", "Império da África Ocidental centrado no vale do rio Níger.", "trivia", 4, 2, ["africa", "imperio"], ["unesco-africa"]],
    ["suaíli", "Língua de uma costa moldada pelo comércio do Índico", "Língua e referência cultural de populações da costa oriental africana.", "association", 3, 3, ["africa", "indico"], ["unesco-africa"]],
    ["zulu", "Do reino formado no sul da África no século XIX", "Relativo a um povo e reino histórico da África Austral, de língua banto.", "trivia", 2, 4, ["africa", "reino"], ["unesco-africa"]],
    ["pan-africanismo", "Projeto de união política que atravessa o continente e a diáspora", "Movimento que promove solidariedade e ação comum entre povos africanos e suas diásporas.", "association", 4, 3, ["africa", "ideias"], ["unesco-africa", "unesco-slavery"]],
    ["negritude", "Afirmação cultural negra contra o domínio colonial", "Movimento intelectual e literário francófono de valorização das identidades negras.", "association", 3, 3, ["africa", "ideias"], ["unesco-africa"]],
    ["colonialismo", "Domínio externo que redesenhou fronteiras e economias", "Sistema de controle político e exploração de territórios por uma potência estrangeira.", "association", 2, 5, ["politica", "imperialismo"], ["national-archives-uk", "unesco-slavery"]],
    ["descolonização", "Quando impérios perderam colônias e novos Estados emergiram", "Processo pelo qual territórios colonizados conquistaram independência política.", "association", 2, 4, ["africa", "independencia"], ["national-archives-uk"]],

    // Ásia do Sul, China e Japão (25)
    ["edo", "Nome antigo de Tóquio e de um longo período japonês", "Nome da atual Tóquio e do período de governo Tokugawa, de 1603 a 1868.", "trivia", 2, 4, ["japao", "cidade"], ["kyoto-museum"]],
    ["gupta", "Dinastia associada a um florescimento artístico no norte da Índia", "Dinastia que governou grande parte do norte da Índia entre os séculos IV e VI.", "trivia", 4, 2, ["india", "dinastia"], ["india-national"]],
    ["han", "Dinastia chinesa que deu nome ao maior grupo étnico do país", "Dinastia que governou a China entre 206 a.C. e 220 d.C., com uma interrupção.", "trivia", 3, 4, ["china", "dinastia"], ["british-asia"]],
    ["harapa", "Cidade que batizou uma civilização do vale do Indo", "Sítio urbano da antiga civilização do Indo, no atual Paquistão.", "trivia", 4, 2, ["india", "antiguidade"], ["british-asia"]],
    ["marajá", "Um grande rei no título do sul da Ásia", "Título histórico de soberano ou príncipe no sul da Ásia.", "association", 2, 4, ["india", "monarquia"], ["british-asia"]],
    ["maurya", "Dinastia de Ashoka na Índia antiga", "Dinastia do primeiro grande império que unificou boa parte do subcontinente indiano.", "trivia", 4, 2, ["india", "dinastia"], ["india-national"]],
    ["meiji", "Era da restauração imperial e rápida transformação japonesa", "Período japonês iniciado em 1868, marcado por centralização e modernização do Estado.", "trivia", 3, 3, ["japao", "politica"], ["kyoto-museum"]],
    ["ming", "Dinastia chinesa famosa pela porcelana azul e branca", "Dinastia que governou a China de 1368 a 1644.", "trivia", 2, 4, ["china", "dinastia"], ["british-asia"]],
    ["mogol", "Império de origem centro-asiática que ergueu o Taj Mahal", "Relativo ao império que governou grande parte do subcontinente indiano entre os séculos XVI e XIX.", "trivia", 2, 4, ["india", "imperio"], ["british-asia"]],
    ["pagode", "Torre de vários andares ligada a tradições budistas", "Edificação religiosa asiática, geralmente em torre de pavimentos sobrepostos.", "association", 2, 4, ["asia", "arquitetura"], ["british-asia"]],
    ["qing", "Última dinastia imperial chinesa", "Dinastia de origem manchu que governou a China de 1644 a 1912.", "trivia", 3, 3, ["china", "dinastia"], ["british-asia"]],
    ["rajá", "Rei em título do sul da Ásia", "Título de governante ou príncipe no sul da Ásia.", "elliptical", 2, 4, ["india", "monarquia"], ["british-asia"]],
    ["sultanato", "Estado que põe um sultão no comando", "Estado ou território governado por um sultão.", "association", 3, 3, ["asia", "politica"], ["british-asia"]],
    ["tang", "Dinastia chinesa de Chang'an e intensa circulação pela Rota da Seda", "Dinastia que governou a China entre 618 e 907.", "trivia", 3, 3, ["china", "dinastia"], ["british-asia", "unesco-silk"]],
    ["tokugawa", "Família de xoguns que governou a partir de Edo", "Dinastia de xoguns que dirigiu o Japão de 1603 a 1868.", "trivia", 3, 3, ["japao", "dinastia"], ["kyoto-museum"]],
    ["xogunato", "Governo japonês com o chefe militar no centro", "Regime de governo dirigido por um xogum no Japão.", "association", 3, 3, ["japao", "politica"], ["kyoto-museum"]],
    ["confucionismo", "Pensamento que ligou ética, família e governo na Ásia Oriental", "Tradição filosófica e ética derivada dos ensinamentos de Confúcio.", "association", 3, 3, ["china", "ideias"], ["british-asia"]],
    ["mandarim", "Funcionário letrado da burocracia imperial chinesa", "Nome dado no Ocidente a altos funcionários civis da China imperial.", "association", 3, 4, ["china", "estado"], ["british-asia"]],
    ["estupa", "Monumento budista que guarda relíquias", "Estrutura religiosa budista, muitas vezes construída para abrigar relíquias.", "association", 3, 3, ["india", "religiao"], ["british-asia"]],
    ["sânscrito", "Idioma clássico de muitos textos do sul da Ásia", "Língua clássica indo-ariana em que foram compostas numerosas obras religiosas e literárias.", "association", 3, 3, ["india", "linguas"], ["british-asia"]],
    ["chola", "Dinastia tâmil de templos e comércio marítimo", "Dinastia do sul da Índia que teve grande projeção entre os séculos IX e XIII.", "trivia", 4, 2, ["india", "dinastia"], ["india-national"]],
    ["manchu", "Do povo que fundou a dinastia Qing", "Relativo ao povo do nordeste asiático que estabeleceu a dinastia Qing.", "trivia", 3, 3, ["china", "povo"], ["british-asia"]],
    ["khmer", "Do império que deixou Angkor", "Relativo ao povo e ao império histórico centrado no atual Camboja.", "trivia", 3, 3, ["sudeste-asiatico", "imperio"], ["british-asia"]],
    ["muromachi", "Período japonês dos xoguns Ashikaga", "Período da história japonesa associado ao xogunato Ashikaga, entre os séculos XIV e XVI.", "trivia", 4, 2, ["japao", "cronologia"], ["kyoto-museum"]],
    ["xintoísmo", "Tradição japonesa dos kami e dos santuários", "Tradição religiosa originária do Japão, centrada no culto aos kami.", "association", 2, 4, ["japao", "religiao"], ["british-asia"]],

    // Américas antes e durante a conquista europeia (20)
    ["asteca", "Nome difundido para o mundo mexica", "Termo amplamente usado para os mexicas e seus aliados no centro do México.", "association", 1, 5, ["mesoamerica", "povo"], ["inah-mexico"]],
    ["ayllu", "Comunidade andina de parentesco e trabalho", "Grupo social andino unido por parentesco, território e obrigações coletivas.", "association", 4, 2, ["andes", "sociedade"], ["larco-peru"]],
    ["chinampa", "Ilha de cultivo no sistema lacustre mesoamericano", "Parcela agrícola elevada construída em áreas rasas de lagos no México central.", "association", 4, 2, ["mesoamerica", "agricultura"], ["inah-mexico"]],
    ["chimú", "Reino costeiro andino com capital em Chan Chan", "Sociedade andina que dominou parte da costa norte do Peru antes dos incas.", "trivia", 4, 2, ["andes", "reino"], ["larco-peru"]],
    ["inca", "De Cusco, numa rede imperial de estradas", "Relativo ao povo e ao império andino governado a partir de Cusco.", "trivia", 1, 5, ["andes", "imperio"], ["larco-peru"]],
    ["maia", "Escreveu sua história em glifos e cidades", "Relativo aos povos maias da Mesoamérica, presentes do passado ao presente.", "association", 1, 5, ["mesoamerica", "povo"], ["inah-mexico"]],
    ["mexica", "Povo que fundou Tenochtitlán", "Povo de língua náuatle que liderou o império conhecido como asteca.", "trivia", 3, 3, ["mesoamerica", "povo"], ["inah-mexico"]],
    ["moche", "Cultura da costa peruana de vasos-retrato", "Sociedade antiga da costa norte do Peru, conhecida por sua cerâmica escultórica.", "trivia", 3, 3, ["andes", "cultura-material"], ["larco-peru"]],
    ["nasca", "Cultura peruana das grandes linhas no deserto", "Sociedade antiga da costa sul do Peru, conhecida por cerâmica e geoglifos.", "trivia", 2, 4, ["andes", "cultura-material"], ["larco-peru"]],
    ["olmeca", "Civilização antiga das cabeças colossais", "Civilização mesoamericana desenvolvida na costa do Golfo do México.", "trivia", 2, 4, ["mesoamerica", "antiguidade"], ["inah-mexico"]],
    ["paracas", "Cultura andina de mantos funerários elaborados", "Sociedade antiga da costa sul do Peru, conhecida por seus têxteis.", "trivia", 3, 3, ["andes", "cultura-material"], ["larco-peru"]],
    ["quipu", "Contas do império presas em nós", "Sistema inca de cordões e nós usado para registrar informações.", "association", 2, 4, ["andes", "registro"], ["larco-peru"]],
    ["teotihuacan", "Metrópole antiga das pirâmides do Sol e da Lua", "Grande cidade mesoamericana que floresceu no centro do México antes dos mexicas.", "trivia", 2, 4, ["mesoamerica", "cidade"], ["inah-mexico"]],
    ["tenochtitlán", "Capital mexica erguida numa ilha", "Capital do império mexica no local da atual Cidade do México.", "trivia", 2, 4, ["mesoamerica", "cidade"], ["inah-mexico"]],
    ["chancay", "Cultura costeira peruana de cerâmica preta e branca", "Sociedade pré-inca da costa central do Peru, conhecida por cerâmica e têxteis.", "trivia", 4, 2, ["andes", "cultura-material"], ["larco-peru"]],
    ["tolteca", "De Tula, antes da ascensão mexica", "Relativo à tradição política e cultural centrada em Tula no México pós-clássico.", "trivia", 3, 3, ["mesoamerica", "povo"], ["inah-mexico"]],
    ["wari", "Império andino anterior aos incas", "Estado andino que se expandiu a partir da região de Ayacucho, no atual Peru.", "trivia", 4, 2, ["andes", "imperio"], ["larco-peru"]],
    ["zapoteca", "De Monte Albán e dos vales de Oaxaca", "Relativo a povos originários de Oaxaca, com longa história no sul do México.", "trivia", 3, 3, ["mesoamerica", "povo"], ["inah-mexico"]],
    ["mita", "Trabalho rotativo andino apropriado pelos colonizadores", "Sistema andino de trabalho por turnos, transformado em trabalho compulsório no período colonial.", "association", 3, 3, ["andes", "trabalho"], ["larco-peru"]],
    ["cacicado", "Território político governado por um cacique", "Unidade de organização política indígena liderada por um cacique.", "association", 3, 3, ["americas", "politica"], ["penn-global"]],

    // Brasil colonial, Império e circulação de ideias (45)
    ["aldeamento", "A colonização reuniu povos indígenas sob administração externa", "Povoado indígena organizado por missionários ou autoridades durante a colonização.", "association", 3, 3, ["brasil", "povos-indigenas"], ["funai", "arquivo-nacional", "iphan-missoes"]],
    ["alforria", "A liberdade registrada em carta, mas cercada de limites", "Ato pelo qual uma pessoa escravizada obtinha juridicamente a liberdade.", "association", 2, 4, ["brasil", "escravidao"], ["arquivo-nacional"]],
    ["bandeirante", "Entrou pelo interior atrás de cativos indígenas e riquezas", "Integrante de expedições paulistas que capturavam indígenas e buscavam metais e pedras.", "association", 2, 5, ["brasil", "colonizacao"], ["arquivo-nacional", "funai"]],
    ["capitania", "Um grande lote da América portuguesa no mapa da Coroa", "Divisão territorial colonial cuja administração podia caber a um donatário.", "association", 2, 4, ["brasil", "colonizacao"], ["arquivo-nacional"]],
    ["caravela", "Velas pequenas para travessias muito grandes?", "Embarcação leve usada nas navegações ibéricas dos séculos XV e XVI.", "wordplay", 1, 5, ["navegacao", "colonizacao"], ["national-archives-uk"]],
    ["catequese", "Conversão religiosa como projeto colonial", "Ensino de doutrina cristã, empregado por missionários na colonização.", "association", 2, 4, ["brasil", "religiao"], ["funai", "arquivo-nacional", "iphan-missoes"]],
    ["cativeiro", "Vida submetida ao poder de quem se dizia dono", "Condição de privação de liberdade imposta a pessoas escravizadas.", "association", 2, 5, ["brasil", "escravidao"], ["arquivo-nacional", "unesco-slavery"]],
    ["conjuração", "Na Bahia de 1798, liberdade e igualdade circularam em papéis", "Articulação política contra a ordem vigente; no Brasil, nomeia movimentos como o Baiano de 1798.", "trivia", 3, 3, ["brasil", "revolta"], ["arquivo-nacional"]],
    ["donatário", "Recebia da Coroa a administração de uma capitania", "Pessoa a quem a Coroa portuguesa concedia direitos de administração sobre uma capitania.", "association", 3, 3, ["brasil", "colonizacao"], ["arquivo-nacional"]],
    ["engenho", "Cana, moenda e poder senhorial no mesmo complexo", "Unidade produtiva colonial dedicada sobretudo à fabricação de açúcar.", "association", 1, 5, ["brasil", "economia"], ["arquivo-nacional", "unesco-slavery"]],
    ["feitoria", "Entreposto europeu de troca, estoque e controle costeiro", "Posto comercial fortificado estabelecido por potências marítimas.", "association", 3, 3, ["colonizacao", "comercio"], ["national-archives-uk"]],
    ["capitalismo", "Capital e trabalho assalariado movem este sistema", "Sistema econômico baseado na propriedade privada dos meios de produção e na produção para o mercado.", "association", 2, 5, ["economia", "ideias"], ["loc-industrial"]],
    ["inconfidência", "Em Minas, 1789 não chegou a virar levante", "Conspiração contra o domínio português ocorrida em Minas Gerais no fim do século XVIII.", "trivia", 2, 5, ["brasil", "revolta"], ["arquivo-nacional"]],
    ["jesuíta", "Da ordem que abriu colégios e missões no mundo colonial", "Membro da Companhia de Jesus, ordem religiosa ativa na educação e nas missões coloniais.", "association", 2, 4, ["brasil", "religiao"], ["arquivo-nacional", "iphan-missoes"]],
    ["liberto", "Saiu juridicamente do cativeiro", "Pessoa que deixou a condição legal de escravizada.", "elliptical", 2, 4, ["brasil", "escravidao"], ["arquivo-nacional"]],
    ["vice-rei", "Representava o monarca longe da metrópole", "Governante que exercia autoridade num território em nome do monarca.", "association", 2, 4, ["colonizacao", "politica"], ["arquivo-nacional"]],
    ["malê", "Muçulmano africano na revolta baiana de 1835", "Nome dado na Bahia oitocentista a africanos muçulmanos, protagonistas de uma revolta em 1835.", "trivia", 3, 3, ["brasil", "revolta"], ["arquivo-bahia"]],
    ["navegação", "Fez oceanos virarem rotas de impérios", "Prática e técnica de conduzir embarcações, central à expansão marítima.", "association", 1, 5, ["colonizacao", "navegacao"], ["national-archives-uk"]],
    ["ouvidor", "Magistrado da Coroa que ouvia causas na colônia?", "Funcionário da administração portuguesa encarregado de funções judiciais.", "wordplay", 3, 3, ["brasil", "administracao"], ["arquivo-nacional"]],
    ["pelourinho", "Coluna pública de punição e poder colonial", "Coluna de pedra associada à autoridade municipal e a castigos públicos.", "association", 2, 5, ["brasil", "escravidao"], ["iphan-material", "arquivo-nacional"]],
    ["quilombo", "Comunidade de resistência à escravização", "Comunidade com trajetória histórica ligada à resistência de pessoas negras à opressão escravista.", "association", 1, 5, ["brasil", "resistencia"], ["palmares"]],
    ["redução", "Aldeamento missionário no vocabulário jesuítico", "Povoado organizado por missionários para reunir e converter populações indígenas.", "association", 3, 3, ["americas", "povos-indigenas"], ["funai", "iphan-missoes"]],
    ["regente", "Governa enquanto o soberano não pode", "Pessoa que exerce temporariamente o poder monárquico em lugar do soberano.", "association", 2, 5, ["brasil", "monarquia"], ["arquivo-nacional"]],
    ["socialismo", "A propriedade e a desigualdade entram no centro da crítica", "Conjunto de doutrinas que propõem controle social ou coletivo dos meios de produção.", "association", 2, 5, ["economia", "ideias"], ["loc-industrial"]],
    ["senzala", "Moradia imposta a escravizados numa propriedade rural", "Alojamento destinado a pessoas escravizadas em propriedades do Brasil colonial e imperial.", "association", 1, 5, ["brasil", "escravidao"], ["arquivo-nacional", "unesco-slavery"]],
    ["sesmaria", "Terra concedida sob condição de aproveitamento", "Concessão de terra usada pela Coroa portuguesa, condicionada ao cultivo.", "association", 3, 3, ["brasil", "terra"], ["arquivo-nacional"]],
    ["tráfico negreiro", "O Atlântico transformado em rota de cativeiro", "Comércio forçado de africanos escravizados, sobretudo através do Atlântico.", "association", 2, 5, ["brasil", "escravidao"], ["arquivo-nacional", "unesco-slavery"]],
    ["tropeiro", "Levava mercadoria no lombo das mulas pelo interior", "Condutor de tropas de animais que transportavam mercadorias por rotas terrestres.", "association", 1, 5, ["brasil", "comercio"], ["arquivo-nacional"]],
    ["abolicionista", "Fez campanha para que o cativeiro acabasse", "Participante do movimento político e social pelo fim da escravidão.", "association", 2, 5, ["brasil", "direitos"], ["arquivo-nacional", "unesco-slavery"]],
    ["escravização", "Violência que transforma uma pessoa livre em cativa", "Processo de submeter pessoas à condição de escravizadas.", "association", 2, 5, ["brasil", "escravidao"], ["arquivo-nacional", "unesco-slavery"]],
    ["Tiradentes", "O alferes executado virou herói cívico da República", "Participante da Inconfidência Mineira executado em 1792 e depois convertido em símbolo nacional.", "trivia", 2, 5, ["brasil", "memoria"], ["arquivo-nacional"]],
    ["corte", "Onde o monarca governa cercado de casa e política", "Conjunto do soberano, sua residência e as pessoas e instituições que o cercam.", "association", 2, 5, ["monarquia", "sociedade"], ["arquivo-nacional"]],
    ["metrópole", "Centro imperial que manda na colônia", "Estado ou cidade central que exerce domínio sobre territórios coloniais.", "association", 2, 5, ["colonizacao", "politica"], ["national-archives-uk"]],
    ["mercantilismo", "Metais, balança favorável e monopólio no receituário dos reinos", "Conjunto de práticas econômicas de Estados europeus modernos voltadas a comércio controlado e acumulação de riqueza.", "association", 3, 3, ["economia", "estado"], ["national-archives-uk"]],
    ["monarquia", "Um soberano na chefia do Estado", "Forma de governo cuja chefia é exercida por monarca.", "elliptical", 1, 5, ["politica", "estado"], ["arquivo-nacional"]],
    ["independência", "A colônia rompe o vínculo político com a metrópole", "Processo pelo qual um território deixa a subordinação a outro Estado.", "association", 1, 5, ["politica", "colonizacao"], ["arquivo-nacional", "archives-us"]],
    ["constituição", "A lei maior organiza poderes e direitos", "Documento jurídico fundamental que estrutura o Estado e estabelece direitos.", "association", 1, 5, ["politica", "direitos"], ["camara-constituicoes"]],
    ["liberalismo", "Liberdades individuais e limites ao poder no centro", "Tradição política que valoriza direitos individuais, governo limitado e igualdade jurídica.", "association", 2, 5, ["politica", "ideias"], ["archives-us", "national-archives-uk"]],
    ["fascismo", "Ultranacionalismo autoritário em camisa de partido", "Ideologia e movimento autoritário ultranacionalista surgido na Europa do século XX.", "association", 2, 5, ["politica", "autoritarismo"], ["ushmm"]],
    ["nazismo", "Racismo de Estado no regime de Hitler", "Ideologia do regime nacional-socialista alemão, racista, antissemita e expansionista.", "trivia", 1, 5, ["politica", "holocausto"], ["ushmm"]],
    ["parlamento", "Debate e voto numa casa legislativa", "Assembleia representativa que exerce funções legislativas.", "association", 1, 5, ["politica", "instituicao"], ["national-archives-uk"]],
    ["absolutismo", "O rei reivindica poder sem contrapesos efetivos", "Modelo de monarquia em que o soberano concentra amplos poderes.", "association", 2, 4, ["politica", "monarquia"], ["national-archives-uk"]],
    ["iluminismo", "A razão do século XVIII sob nova luz?", "Movimento intelectual que valorizou razão, crítica e investigação no século XVIII.", "wordplay", 2, 5, ["ideias", "seculo-xviii"], ["british-galleries"]],
    ["humanismo", "Textos clássicos e ação humana voltam ao primeiro plano", "Corrente intelectual renascentista voltada aos estudos clássicos e às capacidades humanas.", "association", 3, 4, ["ideias", "renascimento"], ["british-galleries"]],
    ["renascimento", "A Antiguidade ganha nova vida na Europa moderna", "Movimento cultural europeu que retomou referências clássicas entre os séculos XIV e XVI.", "association", 1, 5, ["cultura", "europa"], ["british-galleries"]],

    // Brasil republicano, revoltas, cidadania e mundo contemporâneo (35)
    ["balaiada", "Revolta regencial de vaqueiros e artesãos no Maranhão", "Revolta popular ocorrida no Maranhão e no Piauí entre 1838 e 1841.", "trivia", 3, 3, ["brasil", "revolta"], ["arquivo-nacional"]],
    ["cabanagem", "Insurgentes populares chegaram a governar o Grão-Pará", "Revolta regencial iniciada em 1835 no Grão-Pará, com ampla participação popular.", "trivia", 3, 4, ["brasil", "revolta"], ["arquivo-nacional"]],
    ["cangaço", "Bandos armados entre sertão, coronéis e volantes", "Fenômeno histórico de grupos armados itinerantes no Nordeste, sobretudo entre os séculos XIX e XX.", "association", 2, 5, ["brasil", "sertão"], ["cpdoc"]],
    ["canudos", "Conselheiro, Belo Monte e uma guerra no sertão baiano", "Comunidade de Belo Monte destruída pelo Exército brasileiro na guerra de 1896 a 1897.", "trivia", 2, 5, ["brasil", "revolta"], ["cpdoc"]],
    ["coronelismo", "O mando local pressionava o voto na Primeira República", "Sistema de poder local oligárquico ligado a chefes políticos e controle eleitoral.", "association", 2, 5, ["brasil", "politica"], ["cpdoc"]],
    ["contestado", "Guerra entre Paraná e Santa Catarina — e muito além da divisa", "Conflito social e territorial no Sul do Brasil entre 1912 e 1916.", "trivia", 3, 4, ["brasil", "revolta"], ["cpdoc"]],
    ["ditadura", "Poder concentrado, oposição reprimida", "Regime político autoritário que restringe participação, direitos e oposição.", "elliptical", 1, 5, ["politica", "autoritarismo"], ["arquivo-nacional", "cpdoc"]],
    ["diretas", "As eleições já no grito das ruas", "Nome abreviado do movimento brasileiro por eleição presidencial direta em 1983 e 1984.", "association", 2, 5, ["brasil", "redemocratizacao"], ["cpdoc"]],
    ["Estado Novo", "Vargas fechou o Congresso e governou sob a Carta de 1937", "Regime ditatorial brasileiro instaurado por Getúlio Vargas em 1937 e encerrado em 1945.", "trivia", 2, 5, ["brasil", "autoritarismo"], ["cpdoc"]],
    ["farroupilha", "A longa revolta regencial do Rio Grande do Sul", "Revolta ocorrida no sul do Império do Brasil entre 1835 e 1845.", "trivia", 2, 5, ["brasil", "revolta"], ["arquivo-nacional"]],
    ["integralismo", "Sigma, camisas verdes e nacionalismo autoritário", "Movimento político brasileiro de inspiração fascista ativo sobretudo nos anos 1930.", "trivia", 3, 3, ["brasil", "autoritarismo"], ["cpdoc"]],
    ["jagunço", "Homem armado a serviço de chefes locais no sertão", "Combatente ou guarda armado ligado a chefes políticos e proprietários rurais.", "association", 2, 4, ["brasil", "sertão"], ["cpdoc"]],
    ["praieira", "A última grande revolta liberal provincial do Império", "Revolta liberal ocorrida em Pernambuco entre 1848 e 1850.", "trivia", 3, 3, ["brasil", "revolta"], ["arquivo-nacional"]],
    ["sabinada", "Revolta regencial baiana batizada por seu líder", "Revolta ocorrida na Bahia entre 1837 e 1838 durante o período regencial.", "trivia", 3, 3, ["brasil", "revolta"], ["arquivo-nacional"]],
    ["tenentismo", "Jovens oficiais contestaram a República oligárquica", "Movimento político-militar de jovens oficiais brasileiros na década de 1920.", "association", 3, 4, ["brasil", "militares"], ["cpdoc"]],
    ["trabalhismo", "Direitos sociais e representação dos trabalhadores na política", "Corrente política brasileira ligada à organização do trabalho e a direitos sociais, forte a partir da Era Vargas.", "association", 2, 4, ["brasil", "trabalho"], ["cpdoc"]],
    ["varguismo", "Projeto político que leva o nome de Getúlio", "Conjunto de práticas e correntes políticas associadas a Getúlio Vargas.", "association", 3, 4, ["brasil", "politica"], ["cpdoc"]],
    ["anistia", "A lei esquece a pena, mas a memória continua?", "Medida jurídica que extingue consequências penais de determinados atos.", "wordplay", 2, 5, ["direitos", "redemocratizacao"], ["arquivo-nacional"]],
    ["censura", "Tesoura oficial sobre imprensa, arte e fala", "Controle ou proibição da circulação de informações e expressões.", "association", 1, 5, ["direitos", "autoritarismo"], ["arquivo-nacional"]],
    ["cidadania", "Direitos no papel e participação na vida pública", "Condição de pertencimento político acompanhada de direitos e deveres.", "association", 1, 5, ["direitos", "politica"], ["camara-constituicoes", "un-direitos"]],
    ["constituinte", "Assembleia chamada para escrever as regras fundamentais", "Assembleia eleita ou convocada para elaborar uma constituição.", "association", 2, 5, ["politica", "constituicao"], ["camara-constituicoes"]],
    ["democracia", "Governo legitimado pela participação do povo", "Regime em que o poder político deriva da participação e escolha dos cidadãos.", "association", 1, 5, ["politica", "direitos"], ["camara-constituicoes", "un-direitos"]],
    ["sufrágio", "Direito conquistado para entrar na urna", "Direito político de votar em eleições.", "association", 2, 5, ["politica", "direitos"], ["tse-voto"]],
    ["voto", "Escolha que cabe numa urna", "Manifestação formal da escolha de um eleitor.", "association", 1, 5, ["politica", "eleicao"], ["tse-voto"]],
    ["revolução", "A ordem antiga vira de ponta-cabeça", "Transformação rápida e profunda de uma ordem política, social ou econômica.", "association", 1, 5, ["politica", "mudanca-social"], ["national-archives-uk"]],
    ["bastilha", "Sua queda virou símbolo da Revolução Francesa", "Fortaleza-prisão parisiense tomada em 14 de julho de 1789.", "trivia", 1, 5, ["franca", "revolucao"], ["national-archives-uk"]],
    ["burguesia", "Do burgo ao protagonismo econômico moderno?", "Grupo social historicamente ligado à propriedade, ao comércio e ao capital.", "wordplay", 2, 5, ["sociedade", "economia"], ["loc-industrial"]],
    ["guilhotina", "Lâmina que marcou o Terror francês", "Máquina de execução por decapitação associada à Revolução Francesa.", "trivia", 1, 5, ["franca", "revolucao"], ["national-archives-uk"]],
    ["industrialização", "Fábricas multiplicam máquinas, cidades e operários", "Processo de expansão da produção mecanizada e do sistema fabril.", "association", 2, 5, ["economia", "trabalho"], ["loc-industrial"]],
    ["ludismo", "Máquinas quebradas como protesto de trabalhadores", "Movimento de trabalhadores ingleses que atacaram máquinas no início do século XIX.", "association", 3, 3, ["trabalho", "industrializacao"], ["national-archives-uk", "loc-industrial"]],
    ["proletariado", "Classe que vive de vender sua força de trabalho", "Classe de trabalhadores assalariados sem controle dos meios de produção.", "association", 2, 5, ["trabalho", "sociedade"], ["loc-industrial"]],
    ["sindicato", "Trabalhadores reunidos para negociar e reivindicar", "Associação que representa interesses profissionais e trabalhistas.", "association", 1, 5, ["trabalho", "direitos"], ["loc-industrial"]],
    ["trincheira", "Guerra cavada no chão", "Vala defensiva usada por tropas, emblemática da Primeira Guerra Mundial.", "association", 1, 5, ["guerra", "seculo-xx"], ["national-archives-uk"]],
    ["holocausto", "Seis milhões de judeus assassinados pelo regime nazista e seus colaboradores", "Perseguição e assassinato sistemático de judeus europeus pelo regime nazista e seus colaboradores.", "trivia", 1, 5, ["holocausto", "direitos"], ["ushmm"]],
    ["genocídio", "Crime voltado a destruir um grupo humano", "Crime definido internacionalmente pela intenção de destruir, no todo ou em parte, um grupo protegido.", "association", 2, 5, ["direitos", "violencia"], ["un-genocidio", "ushmm"]],
  ],
} as const satisfies BiomeBundle;

export const historiaEntries = entriesFromBundle(historiaBundle);

// Auditoria editorial: 250 registros, 250 respostas normalizadas únicas; duas pistas e fontes revisadas em 2026-08-24.
