import { entriesFromBundle, type BiomeBundle } from "./shared.js";

const naturezaBundle = {
  biome: "natureza",
  prefix: "nat",
  editorialSource: "curadoria-autoral-natureza-v1",
  sources: [
    {
      sourceId: "nat-ctfb",
      title: "Catálogo Taxonômico da Fauna do Brasil",
      url: "https://ipt.jbrj.gov.br/jbrj/resource?r=catalogo_taxonomico_da_fauna_do_brasil&request_locale=pt",
      license: "CC BY 4.0; usado apenas como referência factual e taxonômica",
      role: "factual",
    },
    {
      sourceId: "nat-icmbio-fauna",
      title: "ICMBio — Fauna Brasileira",
      url: "https://www.gov.br/icmbio/pt-br/assuntos/biodiversidade/fauna-brasileira",
      license: "publicação institucional; conteúdo das pistas é autoral",
      role: "factual",
    },
    {
      sourceId: "nat-icmbio-cavernas",
      title: "ICMBio/Cecav — Centro Nacional de Pesquisa e Conservação de Cavernas",
      url: "https://www.gov.br/icmbio/pt-br/assuntos/centros-de-pesquisa/cavernas",
      license: "CC BY-ND 3.0; usado apenas como referência factual",
      role: "factual",
    },
    {
      sourceId: "nat-flora-funga",
      title: "Flora e Funga do Brasil",
      url: "https://ipt.jbrj.gov.br/jbrj/resource?r=lista_especies_flora_brasil",
      license: "CC BY 4.0; usado apenas como referência factual e taxonômica",
      role: "factual",
    },
    {
      sourceId: "nat-ibge-ambiental",
      title: "IBGE — Informações Ambientais",
      url: "https://www.ibge.gov.br/geociencias/cartas-e-mapas/informacoes-ambientais.html",
      license: "publicação institucional; conteúdo das pistas é autoral",
      role: "factual",
    },
    {
      sourceId: "nat-ibge-atlas",
      title: "IBGE — Atlas Geográfico Escolar",
      url: "https://www.ibge.gov.br/geociencias/atlas/nacional/16633-atlas-geografico-escolar.html",
      license: "publicação institucional; conteúdo das pistas é autoral",
      role: "factual",
    },
    {
      sourceId: "nat-ibge-biomas",
      title: "IBGE Educa — Biomas Brasileiros",
      url: "https://educa.ibge.gov.br/jovens/conheca-o-brasil/territorio/19635-ecossistemas.html",
      license: "publicação institucional; conteúdo das pistas é autoral",
      role: "factual",
    },
    {
      sourceId: "nat-ibge-vegetacao",
      title: "IBGE Educa — Tipos de Vegetação do Brasil",
      url: "https://educa.ibge.gov.br/jovens/materias-especiais/23226-conhecendo-os-tipos-de-vegetacao-do-brasil.html",
      license: "publicação institucional; conteúdo das pistas é autoral",
      role: "factual",
    },
    {
      sourceId: "nat-mma-biodiversidade",
      title: "Ministério do Meio Ambiente — Biodiversidade e Biomas",
      url: "https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biodiversidade",
      license: "publicação institucional; conteúdo das pistas é autoral",
      role: "factual",
    },
    {
      sourceId: "nat-mma-areas-umidas",
      title: "Ministério do Meio Ambiente — Áreas Úmidas",
      url: "https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biomas-e-ecossistemas/areas-umidas",
      license: "publicação institucional; conteúdo das pistas é autoral",
      role: "factual",
    },
    {
      sourceId: "nat-openstax-ecologia",
      title: "OpenStax Biology 2e — Population and Community Ecology Key Terms",
      url: "https://openstax.org/books/biology-2e/pages/45-key-terms",
      license: "CC BY-NC-SA 4.0; usado apenas como referência factual",
      role: "factual",
    },
    {
      sourceId: "nat-openstax-biomas",
      title: "OpenStax Biology 2e — Terrestrial Biomes",
      url: "https://openstax.org/books/biology-2e/pages/44-3-terrestrial-biomes",
      license: "CC BY-NC-SA 4.0; usado apenas como referência factual",
      role: "factual",
    },
    {
      sourceId: "nat-openstax-ecossistemas",
      title: "OpenStax Biology 2e — Ecosystems Key Terms",
      url: "https://openstax.org/books/biology-2e/pages/46-key-terms",
      license: "CC BY-NC-SA 4.0; usado apenas como referência factual",
      role: "factual",
    },
    {
      sourceId: "nat-openstax-hibernacao",
      title: "OpenStax Biology 2e — Animal Form and Function",
      url: "https://openstax.org/books/biology-2e/pages/33-1-animal-form-and-function",
      license: "CC BY-NC-SA 4.0; usado apenas como referência factual",
      role: "factual",
    },
    {
      sourceId: "unitex-pb",
      title: "Unitex/GramLab — recursos linguísticos para Português do Brasil",
      url: "https://github.com/UnitexGramLab/unitex-lingua/tree/master/pt-BR",
      license: "LGPLLR",
      role: "lexical",
    },
  ],
  records: [
    // Mamíferos — 30
    ["onça-pintada", "Rosetas na pele e passos discretos na mata", "Grande felino americano de pelagem amarela com manchas em roseta.", "association", 1, 5, ["fauna", "mamiferos"], ["nat-ctfb", "nat-icmbio-fauna"]],
    ["lobo-guará", "Pernas altas passeando pelo cerrado", "Canídeo sul-americano alto, esguio e de pelagem avermelhada.", "association", 1, 5, ["fauna", "mamiferos"], ["nat-ctfb", "nat-icmbio-fauna"]],
    ["tamanduá", "Focinho comprido diante de um formigueiro", "Mamífero que captura formigas e cupins com a língua longa.", "association", 1, 5, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["tatu", "Carapaça com pernas, no chão da mata", "Mamífero terrestre protegido por placas articuladas.", "association", 1, 5, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["capivara", "A maior roedora, quase sempre perto d'água", "Maior roedor vivo, de hábitos semiaquáticos.", "trivia", 1, 5, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["anta", "Grandona da mata com uma pequena tromba", "Maior mamífero terrestre nativo do Brasil, com focinho curto e móvel.", "trivia", 1, 5, ["fauna", "mamiferos"], ["nat-ctfb", "nat-icmbio-fauna"]],
    ["quati", "Focinho curioso e cauda de anéis", "Mamífero de focinho alongado e cauda comprida geralmente anelada.", "association", 1, 5, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["cutia", "Roedora da mata que enterra sementes", "Roedor tropical de pernas finas que dispersa sementes.", "association", 2, 4, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["paca", "Roedora pintada que ronda rios à noite", "Roedor de pelagem castanha marcada por fileiras de manchas claras.", "association", 2, 4, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["preguiça", "Uma vida suspensa e sem pressa", "Mamífero arborícola de movimentos lentos e garras longas.", "association", 1, 5, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["macaco", "Primate que faz da copa o seu caminho", "Nome comum de diversos primatas não humanos.", "association", 1, 5, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["bugio", "Primate cuja voz atravessa a floresta", "Macaco americano conhecido por vocalizações muito fortes.", "association", 2, 4, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["sagui", "Pequeno primata de unhas em forma de garra", "Macaco pequeno da família dos calitriquídeos.", "trivia", 2, 4, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["mico-leão", "Juba em miniatura entre os galhos", "Pequeno primata brasileiro com pelos longos ao redor da cabeça.", "association", 2, 5, ["fauna", "mamiferos"], ["nat-ctfb", "nat-icmbio-fauna"]],
    ["muriqui", "O maior macaco das Américas é brasileiro", "Grande primata nativo da Mata Atlântica.", "trivia", 3, 3, ["fauna", "mamiferos"], ["nat-ctfb", "nat-icmbio-fauna"]],
    ["boto-rosa", "Cetáceo de cor incomum que sobe rios amazônicos", "Golfinho de água doce da bacia Amazônica.", "association", 1, 5, ["fauna", "mamiferos-aquaticos"], ["nat-ctfb"]],
    ["peixe-boi", "Pasta plantas sem sair da água", "Grande mamífero aquático herbívoro de corpo arredondado.", "association", 1, 5, ["fauna", "mamiferos-aquaticos"], ["nat-ctfb", "nat-icmbio-fauna"]],
    ["lontra", "Caçadora de rio com corpo de nadadora", "Mamífero semiaquático de corpo alongado e pés adaptados à natação.", "association", 1, 5, ["fauna", "mamiferos-aquaticos"], ["nat-ctfb"]],
    ["ariranha", "A gigante entre as lontras sul-americanas", "Grande mamífero semiaquático social da família dos mustelídeos.", "trivia", 2, 4, ["fauna", "mamiferos-aquaticos"], ["nat-ctfb", "nat-icmbio-fauna"]],
    ["jaguatirica", "Felina pintada, menor que a onça", "Felino silvestre americano de porte médio e pelagem manchada.", "association", 2, 4, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["gato-maracajá", "Felino pequeno que desce troncos de cabeça", "Felino arborícola americano de olhos grandes e cauda longa.", "trivia", 3, 3, ["fauna", "mamiferos"], ["nat-ctfb", "nat-icmbio-fauna"]],
    ["veado", "Galhadas podem coroar esse habitante da mata", "Nome comum de mamíferos ruminantes da família dos cervídeos.", "association", 1, 5, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["cateto", "Porco-do-mato de colar claro", "Mamífero silvestre parecido com porco, geralmente reconhecido pelo colar esbranquiçado.", "association", 2, 4, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["queixada", "Porco-do-mato que anda em grandes bandos", "Mamífero silvestre social de queixo claro e cheiro forte.", "association", 2, 4, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["morcego", "O único mamífero de voo sustentado", "Mamífero alado da ordem dos quirópteros.", "trivia", 1, 5, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["gambá", "Bolsa para os filhotes e fama pelo cheiro", "Marsupial americano que pode liberar secreção de odor forte.", "association", 1, 5, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["tamanduá-bandeira", "Carrega no corpo uma cauda de estandarte?", "Grande mamífero sul-americano, especializado em formigas e cupins, de cauda muito volumosa.", "wordplay", 2, 5, ["fauna", "mamiferos"], ["nat-ctfb", "nat-icmbio-fauna"]],
    ["tatu-bola", "Quando ameaçado, fecha a armadura em esfera", "Mamífero de placas móveis capaz de enrolar o corpo.", "association", 2, 5, ["fauna", "mamiferos"], ["nat-ctfb", "nat-icmbio-fauna"]],
    ["irara", "Mustelídea escura que escala árvores", "Mamífero ágil da família das lontras e doninhas, comum em florestas americanas.", "association", 3, 3, ["fauna", "mamiferos"], ["nat-ctfb"]],
    ["mão-pelada", "Guaxinim brasileiro de máscara e dedos hábeis", "Mamífero noturno de face mascarada que costuma buscar alimento perto da água.", "association", 2, 4, ["fauna", "mamiferos"], ["nat-ctfb"]],

    // Aves — 30
    ["arara", "Bico curvo e longa cauda em cores tropicais", "Grande ave da família dos psitacídeos, de cauda longa e plumagem colorida.", "association", 1, 5, ["fauna", "aves"], ["nat-ctfb"]],
    ["tucano", "Um bico enorme pousado na copa", "Ave tropical de bico grande e colorido.", "association", 1, 5, ["fauna", "aves"], ["nat-ctfb"]],
    ["papagaio", "Bico curvo e talento para imitar vozes", "Ave psitacídea conhecida por reproduzir sons.", "association", 1, 5, ["fauna", "aves"], ["nat-ctfb"]],
    ["periquito", "Pequeno psitacídeo que costuma voar em bando", "Ave pequena, de bico curvo, aparentada aos papagaios.", "association", 1, 5, ["fauna", "aves"], ["nat-ctfb"]],
    ["beija-flor", "Paira diante de corolas para tomar néctar", "Ave muito pequena capaz de manter voo estacionário.", "association", 1, 5, ["fauna", "aves"], ["nat-ctfb"]],
    ["bem-te-vi", "Canta o próprio nome nos quintais?", "Ave amarela e parda cujo chamado lembra uma frase em português.", "wordplay", 1, 5, ["fauna", "aves"], ["nat-ctfb"]],
    ["sabiá", "Cantor alaranjado de muitos jardins", "Ave canora comum no Brasil, frequentemente vista em áreas arborizadas.", "association", 1, 5, ["fauna", "aves"], ["nat-ctfb"]],
    ["joão-de-barro", "Pedreiro alado de casa arredondada", "Ave que constrói com argila um ninho fechado, semelhante a um forno.", "association", 1, 5, ["fauna", "aves"], ["nat-ctfb"]],
    ["quero-quero", "Sentinela barulhenta de campos e gramados", "Ave campestre de pernas longas que defende o território com gritos.", "association", 1, 5, ["fauna", "aves"], ["nat-ctfb"]],
    ["ema", "Corredora sul-americana que não levanta voo", "Grande ave terrestre incapaz de voar.", "association", 1, 5, ["fauna", "aves"], ["nat-ctfb"]],
    ["seriema", "Pernas longas e canto alto no chão do cerrado", "Ave terrestre sul-americana, alta e corredora.", "association", 2, 4, ["fauna", "aves"], ["nat-ctfb"]],
    ["harpia", "Águia da floresta de garras poderosas", "Grande ave de rapina que vive em florestas tropicais americanas.", "association", 2, 4, ["fauna", "aves"], ["nat-ctfb", "nat-icmbio-fauna"]],
    ["gavião", "Rapina em ronda pelo céu", "Nome comum de várias aves predadoras de bico curvo e garras fortes.", "elliptical", 1, 5, ["fauna", "aves"], ["nat-ctfb"]],
    ["coruja", "Olhos frontais no turno da noite", "Ave de rapina frequentemente noturna, com olhos voltados para a frente.", "association", 1, 5, ["fauna", "aves"], ["nat-ctfb"]],
    ["urubu", "Faxineiro alado à procura de carniça", "Ave necrófaga que se alimenta sobretudo de animais mortos.", "association", 1, 5, ["fauna", "aves"], ["nat-ctfb"]],
    ["garça", "Pernas compridas à espera do peixe", "Ave aquática de pescoço e pernas longos.", "association", 1, 5, ["fauna", "aves-aquaticas"], ["nat-ctfb"]],
    ["colhereiro", "Ave rosada de bico feito talher?", "Ave aquática de bico largo e achatado na ponta.", "wordplay", 2, 4, ["fauna", "aves-aquaticas"], ["nat-ctfb"]],
    ["tuiuiú", "Papo vermelho sobre as águas pantaneiras", "Grande ave pernalta, símbolo do Pantanal.", "association", 2, 5, ["fauna", "aves-aquaticas"], ["nat-ctfb"]],
    ["flamingo", "Pernas altas, plumagem rosa e bico curvado", "Ave aquática rosada que se alimenta filtrando a água.", "association", 1, 5, ["fauna", "aves-aquaticas"], ["nat-ctfb"]],
    ["pinguim", "Ave marinha de fraque natural e voo submerso", "Ave marinha incapaz de voar, adaptada à natação.", "association", 1, 5, ["fauna", "aves-marinhas"], ["nat-ctfb"]],
    ["albatroz", "Planador oceânico de asas muito longas", "Grande ave marinha que percorre longas distâncias sobre o oceano.", "association", 2, 4, ["fauna", "aves-marinhas"], ["nat-ctfb", "nat-icmbio-fauna"]],
    ["gaivota", "Asas sobre a praia e grito sobre as ondas", "Ave costeira de plumagem geralmente branca e cinza.", "association", 1, 5, ["fauna", "aves-marinhas"], ["nat-ctfb"]],
    ["pelicano", "Pescador de bolsa no bico", "Grande ave aquática com saco expansível sob o bico.", "association", 1, 5, ["fauna", "aves-aquaticas"], ["nat-ctfb"]],
    ["martim-pescador", "Mergulho de bico atrás de peixe", "Ave de bico longo que captura presas mergulhando na água.", "association", 2, 4, ["fauna", "aves-aquaticas"], ["nat-ctfb"]],
    ["pica-pau", "Bate à porta da árvore sem querer entrar?", "Ave que perfura troncos com o bico em busca de alimento ou abrigo.", "wordplay", 1, 5, ["fauna", "aves"], ["nat-ctfb"]],
    ["canário", "Pequeno cantor de plumagem muitas vezes amarela", "Ave canora pequena, conhecida pelo canto melodioso.", "association", 1, 5, ["fauna", "aves"], ["nat-ctfb"]],
    ["curió", "Pequeno pássaro de canto muito apreciado", "Ave granívora brasileira, de bico curto e canto marcante.", "association", 2, 4, ["fauna", "aves"], ["nat-ctfb"]],
    ["anu", "Ave preta que cruza pastos em grupo", "Ave de cauda longa, comum em campos e áreas abertas.", "association", 2, 4, ["fauna", "aves"], ["nat-ctfb"]],
    ["jacutinga", "Ave escura de mata atlântica, com mancha branca na asa", "Grande ave florestal brasileira da família dos cracídeos.", "association", 3, 3, ["fauna", "aves"], ["nat-ctfb", "nat-icmbio-fauna"]],
    ["mutum", "Cracídeo grande de penacho encurvado", "Ave florestal robusta, aparentada aos jacus.", "association", 3, 3, ["fauna", "aves"], ["nat-ctfb"]],

    // Répteis, anfíbios e peixes — 35
    ["jacaré", "Réptil de focinho largo à flor d'água", "Crocodiliano de água doce, comum em regiões tropicais das Américas.", "association", 1, 5, ["fauna", "repteis"], ["nat-ctfb"]],
    ["calango", "Lagarto ligeiro tomando sol na pedra", "Nome comum de pequenos lagartos terrestres encontrados em áreas abertas do Brasil.", "association", 1, 5, ["fauna", "repteis"], ["nat-ctfb"]],
    ["tartaruga", "Casco e nadadeiras numa longa travessia", "Réptil quelônio, geralmente aquático, protegido por casco.", "association", 1, 5, ["fauna", "repteis"], ["nat-ctfb", "nat-icmbio-fauna"]],
    ["jabuti", "Casco alto e passos lentos em terra firme", "Quelônio terrestre de patas grossas e casco arqueado.", "association", 1, 5, ["fauna", "repteis"], ["nat-ctfb"]],
    ["cágado", "Quelônio de água doce com patas e dedos", "Réptil de casco que vive principalmente em rios e lagoas.", "association", 2, 4, ["fauna", "repteis"], ["nat-ctfb"]],
    ["cobra", "Corpo comprido que avança sem pernas", "Nome comum dos répteis alongados e sem membros da subordem das serpentes.", "association", 1, 5, ["fauna", "repteis"], ["nat-ctfb"]],
    ["sucuri", "Gigante aquática que vence a presa pelo aperto", "Grande serpente sul-americana sem veneno, adaptada à água.", "association", 1, 5, ["fauna", "repteis"], ["nat-ctfb"]],
    ["jiboia", "Constritora das matas sem bote venenoso", "Serpente americana não peçonhenta que mata presas por constrição.", "association", 1, 5, ["fauna", "repteis"], ["nat-ctfb"]],
    ["cascavel", "O guizo avisa antes do bote", "Serpente peçonhenta com chocalho na ponta da cauda.", "association", 1, 5, ["fauna", "repteis"], ["nat-ctfb"]],
    ["cobra-coral", "Anéis vistosos numa serpente de veneno potente", "Nome comum de serpentes listradas, incluindo espécies peçonhentas do gênero Micrurus.", "association", 2, 4, ["fauna", "repteis"], ["nat-ctfb"]],
    ["iguana", "Lagarto arborícola com crista no dorso", "Grande lagarto herbívoro tropical, geralmente verde quando jovem.", "association", 1, 5, ["fauna", "repteis"], ["nat-ctfb"]],
    ["teiú", "Lagarto grande que prova o ar com a língua bifurcada", "Grande lagarto terrestre sul-americano de dieta variada.", "association", 2, 4, ["fauna", "repteis"], ["nat-ctfb"]],
    ["sapo", "Anfíbio de pele rugosa no jardim", "Nome comum de anfíbios anuros geralmente terrestres e de corpo robusto.", "association", 1, 5, ["fauna", "anfibios"], ["nat-ctfb"]],
    ["rã-touro", "Coaxa grande e chegou de fora", "Grande anfíbio de origem norte-americana introduzido no Brasil.", "association", 3, 3, ["fauna", "anfibios"], ["nat-ctfb"]],
    ["perereca", "Anfíbia que sobe com discos nos dedos", "Anuro geralmente arborícola, com pontas adesivas nos dedos.", "association", 1, 5, ["fauna", "anfibios"], ["nat-ctfb"]],
    ["girino", "Antes do salto, uma cauda na água", "Fase larval aquática de sapos, rãs e pererecas.", "association", 1, 5, ["fauna", "anfibios"], ["nat-ctfb"]],
    ["cururu", "Sapo grande de glândulas atrás dos olhos", "Nome comum de anfíbios robustos do gênero Rhinella.", "association", 2, 4, ["fauna", "anfibios"], ["nat-ctfb"]],
    ["cecília", "A anfíbia que parece uma cobra", "Anfíbio alongado e sem patas, também chamado cobra-cega.", "association", 3, 3, ["fauna", "anfibios"], ["nat-ctfb"]],
    ["tubarão", "Fileiras de dentes cortando o mar", "Peixe cartilaginoso marinho de corpo hidrodinâmico.", "association", 1, 5, ["fauna", "peixes"], ["nat-ctfb"]],
    ["raia", "Peixe achatado que ondula como asa", "Peixe cartilaginoso de corpo largo e achatado.", "association", 1, 5, ["fauna", "peixes"], ["nat-ctfb"]],
    ["cavalo-marinho", "Peixe que nada de pé e leva filhotes no ventre paterno", "Pequeno peixe de águas salgadas, com cabeça angulosa e cauda preênsil.", "trivia", 1, 5, ["fauna", "peixes"], ["nat-ctfb"]],
    ["sardinha", "Pequena prateada que viaja em cardumes", "Peixe marinho pequeno e prateado, comum em grandes grupos.", "association", 1, 5, ["fauna", "peixes"], ["nat-ctfb"]],
    ["atum", "Nadador veloz do oceano aberto", "Grande peixe marinho de corpo fusiforme.", "association", 1, 5, ["fauna", "peixes"], ["nat-ctfb"]],
    ["traíra", "Caçadora de emboscada sob a água doce", "Peixe predador sul-americano de corpo alongado e boca com dentes fortes.", "association", 1, 5, ["fauna", "peixes"], ["nat-ctfb"]],
    ["pirarucu", "Gigante amazônico que sobe para respirar", "Grande peixe de água doce amazônico capaz de captar ar atmosférico.", "association", 1, 5, ["fauna", "peixes"], ["nat-ctfb"]],
    ["piranha", "Dentes afiados em rios sul-americanos", "Peixe de água doce de corpo comprimido e dentição cortante.", "association", 1, 5, ["fauna", "peixes"], ["nat-ctfb"]],
    ["tambaqui", "Frutos da mata entram no cardápio deste peixe amazônico", "Grande peixe amazônico de água doce, de corpo alto e dieta onívora.", "association", 2, 4, ["fauna", "peixes"], ["nat-ctfb"]],
    ["dourado", "Predador de rio com brilho de ouro?", "Peixe sul-americano de água doce, corpo amarelado e hábito predador.", "wordplay", 2, 4, ["fauna", "peixes"], ["nat-ctfb"]],
    ["lambari", "Peixinho prateado de rios e riachos", "Nome comum de diversos peixes pequenos de água doce.", "association", 1, 5, ["fauna", "peixes"], ["nat-ctfb"]],
    ["bagre", "Barbilhões de gato no fundo do rio", "Peixe geralmente de fundo, reconhecido pelos filamentos ao redor da boca.", "association", 1, 5, ["fauna", "peixes"], ["nat-ctfb"]],
    ["robalo", "Caçador costeiro que entra em estuários", "Peixe predador encontrado no litoral e em águas salobras.", "association", 2, 4, ["fauna", "peixes"], ["nat-ctfb"]],
    ["tilápia", "Peixe africano hoje comum em açudes brasileiros", "Peixe de água doce amplamente criado em aquicultura.", "trivia", 1, 5, ["fauna", "peixes"], ["nat-ctfb"]],
    ["cascudo", "Peixe de armadura que raspa o fundo", "Nome comum de peixes de água doce cobertos por placas ósseas e com boca ventral.", "association", 1, 5, ["fauna", "peixes"], ["nat-ctfb"]],
    ["moreia", "Boca entreaberta na fenda do recife", "Peixe marinho alongado que costuma se abrigar em cavidades rochosas.", "association", 2, 4, ["fauna", "peixes"], ["nat-ctfb"]],
    ["baiacu", "Infla o corpo quando o perigo aperta", "Peixe capaz de engolir água ou ar e aumentar muito de volume.", "association", 1, 5, ["fauna", "peixes"], ["nat-ctfb"]],

    // Invertebrados — 25
    ["abelha", "Leva pólen de flor em flor", "Inseto social ou solitário que visita flores e pode produzir mel.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["vespa", "Cintura fina e ferrão à disposição", "Inseto himenóptero geralmente esguio, muitas vezes dotado de ferrão.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["formiga", "Pequena operária de uma grande colônia", "Inseto social que vive em comunidades divididas em castas.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["cupim", "Construtor de montes e comedor de madeira", "Inseto social que se alimenta principalmente de material rico em celulose.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["besouro", "Asas delicadas guardadas sob uma capa dura", "Inseto com o primeiro par de asas endurecido em élitros.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["joaninha", "Besourinho redondo vestido de bolinhas", "Pequeno besouro de corpo arredondado, muitas vezes vermelho com pintas.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["borboleta", "Escamas coloridas em quatro asas", "Inseto de asas largas que passa por metamorfose completa.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["mariposa", "Prima noturna da borboleta", "Inseto lepidóptero geralmente ativo à noite.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["libélula", "Quatro asas transparentes patrulhando a lagoa", "Inseto predador de corpo alongado, cuja fase jovem é aquática.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["gafanhoto", "Saltador de pernas traseiras compridas", "Inseto herbívoro com pernas posteriores adaptadas ao salto.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["grilo", "Músico noturno que toca esfregando as asas", "Inseto saltador conhecido pelo som produzido por estridulação.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["cigarra", "Canto alto vindo do tronco no calor", "Inseto cuja fase adulta produz som intenso com órgãos do abdome.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["louva-a-deus", "Pernas de oração prontas para capturar?", "Inseto predador com pernas dianteiras dobradas e raptoriais.", "wordplay", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["mosca", "Duas asas e olhos de muitas lentes", "Inseto da ordem dos dípteros, com um único par de asas funcionais.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["mosquito", "Zumbido miúdo antes da picada", "Pequeno díptero de corpo fino; em muitas espécies, a fêmea suga sangue.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["aranha", "Oito pernas no centro da teia", "Aracnídeo predador com quatro pares de pernas.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["escorpião", "Pinças na frente, ferrão na cauda", "Aracnídeo com pedipalpos em forma de pinça e aguilhão terminal.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["carrapato", "Aracnídeo que se prende para sugar sangue", "Parasita externo de vertebrados, com corpo pequeno e oito pernas na fase adulta.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["caracol", "Casa em espiral carregada nas costas", "Molusco gastrópode geralmente dotado de concha enrolada.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["lesma", "Molusco terrestre sem casa aparente", "Gastrópode de corpo mole, sem concha externa desenvolvida.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["minhoca", "Abre túneis e revolve a terra", "Anelídeo terrestre alongado que vive no solo úmido.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["polvo", "Oito braços e uma nuvem de tinta", "Molusco marinho cefalópode com oito braços.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["ostra", "Molusco de duas valvas que filtra a água", "Bivalve marinho de concha irregular, fixo a superfícies duras.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["caranguejo", "Anda de lado com pinças à frente", "Crustáceo de corpo largo, cinco pares de pernas e duas pinças.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],
    ["coral", "Construtor colonial de jardins submarinos", "Cnidário marinho, frequentemente colonial, capaz de formar estruturas calcárias.", "association", 1, 5, ["fauna", "invertebrados"], ["nat-ctfb"]],

    // Árvores, palmeiras e plantas de grande porte — 38
    ["ipê", "Florada que pinta a árvore antes das folhas", "Nome comum de árvores brasileiras conhecidas por flores amarelas, roxas, rosas ou brancas.", "association", 1, 5, ["flora", "arvores"], ["nat-flora-funga"]],
    ["jatobá", "Árvore de fruto em vagem e polpa farinácea", "Árvore tropical de madeira dura e fruto com casca resistente.", "association", 2, 4, ["flora", "arvores"], ["nat-flora-funga"]],
    ["jequitibá", "Gigante centenário da mata atlântica", "Nome comum de grandes árvores brasileiras do gênero Cariniana.", "association", 2, 4, ["flora", "arvores"], ["nat-flora-funga"]],
    ["araucária", "Pinheiro brasileiro de copa em taça", "Conífera nativa do Sul do Brasil que produz pinhões.", "association", 1, 5, ["flora", "arvores"], ["nat-flora-funga"]],
    ["sapucaia", "A cumbuca da mata guarda sementes comestíveis", "Árvore tropical cujo fruto lenhoso se abre por uma tampa.", "association", 3, 3, ["flora", "arvores"], ["nat-flora-funga"]],
    ["buriti", "Palmeira das veredas de fruto alaranjado", "Palmeira alta associada a áreas úmidas do Cerrado.", "association", 2, 4, ["flora", "palmeiras"], ["nat-flora-funga", "nat-ibge-vegetacao"]],
    ["carnaúba", "Palmeira da cera no sertão", "Palmeira nordestina cujas folhas fornecem cera.", "association", 2, 4, ["flora", "palmeiras"], ["nat-flora-funga"]],
    ["babaçu", "Palmeira de muitos coquinhos em cachos", "Palmeira brasileira de frutos oleaginosos reunidos em grandes cachos.", "association", 2, 4, ["flora", "palmeiras"], ["nat-flora-funga"]],
    ["castanheira", "Gigante amazônica que entrega ouriços cheios de sementes", "Grande árvore amazônica de sementes comestíveis guardadas em frutos lenhosos.", "association", 1, 5, ["flora", "arvores"], ["nat-flora-funga"]],
    ["seringueira", "Do tronco escorre o látex da borracha", "Árvore amazônica cultivada pela seiva leitosa rica em látex.", "association", 1, 5, ["flora", "arvores"], ["nat-flora-funga"]],
    ["mangue-vermelho", "Raízes-escora na lama da maré", "Árvore típica de estuários tropicais, com raízes aéreas arqueadas.", "association", 3, 3, ["flora", "manguezal"], ["nat-flora-funga", "nat-mma-areas-umidas"]],
    ["embaúba", "Árvore de tronco claro muito visitada por preguiças", "Árvore tropical pioneira de folhas grandes e lobadas.", "association", 2, 4, ["flora", "arvores"], ["nat-flora-funga"]],
    ["quaresmeira", "Roxo na copa perto do calendário da Quaresma?", "Árvore brasileira ornamental de flores roxas ou rosadas.", "wordplay", 2, 4, ["flora", "arvores"], ["nat-flora-funga"]],
    ["manacá", "Arbusto cujas flores mudam do branco ao lilás", "Nome comum de plantas brasileiras conhecidas pela mudança de cor das flores.", "association", 2, 4, ["flora", "arbustos"], ["nat-flora-funga"]],
    ["jabuticabeira", "Frutas escuras brotam direto do tronco", "Árvore brasileira cauliflora, com frutos roxos de polpa clara.", "association", 1, 5, ["flora", "arvores"], ["nat-flora-funga"]],
    ["goiabeira", "Árvore de fruto perfumado, rosado ou branco por dentro", "Árvore tropical de fruto arredondado, aromático e com numerosas sementes.", "association", 1, 5, ["flora", "arvores"], ["nat-flora-funga"]],
    ["cajueiro", "Pedúnculo carnoso e castanha na ponta", "Árvore tropical de copa baixa, pedúnculo suculento e noz externa.", "association", 1, 5, ["flora", "arvores"], ["nat-flora-funga"]],
    ["bananeira", "Folhas enormes em torno de um pseudocaule", "Planta herbácea de grande porte que produz cachos de frutos alongados.", "association", 1, 5, ["flora", "plantas"], ["nat-flora-funga"]],
    ["coqueiro", "Palmeira que oferece água dentro do fruto", "Palmeira tropical de fruto grande, fibroso e com líquido no interior.", "association", 1, 5, ["flora", "palmeiras"], ["nat-flora-funga"]],
    ["palmeira", "Folhas em leque ou pena no alto de um caule", "Planta da família das arecáceas, geralmente de tronco sem ramos.", "association", 1, 5, ["flora", "palmeiras"], ["nat-flora-funga"]],
    ["figueira", "Árvore que guarda muitas flores dentro do fruto", "Árvore do gênero Ficus, produtora de sicônios carnosos.", "trivia", 1, 5, ["flora", "arvores"], ["nat-flora-funga"]],
    ["cedro", "Madeira aromática sob uma copa de árvore", "Nome comum de árvores da família das meliáceas, conhecidas pela madeira valorizada.", "association", 2, 4, ["flora", "arvores"], ["nat-flora-funga"]],
    ["mogno", "Madeira avermelhada de uma grande árvore tropical", "Árvore tropical conhecida por madeira castanho-avermelhada.", "association", 2, 4, ["flora", "arvores"], ["nat-flora-funga"]],
    ["jacarandá", "Flores arroxeadas ou madeira escura, conforme a espécie", "Nome comum aplicado a árvores brasileiras de diferentes gêneros.", "association", 2, 4, ["flora", "arvores"], ["nat-flora-funga"]],
    ["peroba", "Árvore brasileira de madeira dura e tronco alto", "Nome comum de árvores nativas produtoras de madeira resistente.", "association", 2, 4, ["flora", "arvores"], ["nat-flora-funga"]],
    ["imbuia", "Árvore sulista de madeira perfumada", "Árvore nativa da Mata Atlântica, aparentada ao louro e à canela.", "association", 3, 3, ["flora", "arvores"], ["nat-flora-funga"]],
    ["aroeira", "Casca e madeira resistentes sob muitos nomes", "Nome comum de várias plantas lenhosas brasileiras, sobretudo da família das anacardiáceas.", "elliptical", 2, 4, ["flora", "arvores"], ["nat-flora-funga"]],
    ["angico", "Vagens compridas numa árvore de casca rica em taninos", "Nome comum de árvores leguminosas nativas do Brasil.", "association", 3, 3, ["flora", "arvores"], ["nat-flora-funga"]],
    ["sucupira", "Sementes aladas de uma árvore do cerrado", "Nome comum de árvores brasileiras da família das leguminosas.", "association", 3, 3, ["flora", "arvores"], ["nat-flora-funga"]],
    ["copaíba", "O tronco guarda um óleo usado tradicionalmente", "Árvore tropical da qual se extrai um óleo-resina.", "association", 2, 4, ["flora", "arvores"], ["nat-flora-funga"]],
    ["andiroba", "Sementes amazônicas que fornecem óleo", "Árvore amazônica de cujas sementes se extrai óleo.", "association", 2, 4, ["flora", "arvores"], ["nat-flora-funga"]],
    ["guapuruvu", "Tronco claro e crescimento rápido na mata atlântica", "Grande árvore pioneira brasileira de flores amarelas.", "association", 3, 3, ["flora", "arvores"], ["nat-flora-funga"]],
    ["paineira", "Vagens soltam algodão sob um tronco espinhoso", "Árvore de tronco frequentemente barrigudo que produz fibras sedosas nos frutos.", "association", 2, 4, ["flora", "arvores"], ["nat-flora-funga"]],
    ["salgueiro", "Ramos flexíveis pendendo junto à água", "Árvore ou arbusto do gênero Salix, comum em solos úmidos.", "association", 2, 4, ["flora", "arvores"], ["nat-flora-funga"]],
    ["pau-ferro", "Tronco manchado e madeira muito dura", "Árvore brasileira de casca lisa e mosqueada.", "association", 2, 4, ["flora", "arvores"], ["nat-flora-funga"]],
    ["açaizeiro", "Palmeira amazônica de cachos roxos", "Palmeira de estipe delgado que produz pequenos frutos escuros em cachos.", "association", 1, 5, ["flora", "palmeiras"], ["nat-flora-funga"]],
    ["umbuzeiro", "Árvore sertaneja que guarda água nas raízes", "Árvore da Caatinga de copa larga e frutos arredondados.", "association", 2, 4, ["flora", "arvores"], ["nat-flora-funga"]],
    ["pitangueira", "Frutinhos vermelhos e sulcados entre folhas aromáticas", "Arbusto ou pequena árvore nativa de frutos com gomos e aroma marcantes.", "association", 1, 5, ["flora", "arvores"], ["nat-flora-funga"]],

    // Ervas, epífitas e outras formas vegetais — 20
    ["orquídea", "Flor de simetria elegante, muitas vezes sobre galhos", "Planta da família Orchidaceae, frequentemente epífita e de flores vistosas.", "association", 1, 5, ["flora", "flores"], ["nat-flora-funga"]],
    ["bromélia", "Roseta que pode guardar água entre as folhas", "Planta tropical de folhas dispostas em roseta.", "association", 1, 5, ["flora", "epifitas"], ["nat-flora-funga"]],
    ["samambaia", "Folhas em frondes, sem flores nem sementes", "Planta vascular que se reproduz por esporos.", "association", 1, 5, ["flora", "plantas"], ["nat-flora-funga"]],
    ["avenca", "Samambaia delicada de hastes escuras", "Planta de frondes pequenas e finas, comum em locais úmidos.", "association", 2, 4, ["flora", "plantas"], ["nat-flora-funga"]],
    ["musgo", "Tapete verde em pedra úmida", "Pequena planta sem vasos condutores verdadeiros, comum em lugares úmidos.", "association", 1, 5, ["flora", "plantas"], ["nat-flora-funga"]],
    ["cacto", "Reserva de água vestida de espinhos", "Planta suculenta com caule carnoso e folhas frequentemente reduzidas.", "association", 1, 5, ["flora", "plantas"], ["nat-flora-funga"]],
    ["mandacaru", "Cacto alto de braços no sertão", "Cactácea colunar nativa do Brasil, comum na Caatinga.", "association", 1, 5, ["flora", "caatinga"], ["nat-flora-funga"]],
    ["xique-xique", "Cactácea ramificada que arma o chão da caatinga", "Cacto brasileiro de muitos ramos espinhosos.", "association", 2, 4, ["flora", "caatinga"], ["nat-flora-funga"]],
    ["vitória-régia", "Folha gigante que boia na Amazônia", "Planta aquática amazônica de folhas circulares muito grandes.", "association", 1, 5, ["flora", "plantas-aquaticas"], ["nat-flora-funga"]],
    ["aguapé", "Planta flutuante de flores lilases", "Planta aquática que forma rosetas sobre a superfície da água.", "association", 2, 4, ["flora", "plantas-aquaticas"], ["nat-flora-funga"]],
    ["taboa", "Espiga marrom em brejo raso", "Planta de áreas alagadas com inflorescência cilíndrica escura.", "association", 2, 4, ["flora", "areas-umidas"], ["nat-flora-funga", "nat-mma-areas-umidas"]],
    ["capim", "Cobertura verde de folhas estreitas", "Nome comum de diversas gramíneas herbáceas.", "association", 1, 5, ["flora", "gramineas"], ["nat-flora-funga"]],
    ["bambu", "Colmos ocos que crescem em touceiras", "Gramínea lenhosa de caules segmentados.", "association", 1, 5, ["flora", "gramineas"], ["nat-flora-funga"]],
    ["trepadeira", "Sobe apoiada em outra planta, mas sem pedir escada?", "Planta de caule longo que usa um suporte para alcançar altura.", "wordplay", 1, 5, ["flora", "formas-vegetais"], ["nat-flora-funga"]],
    ["cipó", "Corda viva entre troncos", "Caule longo e flexível de uma planta trepadora.", "association", 1, 5, ["flora", "formas-vegetais"], ["nat-flora-funga"]],
    ["erva", "Pequena planta de caule não lenhoso", "Planta herbácea, geralmente baixa e de tecido pouco rígido.", "elliptical", 1, 5, ["flora", "formas-vegetais"], ["nat-flora-funga"]],
    ["arbusto", "Lenhoso, baixo e ramificado desde a base", "Planta lenhosa menor que uma árvore, com vários caules próximos do solo.", "elliptical", 1, 5, ["flora", "formas-vegetais"], ["nat-flora-funga"]],
    ["grama", "Tapete vivo aparado no jardim", "Planta rasteira de folhas estreitas usada como cobertura do solo.", "association", 1, 5, ["flora", "gramineas"], ["nat-flora-funga"]],
    ["espinho", "Ponta defensiva de um ramo ou folha", "Estrutura vegetal rígida e pontiaguda que ajuda na proteção.", "association", 1, 5, ["flora", "estruturas-vegetais"], ["nat-flora-funga"]],
    ["junco", "Haste ereta em solo encharcado", "Nome comum de plantas herbáceas de áreas úmidas, com caules finos.", "association", 2, 4, ["flora", "areas-umidas"], ["nat-flora-funga", "nat-mma-areas-umidas"]],

    // Fungos e associações — 7
    ["fungo", "Nem planta nem animal no tronco úmido", "Organismo heterotrófico que absorve nutrientes e pertence a um reino próprio.", "association", 1, 5, ["funga"], ["nat-flora-funga"]],
    ["cogumelo", "Chapéu que nasce sem cabeça?", "Estrutura reprodutiva visível produzida por certos fungos.", "wordplay", 1, 5, ["funga"], ["nat-flora-funga"]],
    ["levedura", "Fungo microscópico que ajuda massa a crescer", "Fungo unicelular capaz de realizar fermentação.", "association", 2, 5, ["funga"], ["nat-flora-funga"]],
    ["bolor", "Penugem fúngica sobre alimento esquecido", "Crescimento visível de fungos filamentosos sobre matéria orgânica.", "association", 1, 5, ["funga"], ["nat-flora-funga"]],
    ["orelha-de-pau", "Um pavilhão fúngico preso ao tronco?", "Nome comum de fungos de corpo frutífero achatado que crescem em madeira.", "wordplay", 2, 4, ["funga"], ["nat-flora-funga"]],
    ["trufa", "Fungo subterrâneo farejado à mesa", "Corpo frutífero subterrâneo de certos fungos, valorizado como alimento.", "association", 2, 4, ["funga"], ["nat-flora-funga"]],
    ["líquen", "Parceria que pinta pedras e cascas", "Associação estável entre um fungo e um parceiro fotossintetizante.", "association", 2, 4, ["funga", "simbiose"], ["nat-flora-funga"]],

    // Habitats, biomas e formações naturais — 25
    ["floresta", "Teto de copas sobre muitos andares de vida", "Formação vegetal dominada por árvores próximas entre si.", "association", 1, 5, ["habitats", "vegetacao"], ["nat-ibge-vegetacao"]],
    ["mata", "Árvores reunidas numa paisagem fechada", "Área coberta principalmente por vegetação arbórea.", "elliptical", 1, 5, ["habitats", "vegetacao"], ["nat-ibge-vegetacao"]],
    ["bosque", "Pequena reunião de árvores", "Área arborizada geralmente menor e mais aberta que uma floresta.", "elliptical", 1, 5, ["habitats", "vegetacao"], ["nat-ibge-vegetacao"]],
    ["selva", "Floresta densa no imaginário tropical", "Floresta extensa e fechada, especialmente em região tropical.", "association", 1, 5, ["habitats", "vegetacao"], ["nat-ibge-vegetacao"]],
    ["savana", "Árvores espaçadas sobre um mar de gramíneas", "Formação tropical com predomínio de gramíneas e árvores dispersas.", "association", 1, 5, ["habitats", "vegetacao"], ["nat-ibge-vegetacao"]],
    ["pradaria", "Campo vasto dominado por gramíneas", "Formação aberta em que predominam plantas herbáceas, especialmente gramíneas.", "elliptical", 2, 4, ["habitats", "vegetacao"], ["nat-ibge-vegetacao"]],
    ["deserto", "Chuva rara numa paisagem de extremos", "Região muito seca, com precipitação escassa e vegetação rarefeita.", "association", 1, 5, ["habitats", "climas"], ["nat-ibge-atlas"]],
    ["tundra", "Vegetação rasteira onde o subsolo permanece gelado", "Bioma frio sem árvores, marcado por solo congelado durante longos períodos.", "association", 2, 4, ["habitats", "biomas"], ["nat-openstax-biomas"]],
    ["taiga", "Cinturão frio de coníferas", "Bioma de florestas boreais dominadas por coníferas.", "elliptical", 2, 4, ["habitats", "biomas"], ["nat-openstax-biomas"]],
    ["manguezal", "Berçário costeiro entre lama e maré", "Ecossistema costeiro de águas salobras e árvores adaptadas ao alagamento.", "association", 1, 5, ["habitats", "areas-umidas"], ["nat-mma-areas-umidas"]],
    ["restinga", "Vegetação enraizada na areia do litoral", "Conjunto de formações vegetais que ocupa planícies arenosas costeiras.", "association", 2, 4, ["habitats", "vegetacao"], ["nat-ibge-vegetacao"]],
    ["cerrado", "Árvores retorcidas sobre campos do Brasil central", "Bioma brasileiro de savanas, campos e formações florestais.", "association", 1, 5, ["habitats", "biomas-brasileiros"], ["nat-ibge-biomas", "nat-mma-biodiversidade"]],
    ["caatinga", "Branca na seca, verde depois da chuva", "Bioma semiárido exclusivamente brasileiro, com vegetação adaptada à estiagem.", "association", 1, 5, ["habitats", "biomas-brasileiros"], ["nat-ibge-biomas", "nat-mma-biodiversidade"]],
    ["pantanal", "Planície brasileira que pulsa com as cheias", "Bioma brasileiro marcado por extensas inundações sazonais.", "association", 1, 5, ["habitats", "biomas-brasileiros"], ["nat-ibge-biomas", "nat-mma-areas-umidas"]],
    ["amazônia", "Maior bioma do Brasil sob uma vasta copa", "Bioma brasileiro dominado pela maior floresta tropical do planeta.", "trivia", 1, 5, ["habitats", "biomas-brasileiros"], ["nat-ibge-biomas", "nat-mma-biodiversidade"]],
    ["pampa", "Campos do extremo sul brasileiro", "Bioma brasileiro de paisagens campestres, restrito ao Rio Grande do Sul no país.", "association", 1, 5, ["habitats", "biomas-brasileiros"], ["nat-ibge-biomas", "nat-mma-biodiversidade"]],
    ["mata atlântica", "Floresta costeira que acompanha boa parte do Brasil", "Bioma brasileiro originalmente estendido por grande faixa do litoral e áreas interiores.", "association", 1, 5, ["habitats", "biomas-brasileiros"], ["nat-ibge-biomas", "nat-mma-biodiversidade"]],
    ["brejo", "Terreno encharcado de vegetação própria", "Área baixa e úmida, com solo saturado ou coberto por água rasa.", "elliptical", 1, 5, ["habitats", "areas-umidas"], ["nat-mma-areas-umidas"]],
    ["pântano", "Água rasa parada entre plantas", "Área úmida permanentemente ou periodicamente alagada.", "association", 1, 5, ["habitats", "areas-umidas"], ["nat-mma-areas-umidas"]],
    ["charco", "Pequena área de chão lodoso e alagado", "Trecho de terreno com água parada e lama.", "elliptical", 2, 4, ["habitats", "areas-umidas"], ["nat-mma-areas-umidas"]],
    ["costão", "Rocha costeira sob ondas e marés", "Trecho de litoral rochoso exposto à ação do mar.", "association", 2, 4, ["habitats", "costeiros"], ["nat-ibge-atlas"]],
    ["estuário", "Onde o rio encontra a água salgada", "Trecho costeiro em que água doce e água do mar se misturam.", "association", 1, 5, ["habitats", "costeiros"], ["nat-mma-areas-umidas"]],
    ["lagoa", "Espelho raso entre margens", "Corpo de água interior relativamente raso.", "association", 1, 5, ["habitats", "aguas"], ["nat-ibge-atlas"]],
    ["oásis", "Água e verde no meio da aridez", "Área fértil num deserto, sustentada por uma fonte de água.", "association", 1, 5, ["habitats", "aguas"], ["nat-ibge-atlas"]],
    ["caverna", "Escuridão natural aberta na rocha", "Cavidade subterrânea natural acessível a partir da superfície.", "association", 1, 5, ["habitats", "relevo"], ["nat-icmbio-cavernas"]],

    // Relevo, águas e paisagens — 25
    ["rio", "Caminho de água que segue para outro corpo d'água", "Curso natural de água que escoa por um leito.", "association", 1, 5, ["paisagens", "aguas"], ["nat-ibge-atlas"]],
    ["riacho", "Curso d'água pequeno o bastante para murmurar", "Curso natural de água menor e menos caudaloso que um rio.", "association", 1, 5, ["paisagens", "aguas"], ["nat-ibge-atlas"]],
    ["nascente", "Primeiro fio de um curso d'água", "Local onde a água subterrânea aflora e inicia um curso.", "association", 1, 5, ["paisagens", "aguas"], ["nat-ibge-atlas"]],
    ["cachoeira", "Queda que faz o rio despencar", "Trecho em que um curso de água cai por forte desnível.", "association", 1, 5, ["paisagens", "aguas"], ["nat-ibge-atlas"]],
    ["corredeira", "Água veloz entre pedras e desníveis", "Trecho raso e turbulento de um curso de água.", "association", 2, 4, ["paisagens", "aguas"], ["nat-ibge-atlas"]],
    ["lago", "Grande espelho d'água cercado por terra", "Corpo de água interior acumulado numa depressão do terreno.", "association", 1, 5, ["paisagens", "aguas"], ["nat-ibge-atlas"]],
    ["laguna", "Água costeira separada do mar por uma faixa", "Corpo de água litoral parcialmente isolado do oceano por barreira arenosa.", "association", 2, 4, ["paisagens", "aguas"], ["nat-ibge-atlas"]],
    ["baía", "Curva do mar entrando na costa", "Reentrância ampla do litoral ocupada pelo mar.", "association", 1, 5, ["paisagens", "litoral"], ["nat-ibge-atlas"]],
    ["enseada", "Pequeno abraço da costa no mar", "Reentrância costeira abrigada, geralmente menor que uma baía.", "association", 1, 5, ["paisagens", "litoral"], ["nat-ibge-atlas"]],
    ["praia", "Faixa de areia entre terra e onda", "Trecho de costa coberto por areia, cascalho ou sedimentos semelhantes.", "association", 1, 5, ["paisagens", "litoral"], ["nat-ibge-atlas"]],
    ["duna", "Morro de areia que o vento modela", "Acúmulo de areia formado e deslocado pela ação do vento.", "association", 1, 5, ["paisagens", "relevo"], ["nat-ibge-ambiental"]],
    ["ilha", "Terra cercada de água por todos os lados", "Porção de terra emersa completamente rodeada por água.", "elliptical", 1, 5, ["paisagens", "relevo"], ["nat-ibge-atlas"]],
    ["arquipélago", "Um grupo de ilhas no mesmo mapa", "Conjunto de ilhas próximas entre si.", "association", 1, 5, ["paisagens", "relevo"], ["nat-ibge-atlas"]],
    ["península", "Quase ilha, presa ao continente", "Porção de terra cercada de água na maior parte de seu contorno.", "association", 1, 5, ["paisagens", "relevo"], ["nat-ibge-atlas"]],
    ["vale", "Terra baixa entre elevações", "Depressão alongada situada entre montanhas ou colinas.", "elliptical", 1, 5, ["paisagens", "relevo"], ["nat-ibge-ambiental"]],
    ["planalto", "Relevo alto em que a erosão supera a deposição", "Unidade de relevo elevada e marcada pelo desgaste erosivo.", "association", 2, 4, ["paisagens", "relevo"], ["nat-ibge-ambiental"]],
    ["planície", "Relevo baixo construído por sedimentos", "Unidade de relevo relativamente plana, onde predomina a deposição.", "association", 2, 4, ["paisagens", "relevo"], ["nat-ibge-ambiental"]],
    ["serra", "Sequência de elevações no horizonte", "Conjunto de montanhas ou terrenos elevados alinhados.", "elliptical", 1, 5, ["paisagens", "relevo"], ["nat-ibge-ambiental"]],
    ["montanha", "Grande elevação com encostas e cume", "Forma de relevo que se ergue acentuadamente acima do entorno.", "elliptical", 1, 5, ["paisagens", "relevo"], ["nat-ibge-ambiental"]],
    ["morro", "Elevação menor de topo arredondado", "Elevação natural do terreno, em geral menor que uma montanha.", "elliptical", 1, 5, ["paisagens", "relevo"], ["nat-ibge-ambiental"]],
    ["chapada", "Topo amplo com bordas escarpadas", "Relevo elevado de superfície relativamente plana e encostas abruptas.", "association", 1, 5, ["paisagens", "relevo"], ["nat-ibge-ambiental"]],
    ["falésia", "Parede costeira talhada pelas ondas", "Escarpa íngreme junto ao mar, formada pela erosão costeira.", "association", 2, 4, ["paisagens", "relevo"], ["nat-ibge-ambiental"]],
    ["cânion", "Vale estreito de paredes profundas", "Vale profundo e encaixado, geralmente esculpido por um rio.", "association", 1, 5, ["paisagens", "relevo"], ["nat-ibge-ambiental"]],
    ["foz", "Fim do rio, começo de outra água", "Local onde um curso de água desemboca em outro corpo de água.", "association", 1, 5, ["paisagens", "aguas"], ["nat-ibge-atlas"]],
    ["várzea", "Planície que o rio visita nas cheias", "Terreno baixo e plano sujeito a inundações periódicas de um rio.", "association", 2, 4, ["paisagens", "areas-umidas"], ["nat-ibge-ambiental", "nat-mma-areas-umidas"]],

    // Relações ecológicas e ciclos naturais — 15
    ["ecossistema", "Seres e ambiente em uma só rede", "Conjunto dos organismos de uma área e das interações com o meio físico.", "association", 1, 5, ["ecologia"], ["nat-openstax-ecossistemas"]],
    ["habitat", "O endereço natural de uma espécie", "Ambiente em que um organismo vive e encontra os recursos de que precisa.", "association", 1, 5, ["ecologia"], ["nat-openstax-ecologia"]],
    ["nicho", "Profissão ecológica de uma espécie?", "Papel de uma espécie no ambiente e modo como utiliza recursos.", "wordplay", 2, 4, ["ecologia"], ["nat-openstax-ecologia"]],
    ["cadeia alimentar", "Sequência de quem serve de alimento a quem", "Representação linear da transferência de matéria e energia entre organismos.", "association", 1, 5, ["ecologia", "relacoes"], ["nat-openstax-ecossistemas"]],
    ["teia alimentar", "Várias cadeias entrelaçadas no prato da natureza", "Rede que liga organismos por relações de consumo.", "association", 2, 4, ["ecologia", "relacoes"], ["nat-openstax-ecossistemas"]],
    ["predador", "Caçador numa relação entre espécies", "Animal que captura e consome outro organismo.", "elliptical", 1, 5, ["ecologia", "relacoes"], ["nat-openstax-ecologia"]],
    ["presa", "Alvo vivo no cardápio do caçador", "Organismo capturado e consumido por outro.", "association", 1, 5, ["ecologia", "relacoes"], ["nat-openstax-ecologia"]],
    ["parasita", "Vive às custas de um hospedeiro", "Organismo que obtém recursos de outro e lhe causa prejuízo.", "association", 1, 5, ["ecologia", "relacoes"], ["nat-openstax-ecologia"]],
    ["simbiose", "Duas espécies em convivência íntima", "Associação estreita e duradoura entre organismos de espécies diferentes.", "association", 2, 4, ["ecologia", "relacoes"], ["nat-openstax-ecologia"]],
    ["polinização", "Viagem do pólen até a parte receptora da flor", "Transferência de grãos de pólen que possibilita a fecundação das plantas com sementes.", "association", 1, 5, ["ecologia", "ciclos-naturais"], ["nat-openstax-ecologia"]],
    ["decomposição", "Restos voltam ao ciclo pela ação de fungos e bactérias", "Transformação da matéria orgânica morta em substâncias mais simples.", "association", 2, 5, ["ecologia", "ciclos-naturais"], ["nat-openstax-ecossistemas"]],
    ["migração", "Viagem sazonal de ida e volta", "Deslocamento regular de animais entre regiões, muitas vezes ligado às estações.", "association", 1, 5, ["ecologia", "comportamento"], ["nat-openstax-ecologia"]],
    ["hibernação", "Longo repouso para atravessar o frio e a escassez", "Estado sazonal de baixa atividade e metabolismo reduzido em certos animais.", "association", 1, 5, ["ecologia", "comportamento"], ["nat-openstax-hibernacao"]],
    ["enxame", "Nuvem viva de insetos em deslocamento", "Grande agrupamento de insetos que se movem juntos.", "association", 1, 5, ["ecologia", "coletivos"], ["unitex-pb"]],
    ["cardume", "Muitos peixes nadando como um só", "Grupo de peixes que se desloca de forma coordenada.", "association", 1, 5, ["ecologia", "coletivos"], ["unitex-pb"]],
  ],
} as const satisfies BiomeBundle;

export const naturezaEntries = entriesFromBundle(naturezaBundle);

// Auditoria: 250 registros e chaves únicas; comprimentos 66/162/22 (3–5/6–10/11–18),
// estilos 212/16/11/11 (associação/elipse/trocadilho/trívia), 15 fontes e 0 colisões globais.
