import type { BiomeId, ContentEntryInput } from "../src/content/catalog.js";
import { normalizeGridAnswer } from "../src/content/catalog.js";

type SeedRecord = readonly [
  answer: string,
  normalClue: string,
  simpleClue: string,
  difficulty: 1 | 2 | 3 | 4 | 5,
  familiarity: 1 | 2 | 3 | 4 | 5,
  tags?: readonly string[],
];

function entriesFor(biome: BiomeId, prefix: string, records: readonly SeedRecord[]): ContentEntryInput[] {
  return records.map(([answer, normal, simple, difficulty, familiarity, tags = []]) => ({
    id: `${prefix}-${normalizeGridAnswer(answer).toLowerCase()}`,
    answer,
    biomes: [biome],
    difficulty,
    familiarity,
    clues: { normal, simple },
    provenance: {
      source: "curadoria-cruzaverso-v1",
      license: "conteudo-original-do-projeto",
    },
    tags: [...tags],
  }));
}

const cotidiano: readonly SeedRecord[] = [
  ["abacaxi", "Fruto tropical coroado por folhas rígidas.", "Fruta grande, ácida e com casca espinhosa.", 1, 5, ["alimento"]],
  ["agenda", "Objeto ou sistema usado para organizar compromissos.", "Lugar onde se anotam horários e tarefas.", 1, 5, ["rotina"]],
  ["almoço", "Refeição que costuma ocupar o meio do dia.", "Refeição feita por volta do meio-dia.", 1, 5, ["alimento"]],
  ["amizade", "Vínculo de afeto e confiança entre pessoas.", "Relação entre amigos.", 1, 5, ["relações"]],
  ["bicicleta", "Veículo leve movido por pedais.", "Transporte de duas rodas com pedais.", 1, 5, ["transporte"]],
  ["cafeteira", "Utensílio ou aparelho que prepara uma bebida torrada.", "Aparelho usado para fazer café.", 1, 5, ["cozinha"]],
  ["camiseta", "Peça casual que cobre o tronco e geralmente tem mangas curtas.", "Roupa leve usada na parte de cima do corpo.", 1, 5, ["roupa"]],
  ["carteira", "Objeto pequeno que guarda dinheiro e documentos.", "Onde se carregam cartões e notas.", 1, 5, ["objeto"]],
  ["chuveiro", "Equipamento doméstico que espalha água sobre o corpo.", "Aparelho usado para tomar banho.", 1, 5, ["casa"]],
  ["cozinha", "Cômodo onde alimentos são preparados.", "Parte da casa usada para cozinhar.", 1, 5, ["casa"]],
  ["domingo", "Dia da semana associado ao descanso em muitos calendários.", "Dia que vem depois de sábado.", 1, 5, ["tempo"]],
  ["escola", "Instituição dedicada ao ensino e à aprendizagem.", "Lugar onde alunos estudam.", 1, 5, ["rotina"]],
  ["família", "Grupo unido por parentesco ou laços de cuidado.", "Pais, filhos e outros parentes.", 1, 5, ["relações"]],
  ["feira", "Encontro periódico de vendedores em bancas.", "Lugar com barracas para comprar frutas e outros produtos.", 1, 5, ["cidade"]],
  ["garagem", "Espaço destinado a guardar veículos.", "Parte da casa onde fica o carro.", 1, 5, ["casa"]],
  ["janela", "Abertura que deixa entrar luz e ventilação.", "Abertura com vidro numa parede.", 1, 5, ["casa"]],
  ["mercado", "Estabelecimento com grande variedade de produtos de consumo.", "Lugar onde se compram alimentos e itens de casa.", 1, 5, ["cidade"]],
  ["mochila", "Bolsa carregada nas costas por duas alças.", "Bolsa usada nas costas para levar objetos.", 1, 5, ["objeto"]],
  ["pipoca", "Grão estourado pelo calor, comum em sessões de filme.", "Milho estourado que se come no cinema.", 1, 5, ["alimento"]],
  ["quintal", "Área aberta ligada a uma residência.", "Espaço descoberto nos fundos ou na frente de uma casa.", 1, 5, ["casa"]],
  ["receita", "Conjunto de instruções e ingredientes para preparar algo.", "Passo a passo para fazer um prato.", 1, 5, ["cozinha"]],
  ["sapato", "Calçado fechado que protege os pés.", "Peça usada nos pés para caminhar.", 1, 5, ["roupa"]],
  ["sorriso", "Expressão facial associada a alegria ou simpatia.", "Expressão feita com a boca quando alguém está feliz.", 1, 5, ["relações"]],
  ["telefone", "Aparelho usado para conversar à distância.", "Dispositivo usado para fazer ligações.", 1, 5, ["objeto"]],
  ["trabalho", "Atividade realizada para produzir, servir ou obter renda.", "Atividade profissional de uma pessoa.", 1, 5, ["rotina"]],
  ["viagem", "Deslocamento para um lugar distante do habitual.", "Ato de ir conhecer ou visitar outro lugar.", 1, 5, ["transporte"]],
  ["vizinho", "Pessoa que mora perto de outra.", "Quem vive na casa ou apartamento ao lado.", 1, 5, ["relações"]],
  ["xícara", "Recipiente pequeno com asa, usado para bebidas quentes.", "Copinho com alça usado para tomar café.", 1, 5, ["cozinha"]],
];

const ciencia: readonly SeedRecord[] = [
  ["átomo", "Unidade básica que preserva as propriedades de um elemento.", "Partícula que forma os elementos químicos.", 2, 5, ["quimica"]],
  ["bactéria", "Microrganismo unicelular sem núcleo delimitado.", "Ser microscópico formado por uma célula.", 2, 4, ["biologia"]],
  ["célula", "Menor unidade estrutural e funcional dos seres vivos.", "Unidade básica de um organismo vivo.", 1, 5, ["biologia"]],
  ["clima", "Padrão de condições atmosféricas observado por longos períodos.", "Comportamento do tempo de uma região ao longo dos anos.", 2, 5, ["terra"]],
  ["cometa", "Corpo gelado que pode formar cauda ao se aproximar de uma estrela.", "Astro que pode aparecer no céu com uma longa cauda.", 2, 5, ["astronomia"]],
  ["cristal", "Sólido cujas partículas formam uma estrutura ordenada.", "Sólido com átomos organizados em padrão regular.", 3, 4, ["quimica"]],
  ["elétron", "Partícula subatômica com carga elétrica negativa.", "Partícula negativa que fica ao redor do núcleo atômico.", 2, 5, ["fisica"]],
  ["energia", "Grandeza associada à capacidade de produzir transformação.", "Capacidade de realizar trabalho ou causar mudança.", 2, 5, ["fisica"]],
  ["evolução", "Mudança hereditária de populações ao longo das gerações.", "Processo pelo qual espécies mudam com o tempo.", 2, 5, ["biologia"]],
  ["fóssil", "Vestígio preservado de um organismo de épocas passadas.", "Resto ou marca antiga de um ser vivo preservado em rocha.", 2, 5, ["terra"]],
  ["fóton", "Quantum associado à radiação eletromagnética.", "Partícula elementar da luz.", 3, 3, ["fisica"]],
  ["galáxia", "Grande sistema de estrelas, gás, poeira e matéria escura.", "Conjunto enorme de estrelas, como a Via Láctea.", 2, 5, ["astronomia"]],
  ["genoma", "Conjunto completo do material genético de um organismo.", "Todo o DNA de um ser vivo.", 3, 4, ["biologia"]],
  ["gravidade", "Interação que atrai corpos com massa.", "Força que puxa objetos em direção ao chão.", 2, 5, ["fisica"]],
  ["laser", "Dispositivo que emite luz coerente e concentrada.", "Feixe de luz muito concentrado.", 2, 5, ["fisica"]],
  ["magnetismo", "Fenômeno ligado a campos produzidos por cargas em movimento.", "Fenômeno que faz ímãs atraírem certos metais.", 3, 4, ["fisica"]],
  ["meteoro", "Rastro luminoso de um corpo ao atravessar uma atmosfera.", "Risco de luz causado por uma pedra espacial na atmosfera.", 2, 4, ["astronomia"]],
  ["molécula", "Conjunto eletricamente neutro de átomos ligados.", "Grupo de átomos unidos.", 2, 5, ["quimica"]],
  ["neurônio", "Célula especializada em transmitir sinais no sistema nervoso.", "Célula que carrega sinais no cérebro e nos nervos.", 2, 5, ["biologia"]],
  ["órbita", "Trajetória de um corpo sob ação gravitacional ao redor de outro.", "Caminho de um astro ao redor de outro.", 2, 5, ["astronomia"]],
  ["oxigênio", "Elemento gasoso essencial à respiração de muitos organismos.", "Gás do ar usado na respiração.", 1, 5, ["quimica"]],
  ["planeta", "Corpo celeste que orbita uma estrela e domina sua vizinhança orbital.", "Mundo que gira ao redor de uma estrela.", 1, 5, ["astronomia"]],
  ["proteína", "Macromolécula formada por cadeias de aminoácidos.", "Nutriente e molécula formada por aminoácidos.", 2, 5, ["biologia"]],
  ["quark", "Partícula elementar que compõe prótons e nêutrons.", "Partícula muito pequena encontrada dentro de prótons e nêutrons.", 4, 3, ["fisica"]],
  ["satélite", "Corpo que orbita outro de maior massa.", "Objeto natural ou artificial que gira ao redor de um planeta.", 2, 5, ["astronomia"]],
  ["telescópio", "Instrumento que coleta radiação para observar objetos distantes.", "Instrumento usado para enxergar astros distantes.", 2, 5, ["astronomia"]],
  ["vacina", "Preparação que treina o sistema imune contra um agente.", "Proteção que ensina o corpo a combater uma doença.", 1, 5, ["biologia"]],
  ["vulcão", "Estrutura geológica por onde material interno alcança a superfície.", "Montanha que pode expelir lava.", 1, 5, ["terra"]],
];

const historia: readonly SeedRecord[] = [
  ["abolição", "Ato político que extingue formalmente uma instituição ou prática.", "Fim oficial de uma prática, como a escravidão.", 2, 4, ["politica"]],
  ["acrópole", "Parte elevada e fortificada de antigas cidades gregas.", "Área alta de uma cidade da Grécia antiga.", 4, 2, ["antiguidade"]],
  ["armadura", "Conjunto defensivo usado por combatentes em épocas passadas.", "Proteção de metal usada por guerreiros.", 2, 5, ["medieval"]],
  ["arqueologia", "Disciplina que estuda sociedades por meio de vestígios materiais.", "Ciência que investiga povos antigos por seus objetos e ruínas.", 3, 4, ["pesquisa"]],
  ["caravela", "Embarcação de velas usada nas navegações ibéricas.", "Navio pequeno usado nas grandes navegações.", 2, 5, ["navegacoes"]],
  ["castelo", "Residência fortificada associada à nobreza medieval.", "Grande construção fortificada de reis e nobres.", 1, 5, ["medieval"]],
  ["catedral", "Templo que abriga a sede de um bispo.", "Grande igreja principal de uma diocese.", 2, 5, ["arquitetura"]],
  ["colônia", "Território submetido ao controle político de outra potência.", "Território governado por outro país.", 2, 5, ["politica"]],
  ["constituição", "Documento fundamental que organiza juridicamente um Estado.", "Conjunto principal de leis de um país.", 2, 5, ["politica"]],
  ["coroa", "Objeto simbólico ligado à autoridade monárquica.", "Adorno usado por reis e rainhas.", 1, 5, ["monarquia"]],
  ["dinastia", "Sequência de governantes pertencentes à mesma família.", "Família que governa por várias gerações.", 2, 4, ["monarquia"]],
  ["Egito", "Civilização antiga desenvolvida ao redor do rio Nilo.", "País dos faraós e das grandes pirâmides.", 1, 5, ["antiguidade"]],
  ["escrita", "Sistema de sinais que permitiu registrar fala, leis e memória.", "Forma de registrar palavras com símbolos.", 1, 5, ["cultura"]],
  ["faraó", "Título atribuído aos soberanos do antigo vale do Nilo.", "Governante do Egito antigo.", 1, 5, ["antiguidade"]],
  ["feudalismo", "Organização social europeia baseada em terras e vínculos de dependência.", "Sistema medieval de senhores, servos e feudos.", 3, 4, ["medieval"]],
  ["império", "Estado extenso que reúne diferentes povos sob uma autoridade central.", "Grande território governado por um imperador.", 2, 5, ["politica"]],
  ["independência", "Ruptura de subordinação política entre territórios.", "Quando um país deixa de ser governado por outro.", 2, 5, ["politica"]],
  ["monarquia", "Forma de governo cuja chefia é ocupada por um soberano.", "Governo liderado por rei ou rainha.", 2, 5, ["politica"]],
  ["museu", "Instituição que preserva e interpreta patrimônios.", "Lugar que guarda e exibe objetos históricos ou artísticos.", 1, 5, ["cultura"]],
  ["pirâmide", "Construção monumental de base larga e faces triangulares.", "Monumento de pedra famoso no Egito antigo.", 1, 5, ["antiguidade"]],
  ["quilombo", "Comunidade histórica formada sobretudo por pessoas que resistiram à escravidão.", "Comunidade criada por pessoas negras que escapavam da escravidão.", 2, 5, ["brasil"]],
  ["república", "Forma de governo em que a chefia pública não é hereditária.", "Governo sem rei, com representantes escolhidos.", 2, 5, ["politica"]],
  ["revolução", "Transformação profunda e acelerada de uma ordem política ou social.", "Mudança radical na sociedade ou no governo.", 2, 5, ["politica"]],
  ["Roma", "Cidade que deu origem a uma potência central da Antiguidade ocidental.", "Capital de um grande império da Antiguidade.", 1, 5, ["antiguidade"]],
  ["senado", "Assembleia política cujo nome remonta à Antiguidade romana.", "Casa legislativa formada por senadores.", 2, 5, ["politica"]],
  ["Tiradentes", "Inconfidente mineiro transformado em símbolo cívico brasileiro.", "Personagem da Inconfidência Mineira executado em 1792.", 2, 5, ["brasil"]],
  ["tratado", "Acordo formal firmado entre Estados ou autoridades políticas.", "Documento de acordo entre países.", 2, 5, ["politica"]],
  ["viking", "Nome dado a navegadores escandinavos da Alta Idade Média.", "Navegador e guerreiro medieval da Escandinávia.", 2, 5, ["medieval"]],
];

const culturaPop: readonly SeedRecord[] = [
  ["anime", "Produção de animação associada à indústria japonesa.", "Desenho animado produzido no Japão.", 1, 5, ["animacao"]],
  ["arcade", "Máquina pública dedicada a jogos eletrônicos de sessões curtas.", "Máquina de videogame encontrada em fliperamas.", 2, 4, ["games"]],
  ["aventura", "Gênero centrado em jornadas, riscos e descobertas.", "História de viagem, exploração e desafios.", 1, 5, ["genero"]],
  ["cinema", "Arte e indústria de narrativas projetadas em movimento.", "Arte de produzir e exibir filmes.", 1, 5, ["filme"]],
  ["controle", "Periférico segurado nas mãos para comandar um jogo.", "Aparelho com botões usado para jogar videogame.", 1, 5, ["games"]],
  ["cosplay", "Prática de vestir e interpretar personagens de obras populares.", "Fantasia usada para imitar um personagem.", 2, 4, ["fandom"]],
  ["detetive", "Personagem que investiga pistas para esclarecer um mistério.", "Investigador comum em histórias de mistério.", 1, 5, ["genero"]],
  ["dragão", "Criatura fantástica frequentemente alada e associada ao fogo.", "Monstro lendário que costuma voar e soltar fogo.", 1, 5, ["fantasia"]],
  ["episódio", "Parte individual de uma obra seriada.", "Cada capítulo de uma série ou podcast.", 1, 5, ["serie"]],
  ["fandom", "Comunidade organizada em torno de uma obra ou artista.", "Grupo de fãs de uma série, jogo ou artista.", 2, 4, ["comunidade"]],
  ["fantasia", "Gênero que admite magia e mundos imaginários.", "Tipo de história com magia e criaturas inventadas.", 1, 5, ["genero"]],
  ["herói", "Figura central que enfrenta obstáculos em favor de uma causa.", "Personagem corajoso que tenta salvar ou ajudar.", 1, 5, ["personagem"]],
  ["karaokê", "Entretenimento de cantar acompanhando uma faixa instrumental.", "Brincadeira de cantar seguindo a letra na tela.", 1, 5, ["musica"]],
  ["magia", "Força sobrenatural usada como recurso narrativo.", "Poder sobrenatural comum em histórias de fantasia.", 1, 5, ["fantasia"]],
  ["mangá", "Quadrinho ligado à tradição editorial japonesa.", "História em quadrinhos japonesa.", 1, 5, ["quadrinho"]],
  ["meme", "Unidade cultural remixada e compartilhada rapidamente em rede.", "Imagem ou piada que se espalha pela internet.", 1, 5, ["internet"]],
  ["musical", "Obra dramática em que canções conduzem parte da narrativa.", "Peça ou filme cuja história inclui muitas músicas.", 2, 4, ["musica"]],
  ["novela", "Narrativa televisiva longa exibida em capítulos frequentes.", "História de televisão dividida em muitos capítulos.", 1, 5, ["televisao"]],
  ["pixel", "Menor elemento endereçável de uma imagem digital rasterizada.", "Pequeno ponto colorido que forma uma imagem na tela.", 1, 5, ["games"]],
  ["podcast", "Programa sonoro distribuído em episódios sob demanda.", "Programa de áudio ouvido pela internet.", 1, 5, ["internet"]],
  ["quadrinho", "Narrativa composta por imagens sequenciais e balões.", "História contada em desenhos e balões de fala.", 1, 5, ["quadrinho"]],
  ["roteiro", "Texto que organiza cenas, falas e ações de uma produção.", "Documento com cenas e falas de um filme ou série.", 2, 5, ["filme"]],
  ["seriado", "Produção audiovisual dividida em capítulos recorrentes.", "Programa de televisão contado em episódios.", 1, 5, ["serie"]],
  ["streaming", "Distribuição contínua de mídia pela rede sem download integral prévio.", "Forma de assistir ou ouvir conteúdo pela internet.", 2, 5, ["internet"]],
  ["super-herói", "Personagem de feitos extraordinários, frequentemente com identidade visual própria.", "Herói com poderes ou habilidades fora do comum.", 1, 5, ["personagem"]],
  ["videogame", "Mídia interativa eletrônica comandada pelo jogador.", "Jogo eletrônico exibido numa tela.", 1, 5, ["games"]],
  ["vilão", "Personagem que se opõe aos objetivos do protagonista.", "Antagonista ou inimigo principal de uma história.", 1, 5, ["personagem"]],
  ["zumbi", "Morto reanimado recorrente em obras de horror.", "Criatura morta-viva comum em filmes e jogos.", 1, 5, ["terror"]],
];

export const bundledEntries: ContentEntryInput[] = [
  ...entriesFor("cotidiano", "cot", cotidiano),
  ...entriesFor("ciencia", "cie", ciencia),
  ...entriesFor("historia", "his", historia),
  ...entriesFor("cultura-pop", "pop", culturaPop),
];
