import type { BiomeId, ContentEntryInput } from "../src/content/catalog.js";
import { normalizeGridAnswer } from "../src/content/catalog.js";

type SeedRecord = readonly [
  answer: string,
  normalClue: string,
  simpleClue: string,
  difficulty: 1 | 2 | 3 | 4 | 5,
  familiarity: 1 | 2 | 3 | 4 | 5,
  tags?: readonly string[],
];

function entriesFor(biome: BiomeId, prefix: string, records: readonly SeedRecord[]): ContentEntryInput[] {
  return records.map(([answer, normal, simple, difficulty, familiarity, tags = []]) => ({
    id: `${prefix}-${normalizeGridAnswer(answer).toLowerCase()}`,
    answer,
    biomes: [biome],
    difficulty,
    familiarity,
    clues: { normal, simple },
    provenance: {
      source: "curadoria-cruzaverso-v2",
      license: "conteudo-original-do-projeto",
    },
    tags: [...tags],
  }));
}

const cotidiano: readonly SeedRecord[] = [
  ["abacaxi", "Fruto tropical coroado por folhas rígidas.", "Fruta grande, ácida e com casca espinhosa.", 1, 5, ["alimento"]],
  ["agenda", "Objeto ou sistema usado para organizar compromissos.", "Lugar onde se anotam horários e tarefas.", 1, 5, ["rotina"]],
  ["alicate", "Ferramenta articulada que concentra a força das mãos entre duas mandíbulas.", "Ferramenta usada para segurar peças e cortar arame.", 2, 5, ["ferramenta"]],
  ["almoço", "Refeição que costuma ocupar o meio do dia.", "Refeição feita por volta do meio-dia.", 1, 5, ["alimento"]],
  ["amizade", "Vínculo de afeto e confiança entre pessoas.", "Relação entre amigos.", 1, 5, ["relações"]],
  ["bicicleta", "Veículo leve movido por pedais.", "Transporte de duas rodas com pedais.", 1, 5, ["transporte"]],
  ["cafeteira", "Utensílio ou aparelho que prepara uma bebida torrada.", "Aparelho usado para fazer café.", 1, 5, ["cozinha"]],
  ["camiseta", "Peça casual que cobre o tronco e geralmente tem mangas curtas.", "Roupa leve usada na parte de cima do corpo.", 1, 5, ["roupa"]],
  ["carteira", "Objeto pequeno que guarda dinheiro e documentos.", "Onde se carregam cartões e notas.", 1, 5, ["objeto"]],
  ["chuveiro", "Equipamento doméstico que espalha água sobre o corpo.", "Aparelho usado para tomar banho.", 1, 5, ["casa"]],
  ["cozinha", "Cômodo onde alimentos são preparados.", "Parte da casa usada para cozinhar.", 1, 5, ["casa"]],
  ["crachá", "Cartão visível que apresenta nome ou função para reconhecer seu portador.", "Cartão com nome usado para identificar alguém.", 2, 5, ["trabalho"]],
  ["despensa", "Pequeno cômodo onde mantimentos aguardam o uso.", "Lugar da casa onde se guardam alimentos.", 2, 4, ["casa"]],
  ["domingo", "Dia da semana associado ao descanso em muitos calendários.", "Dia que vem depois de sábado.", 1, 5, ["tempo"]],
  ["escola", "Instituição dedicada ao ensino e à aprendizagem.", "Lugar onde alunos estudam.", 1, 5, ["rotina"]],
  ["escorredor", "Suporte vazado que recebe pratos e copos depois da lavagem.", "Suporte onde a louça fica para secar depois de lavada.", 2, 4, ["cozinha"]],
  ["família", "Grupo unido por parentesco ou laços de cuidado.", "Pais, filhos e outros parentes.", 1, 5, ["relações"]],
  ["feira", "Encontro periódico de vendedores em bancas.", "Lugar com barracas para comprar frutas e outros produtos.", 1, 5, ["cidade"]],
  ["fronha", "Envelope de tecido da roupa de cama que protege o apoio da cabeça.", "Capa de tecido que envolve o travesseiro.", 2, 5, ["casa"]],
  ["garagem", "Espaço destinado a guardar veículos.", "Parte da casa onde fica o carro.", 1, 5, ["casa"]],
  ["gorjeta", "Valor voluntário acrescentado à conta em agradecimento pelo atendimento.", "Dinheiro extra dado a quem prestou um serviço.", 2, 5, ["serviço"]],
  ["interruptor", "Peça que abre ou fecha um circuito com um toque.", "Botão usado para ligar e desligar a luz.", 2, 5, ["casa"]],
  ["janela", "Abertura que deixa entrar luz e ventilação.", "Abertura com vidro numa parede.", 1, 5, ["casa"]],
  ["lixa", "Superfície abrasiva passada repetidamente para nivelar ou polir.", "Papel áspero usado para alisar madeira ou metal.", 2, 4, ["ferramenta"]],
  ["mercado", "Estabelecimento com grande variedade de produtos de consumo.", "Lugar onde se compram alimentos e itens de casa.", 1, 5, ["cidade"]],
  ["mochila", "Bolsa carregada nas costas por duas alças.", "Bolsa usada nas costas para levar objetos.", 1, 5, ["objeto"]],
  ["mutirão", "Trabalho coletivo organizado por várias pessoas em benefício comum.", "Tarefa comunitária feita por muitas pessoas juntas.", 2, 4, ["comunidade"]],
  ["pipoca", "Grão estourado pelo calor, comum em sessões de filme.", "Milho estourado que se come no cinema.", 1, 5, ["alimento"]],
  ["quintal", "Área aberta ligada a uma residência.", "Espaço descoberto nos fundos ou na frente de uma casa.", 1, 5, ["casa"]],
  ["rascunho", "Versão provisória que ainda aceita cortes e correções antes de valer.", "Primeira versão de um texto, antes de passar a limpo.", 2, 5, ["escrita"]],
  ["receita", "Conjunto de instruções e ingredientes para preparar algo.", "Passo a passo para fazer um prato.", 1, 5, ["cozinha"]],
  ["rodapé", "Faixa de acabamento que acompanha o encontro entre parede e piso.", "Peça colocada na parte de baixo da parede.", 2, 4, ["casa"]],
  ["sapato", "Calçado fechado que protege os pés.", "Peça usada nos pés para caminhar.", 1, 5, ["roupa"]],
  ["sorriso", "Expressão facial associada a alegria ou simpatia.", "Expressão feita com a boca quando alguém está feliz.", 1, 5, ["relações"]],
  ["telefone", "Aparelho usado para conversar à distância.", "Dispositivo usado para fazer ligações.", 1, 5, ["objeto"]],
  ["trabalho", "Atividade realizada para produzir, servir ou obter renda.", "Atividade profissional de uma pessoa.", 1, 5, ["rotina"]],
  ["viagem", "Deslocamento para um lugar distante do habitual.", "Ato de ir conhecer ou visitar outro lugar.", 1, 5, ["transporte"]],
  ["vizinho", "Pessoa que mora perto de outra.", "Quem vive na casa ou apartamento ao lado.", 1, 5, ["relações"]],
  ["xícara", "Recipiente pequeno com asa, usado para bebidas quentes.", "Copinho com alça usado para tomar café.", 1, 5, ["cozinha"]],
  ["zíper", "Fecho cujo cursor une duas fileiras de dentes.", "Fecho de correr usado em roupas e bolsas.", 2, 5, ["roupa"]],
];

const ciencia: readonly SeedRecord[] = [
  ["aquífero", "Formação subterrânea permeável da qual se pode extrair água armazenada em poros e fraturas.", "Formação abaixo do solo que armazena água e abastece poços.", 3, 4, ["terra"]],
  ["átomo", "Unidade básica que preserva as propriedades de um elemento.", "Partícula que forma os elementos químicos.", 2, 5, ["quimica"]],
  ["bactéria", "Microrganismo unicelular sem núcleo delimitado.", "Ser microscópico formado por uma célula.", 2, 4, ["biologia"]],
  ["catalisador", "Substância que permite a uma reação seguir uma rota que exige menos energia.", "Substância que acelera uma reação e volta a ficar disponível no processo.", 3, 4, ["quimica"]],
  ["célula", "Menor unidade estrutural e funcional dos seres vivos.", "Unidade básica de um organismo vivo.", 1, 5, ["biologia"]],
  ["clima", "Padrão de condições atmosféricas observado por longos períodos.", "Comportamento do tempo de uma região ao longo dos anos.", 2, 5, ["terra"]],
  ["cometa", "Corpo gelado que pode formar cauda ao se aproximar de uma estrela.", "Astro que pode aparecer no céu com uma longa cauda.", 2, 5, ["astronomia"]],
  ["cristal", "Sólido cujas partículas formam uma estrutura ordenada.", "Sólido com átomos organizados em padrão regular.", 3, 4, ["quimica"]],
  ["elétron", "Partícula subatômica com carga elétrica negativa.", "Partícula negativa que fica ao redor do núcleo atômico.", 2, 5, ["fisica"]],
  ["energia", "Grandeza associada à capacidade de produzir transformação.", "Capacidade de realizar trabalho ou causar mudança.", 2, 5, ["fisica"]],
  ["enzima", "Catalisador biológico que acelera reações específicas sem ser destruído no processo.", "Molécula que ajuda reações da célula a acontecer mais rápido.", 2, 5, ["biologia"]],
  ["erosão", "Remoção e transporte de solo ou rocha por água, vento ou outros processos superficiais.", "Desgaste que leva pedaços de solo ou rocha para outro lugar.", 2, 5, ["terra"]],
  ["evolução", "Mudança hereditária de populações ao longo das gerações.", "Processo pelo qual espécies mudam com o tempo.", 2, 5, ["biologia"]],
  ["fóssil", "Vestígio preservado de um organismo de épocas passadas.", "Resto ou marca antiga de um ser vivo preservado em rocha.", 2, 5, ["terra"]],
  ["fóton", "Quantum associado à radiação eletromagnética.", "Partícula elementar da luz.", 3, 3, ["fisica"]],
  ["galáxia", "Grande sistema de estrelas, gás, poeira e matéria escura.", "Conjunto enorme de estrelas, como a Via Láctea.", 2, 5, ["astronomia"]],
  ["genoma", "Conjunto completo do material genético de um organismo.", "Todo o DNA de um ser vivo.", 3, 4, ["biologia"]],
  ["gravidade", "Interação que atrai corpos com massa.", "Força que puxa objetos em direção ao chão.", 2, 5, ["fisica"]],
  ["inércia", "Propriedade da matéria de resistir a mudanças em seu estado de movimento.", "Tendência de um corpo continuar parado ou em movimento uniforme.", 3, 5, ["fisica"]],
  ["isótopo", "Forma de um elemento com o mesmo número de prótons e diferente número de nêutrons.", "Átomo do mesmo elemento, mas com outra quantidade de nêutrons.", 3, 4, ["quimica"]],
  ["laser", "Dispositivo que emite luz coerente e concentrada.", "Feixe de luz muito concentrado.", 2, 5, ["fisica"]],
  ["magma", "Mistura de rocha fundida ou parcialmente fundida, cristais e gases abaixo da superfície.", "Rocha derretida que ainda está abaixo da superfície da Terra.", 2, 5, ["terra"]],
  ["magnetismo", "Fenômeno ligado a campos produzidos por cargas em movimento.", "Fenômeno que faz ímãs atraírem certos metais.", 3, 4, ["fisica"]],
  ["meteoro", "Rastro luminoso de um corpo ao atravessar uma atmosfera.", "Risco de luz causado por uma pedra espacial na atmosfera.", 2, 4, ["astronomia"]],
  ["mitose", "Processo nuclear que separa cromossomos já duplicados em dois conjuntos equivalentes.", "Processo que reparte cópias dos cromossomos entre dois novos núcleos.", 3, 4, ["biologia"]],
  ["molécula", "Conjunto eletricamente neutro de átomos ligados.", "Grupo de átomos unidos.", 2, 5, ["quimica"]],
  ["nebulosa", "Nuvem interestelar de gás e poeira que pode marcar o nascimento ou o fim de estrelas.", "Grande nuvem de gás e poeira entre as estrelas.", 3, 4, ["astronomia"]],
  ["neurônio", "Célula especializada em transmitir sinais no sistema nervoso.", "Célula que carrega sinais no cérebro e nos nervos.", 2, 5, ["biologia"]],
  ["órbita", "Trajetória de um corpo sob ação gravitacional ao redor de outro.", "Caminho de um astro ao redor de outro.", 2, 5, ["astronomia"]],
  ["oxigênio", "Elemento gasoso essencial à respiração de muitos organismos.", "Gás do ar usado na respiração.", 1, 5, ["quimica"]],
  ["planeta", "Corpo celeste que orbita uma estrela e domina sua vizinhança orbital.", "Mundo que gira ao redor de uma estrela.", 1, 5, ["astronomia"]],
  ["plasma", "Estado da matéria formado por gás ionizado, com íons e elétrons livres.", "Gás ionizado que forma o Sol e a maioria das estrelas.", 3, 4, ["fisica"]],
  ["polímero", "Substância composta por macromoléculas formadas pela repetição de unidades estruturais.", "Material de moléculas grandes feitas de muitas unidades repetidas.", 3, 4, ["quimica"]],
  ["proteína", "Macromolécula formada por cadeias de aminoácidos.", "Nutriente e molécula formada por aminoácidos.", 2, 5, ["biologia"]],
  ["pulsar", "Estrela de nêutrons em rotação rápida observada como pulsos regulares de radiação.", "Estrela de nêutrons que gira e parece piscar em intervalos regulares.", 4, 3, ["astronomia"]],
  ["quark", "Partícula elementar que compõe prótons e nêutrons.", "Partícula muito pequena encontrada dentro de prótons e nêutrons.", 4, 3, ["fisica"]],
  ["satélite", "Corpo que orbita outro de maior massa.", "Objeto natural ou artificial que gira ao redor de um planeta.", 2, 5, ["astronomia"]],
  ["telescópio", "Instrumento que coleta radiação para observar objetos distantes.", "Instrumento usado para enxergar astros distantes.", 2, 5, ["astronomia"]],
  ["vacina", "Preparação que treina o sistema imune contra um agente.", "Proteção que ensina o corpo a combater uma doença.", 1, 5, ["biologia"]],
  ["vulcão", "Estrutura geológica por onde material interno alcança a superfície.", "Montanha que pode expelir lava.", 1, 5, ["terra"]],
];

const historia: readonly SeedRecord[] = [
  ["abolição", "Ato político que extingue formalmente uma instituição ou prática.", "Fim oficial de uma prática, como a escravidão.", 2, 4, ["politica"]],
  ["acrópole", "Parte elevada e fortificada de antigas cidades gregas.", "Área alta de uma cidade da Grécia antiga.", 4, 2, ["antiguidade"]],
  ["apartheid", "Regime sul-africano que, a partir de 1948, institucionalizou a segregação e a dominação racial.", "Sistema oficial de segregação racial da África do Sul.", 3, 5, ["segregacao"]],
  ["armadura", "Conjunto defensivo usado por combatentes em épocas passadas.", "Proteção de metal usada por guerreiros.", 2, 5, ["medieval"]],
  ["arqueologia", "Disciplina que estuda sociedades por meio de vestígios materiais.", "Ciência que investiga povos antigos por seus objetos e ruínas.", 3, 4, ["pesquisa"]],
  ["bandeirante", "Integrante de expedições paulistas que avançaram pelo interior colonial para escravizar indígenas e procurar metais e pedras.", "Membro de expedições que saíam de São Paulo para capturar e escravizar indígenas no interior.", 3, 4, ["bandeiras"]],
  ["cabanagem", "Revolta popular em que insurgentes chegaram ao governo da província do Grão-Pará durante o período regencial.", "Revolta iniciada em 1835 no Grão-Pará, com forte participação popular.", 4, 3, ["brasil"]],
  ["califado", "Estado político-religioso governado por um califa em diferentes períodos da história islâmica.", "Estado islâmico liderado por um califa.", 4, 3, ["islam"]],
  ["capitania", "Grande divisão territorial da América portuguesa cuja administração podia ser entregue pela Coroa a um donatário.", "Território colonial administrado por um donatário.", 3, 4, ["brasil"]],
  ["caravela", "Embarcação de velas usada nas navegações ibéricas.", "Navio pequeno usado nas grandes navegações.", 2, 5, ["navegacoes"]],
  ["castelo", "Residência fortificada associada à nobreza medieval.", "Grande construção fortificada de reis e nobres.", 1, 5, ["medieval"]],
  ["catedral", "Templo que abriga a sede de um bispo.", "Grande igreja principal de uma diocese.", 2, 5, ["arquitetura"]],
  ["colônia", "Território submetido ao controle político de outra potência.", "Território governado por outro país.", 2, 5, ["politica"]],
  ["constituição", "Documento fundamental que organiza juridicamente um Estado.", "Conjunto principal de leis de um país.", 2, 5, ["politica"]],
  ["coroa", "Objeto simbólico ligado à autoridade monárquica.", "Adorno usado por reis e rainhas.", 1, 5, ["monarquia"]],
  ["coronelismo", "Sistema de poder local ligado a chefes políticos, pressão sobre eleitores e domínio oligárquico na Primeira República brasileira.", "Controle da política e dos votos por chefes locais na República Velha.", 3, 4, ["politica"]],
  ["dinastia", "Sequência de governantes pertencentes à mesma família.", "Família que governa por várias gerações.", 2, 4, ["monarquia"]],
  ["Egito", "Civilização antiga desenvolvida ao redor do rio Nilo.", "País dos faraós e das grandes pirâmides.", 1, 5, ["antiguidade"]],
  ["escrita", "Sistema de sinais que permitiu registrar fala, leis e memória.", "Forma de registrar palavras com símbolos.", 1, 5, ["cultura"]],
  ["faraó", "Título atribuído aos soberanos do antigo vale do Nilo.", "Governante do Egito antigo.", 1, 5, ["antiguidade"]],
  ["feudalismo", "Organização social europeia baseada em terras e vínculos de dependência.", "Sistema medieval de senhores, servos e feudos.", 3, 4, ["medieval"]],
  ["iluminismo", "Movimento intelectual do século XVIII que promoveu a crítica de autoridades e a confiança na razão e na investigação da natureza.", "Movimento europeu do século XVIII conhecido como Idade da Razão.", 3, 5, ["ideias"]],
  ["império", "Estado extenso que reúne diferentes povos sob uma autoridade central.", "Grande território governado por um imperador.", 2, 5, ["politica"]],
  ["independência", "Ruptura de subordinação política entre territórios.", "Quando um país deixa de ser governado por outro.", 2, 5, ["politica"]],
  ["monarquia", "Forma de governo cuja chefia é ocupada por um soberano.", "Governo liderado por rei ou rainha.", 2, 5, ["politica"]],
  ["museu", "Instituição que preserva e interpreta patrimônios.", "Lugar que guarda e exibe objetos históricos ou artísticos.", 1, 5, ["cultura"]],
  ["pergaminho", "Suporte de escrita feito de pele animal preparada, frequente em documentos e manuscritos antigos e medievais.", "Material de pele animal usado como página antes da difusão do papel.", 3, 4, ["escrita"]],
  ["pirâmide", "Construção monumental de base larga e faces triangulares.", "Monumento de pedra famoso no Egito antigo.", 1, 5, ["antiguidade"]],
  ["quilombo", "Comunidade histórica formada sobretudo por pessoas que resistiram à escravidão.", "Comunidade criada por pessoas negras que escapavam da escravidão.", 2, 5, ["brasil"]],
  ["república", "Forma de governo em que a chefia pública não é hereditária.", "Governo sem rei, com representantes escolhidos.", 2, 5, ["politica"]],
  ["revolução", "Transformação profunda e acelerada de uma ordem política ou social.", "Mudança radical na sociedade ou no governo.", 2, 5, ["politica"]],
  ["Roma", "Cidade que deu origem a uma potência central da Antiguidade ocidental.", "Capital de um grande império da Antiguidade.", 1, 5, ["antiguidade"]],
  ["samurai", "Membro da elite guerreira que exerceu poder militar, político e cultural no Japão entre os séculos XII e XIX.", "Guerreiro da antiga classe militar japonesa.", 2, 5, ["japao"]],
  ["senado", "Assembleia política cujo nome remonta à Antiguidade romana.", "Casa legislativa formada por senadores.", 2, 5, ["politica"]],
  ["sesmaria", "Concessão de terra condicionada ao aproveitamento produtivo, usada pela Coroa portuguesa na colonização do Brasil.", "Terra concedida pela Coroa para ser ocupada e cultivada.", 4, 2, ["brasil"]],
  ["sufrágio", "Direito político de participar da soberania por meio do voto, ampliado por lutas dos séculos XIX e XX.", "Direito político de votar.", 3, 4, ["direitos"]],
  ["Tiradentes", "Inconfidente mineiro transformado em símbolo cívico brasileiro.", "Personagem da Inconfidência Mineira executado em 1792.", 2, 5, ["brasil"]],
  ["tratado", "Acordo formal firmado entre Estados ou autoridades políticas.", "Documento de acordo entre países.", 2, 5, ["politica"]],
  ["tropeiro", "Condutor de tropas de muares que transportava mercadorias e notícias pelo interior brasileiro.", "Viajante que guiava mulas carregadas de mercadorias.", 3, 4, ["tropeirismo"]],
  ["viking", "Nome dado a navegadores escandinavos da Alta Idade Média.", "Navegador e guerreiro medieval da Escandinávia.", 2, 5, ["medieval"]],
];

const culturaPop: readonly SeedRecord[] = [
  ["acorde", "Unidade harmônica formada quando diferentes notas soam ao mesmo tempo.", "Grupo de notas musicais tocadas juntas.", 2, 5, ["teoria-musical"]],
  ["anime", "Produção de animação associada à indústria japonesa.", "Desenho animado produzido no Japão.", 1, 5, ["animacao"]],
  ["arcade", "Máquina pública dedicada a jogos eletrônicos de sessões curtas.", "Máquina de videogame encontrada em fliperamas.", 2, 4, ["games"]],
  ["aventura", "Gênero centrado em jornadas, riscos e descobertas.", "História de viagem, exploração e desafios.", 1, 5, ["genero"]],
  ["baralho", "Conjunto de cartas de jogar reunidas para disputar diferentes partidas.", "Coleção de cartas usada em jogos como truco e pôquer.", 2, 5, ["cartas"]],
  ["cinema", "Arte e indústria de narrativas projetadas em movimento.", "Arte de produzir e exibir filmes.", 1, 5, ["filme"]],
  ["claquete", "Quadro articulado que marca tomadas e produz uma batida útil à sincronização.", "Placa batida no início da filmagem para identificar a cena.", 3, 4, ["producao"]],
  ["controle", "Periférico segurado nas mãos para comandar um jogo.", "Aparelho com botões usado para jogar videogame.", 1, 5, ["games"]],
  ["cosplay", "Prática de vestir e interpretar personagens de obras populares.", "Fantasia usada para imitar um personagem.", 2, 4, ["fandom"]],
  ["detetive", "Personagem que investiga pistas para esclarecer um mistério.", "Investigador comum em histórias de mistério.", 1, 5, ["genero"]],
  ["discografia", "Relação organizada das gravações lançadas por um artista ao longo da carreira.", "Lista dos discos e álbuns de um cantor ou banda.", 3, 3, ["musica"]],
  ["documentário", "Gênero audiovisual de não ficção que constrói um olhar sobre pessoas, acontecimentos ou temas reais.", "Filme de não ficção sobre pessoas ou fatos reais.", 2, 5, ["filme"]],
  ["dragão", "Criatura fantástica frequentemente alada e associada ao fogo.", "Monstro lendário que costuma voar e soltar fogo.", 1, 5, ["fantasia"]],
  ["dublagem", "Processo que encaixa novas vozes nos movimentos de fala já filmados.", "Troca das vozes originais de um filme por vozes em outro idioma.", 2, 5, ["localizacao"]],
  ["emoji", "Pictograma colorido inserido no meio de mensagens eletrônicas.", "Pequeno símbolo, como uma carinha, enviado em conversas digitais.", 2, 5, ["internet"]],
  ["episódio", "Parte individual de uma obra seriada.", "Cada capítulo de uma série ou podcast.", 1, 5, ["serie"]],
  ["fandom", "Comunidade organizada em torno de uma obra ou artista.", "Grupo de fãs de uma série, jogo ou artista.", 2, 4, ["comunidade"]],
  ["fantasia", "Gênero que admite magia e mundos imaginários.", "Tipo de história com magia e criaturas inventadas.", 1, 5, ["genero"]],
  ["hashtag", "Marcador iniciado por cerquilha que reúne publicações sob o mesmo assunto.", "Palavra com o sinal de jogo da velha usada para marcar um tema nas redes sociais.", 2, 5, ["internet"]],
  ["herói", "Figura central que enfrenta obstáculos em favor de uma causa.", "Personagem corajoso que tenta salvar ou ajudar.", 1, 5, ["personagem"]],
  ["karaokê", "Entretenimento de cantar acompanhando uma faixa instrumental.", "Brincadeira de cantar seguindo a letra na tela.", 1, 5, ["musica"]],
  ["magia", "Força sobrenatural usada como recurso narrativo.", "Poder sobrenatural comum em histórias de fantasia.", 1, 5, ["fantasia"]],
  ["mangá", "Quadrinho ligado à tradição editorial japonesa.", "História em quadrinhos japonesa.", 1, 5, ["quadrinho"]],
  ["meme", "Unidade cultural remixada e compartilhada rapidamente em rede.", "Imagem ou piada que se espalha pela internet.", 1, 5, ["internet"]],
  ["musical", "Obra dramática em que canções conduzem parte da narrativa.", "Peça ou filme cuja história inclui muitas músicas.", 2, 4, ["musica"]],
  ["novela", "Narrativa televisiva longa exibida em capítulos frequentes.", "História de televisão dividida em muitos capítulos.", 1, 5, ["televisao"]],
  ["onomatopeia", "Palavra desenhada para fazer um ruído parecer audível na página.", "Palavra que imita um som, como miau ou bum.", 3, 4, ["quadrinho"]],
  ["pixel", "Menor elemento endereçável de uma imagem digital rasterizada.", "Pequeno ponto colorido que forma uma imagem na tela.", 1, 5, ["games"]],
  ["podcast", "Programa sonoro distribuído em episódios sob demanda.", "Programa de áudio ouvido pela internet.", 1, 5, ["internet"]],
  ["quadrinho", "Narrativa composta por imagens sequenciais e balões.", "História contada em desenhos e balões de fala.", 1, 5, ["quadrinho"]],
  ["roteiro", "Texto que organiza cenas, falas e ações de uma produção.", "Documento com cenas e falas de um filme ou série.", 2, 5, ["filme"]],
  ["seriado", "Produção audiovisual dividida em capítulos recorrentes.", "Programa de televisão contado em episódios.", 1, 5, ["serie"]],
  ["streaming", "Distribuição contínua de mídia pela rede sem download integral prévio.", "Forma de assistir ou ouvir conteúdo pela internet.", 2, 5, ["internet"]],
  ["sudoku", "Desafio lógico clássico que distribui os algarismos de um a nove sem repetição em linhas, colunas e regiões.", "Grade nove por nove em que os números não podem se repetir em cada linha, coluna ou bloco.", 2, 5, ["logica"]],
  ["super-herói", "Personagem de feitos extraordinários, frequentemente com identidade visual própria.", "Herói com poderes ou habilidades fora do comum.", 1, 5, ["personagem"]],
  ["tabuleiro", "Superfície marcada onde peças obedecem às regras de uma partida.", "Base onde se movem peças em jogos como xadrez e damas.", 2, 5, ["games"]],
  ["tirinha", "Narrativa gráfica curta que costuma caber numa única faixa de poucos quadros.", "História em quadrinhos curta, geralmente com três ou quatro quadros.", 2, 5, ["quadrinho"]],
  ["videogame", "Mídia interativa eletrônica comandada pelo jogador.", "Jogo eletrônico exibido numa tela.", 1, 5, ["games"]],
  ["vilão", "Personagem que se opõe aos objetivos do protagonista.", "Antagonista ou inimigo principal de uma história.", 1, 5, ["personagem"]],
  ["zumbi", "Morto reanimado recorrente em obras de horror.", "Criatura morta-viva comum em filmes e jogos.", 1, 5, ["terror"]],
];

export const bundledEntries: ContentEntryInput[] = [
  ...entriesFor("cotidiano", "cot", cotidiano),
  ...entriesFor("ciencia", "cie", ciencia),
  ...entriesFor("historia", "his", historia),
  ...entriesFor("cultura-pop", "pop", culturaPop),
];
